### ISSUE TITLE
Automate with text search on screen, exit Windows Chrome cleanly [done]

### ISSUE THREAD

**Issue by kensoh** [tebelorg/RPA-Python#101]
Raising an issue to add a couple of useful features that are going to be implemented in upcoming v6 release of TagUI. Due to fundamental changes from v6 onwards that have different goals from RPA for Python, a fork will be maintained here - https://github.com/tebelorg/TagUI/tree/rpa_python

The packaged installations of TagUI used by RPA for Python and automatically downloaded during init() will continue to be hosted here - https://github.com/tebelorg/Tump/releases/tag/v1.0.0

The main differences are being TagUI v6 onwards is business-user focused instead of being developer-focused. Thus some changes are contrary to what RPA for Python aims for, which is being developer-focused. The bet is more business users are likely to pick up Python in future.

Also, in TagUI v7 a migration from current PhantomJS engine to Node.js engine is being considered. That architecture overhaul would likely take some time to smooth rough edges, thus would not be used by RPA for Python in the near term. Also, there is a future possibility of rewriting RPA in Python so that it is purely written in Python without dependency on TagUI, and only dependent on SikuliX.

**Comment by kensoh** [comment]
The 2 features to be added from TagUI v6 -

1. enable specifying text on the screen as identifier to interact with (click, hover, snap, read etc)
2. exit Chrome cleanly on Windows if possible instead of showing browser ended unexpectedly

**Comment by kensoh** [comment]
Implemented in v1.24 and available with `pip install rpa --upgrade`

**Comment by kensoh** [comment]
Adding a note that some commits need to be added in upstream TagUI before this feature is usable.

**Comment by kensoh** [comment]
Done, feature ready in v1.24.1 and available with `pip install rpa --upgrade`

**Comment by parvindarb** [comment]
Hi Ken, than you for sharing this! I think it's a really useful package :) 
I have a quick question, not a bug but maybe I haven't searched well enough.
Is there a way to list all the URLs in a webpage and then be able to right click (this works) and select 'Open in a new tab' (I'm having trouble finding a way to select any option after the right click).
Any guidance would be appreciated.
Thanks!
Parv

**Comment by kensoh** [comment]
Hi Parv, thanks for your kind words and I hope you have fun using it!

I see.. The popup menu after right-click a link is not part of the webpage DOM I think. To do that, you can take a snapshot of the text and then do r.click('text.png'). Alternatively, with this new feature, you can try doing r.click('Open in a new tab.png') to let the tool use OCR to search for this text on the screen and click on it.

For listing all URLs on the webpage there is no in-built function to do that because a normal user process won't be working this way from the backend. You probably can write some function to loop and search for element of the URLs you want to look for, on a case by case basis. Searching by the //a identifier will return too many useless URLs.

**Comment by kensoh** [comment]
The API reference section (https://github.com/tebelorg/RPA-Python#api-reference) and the sample script has an example of this searching-by-text-visually feature.

https://github.com/tebelorg/RPA-Python/blob/28e32e1c19a292f6a343baf47a1f0e234f3e61ab/sample.py#L59

**Comment by parvindarb** [comment]
Thanks a lot for the quick response :) 
I do intend to have fun using this.. just need to get used to it first. 
Thanks for your tips, I'll try to follow.

**Comment by kensoh** [comment]
Made a minor update on bug fix from upstream TagUI project, which should not have impact on this package even if the bug fix is not applied here. But applying anyway in case I miss something.

Published package v1.24.2, available with `pip install rpa --upgrade`

**Comment by kensoh** [comment]
Rolling back the change on exiting Windows Chrome cleanly. The upstream change is not robust, rolling back until upstream TagUI project has implemented a robust way to hack Chrome exit.

Published package v1.25.2, available with `pip install rpa --upgrade`

**Comment by kensoh** [comment]
Upstream TagUI patch done, for Chrome to exit cleanly on Windows without the 'browser closed unexpectedly' popup message on launch of automation Chrome browser session.

Published package v1.26, available with `pip install rpa --upgrade`
