### ISSUE TITLE
Unable to attach to existing Chrome window - as designed or use visual

### ISSUE THREAD

**Issue by Atrivkumar** [tebelorg/RPA-Python#106]
I am not able to attach to the already opened window of chrome. I always need to open the new window of chrome

**Comment by kensoh** [comment]
Hi @Atrivkumar this is working as designed. To automate Chrome from backend it has to be started with some debugging flag in order for TagUI to talk to it and control it.

Existing sessions opened by users do not have that backdoor to allow the Chrome browser to be controlled through the backend using a WebSocket connection and DevTools Protocol.

If there is a use case that requires automating an existing running Chrome session, try doing everything using visual automation by providing image snapshots of the web elements. For eg,

```py
r.click('chrome.png')
r.type('email.png', 'test@gmail.com')
```

**Comment by kensoh** [comment]
Closing this issue for now until further inputs! This is not a natively supported use case as Chrome can't be controlled without launching it from the package with Chrome backdoor open. Workaround is use visual automation on existing user Chrome window.
