### ISSUE TITLE
How to get a list of all image matches on screen - use vision() or anchor

### ISSUE THREAD

**Issue by asagao-web** [tebelorg/RPA-Python#113]

**Comment by kensoh** [comment]
See below 2 examples using the vision() function. This can be done through the vision() function by using custom SikuliX commands. By first forming an iterator list, you can iterate through the list to interact with the matched elements on the screen.

However, where possible, other solutions could be explored. For example first, identifying an anchor element using hover(), after that get the x,y coordinates using mouse_x() and mouse_y(), and finally clicking on the item with an offset from the anchor element.

```py
import rpa as r
r.init(True, False)
r.vision('resultList = findAll("full_folder_path_to_filename.png")')
r.vision('if resultList.hasNext(): resultList.next().click()')
r.close()
```

```py
import rpa as r
r.init(True, False)
r.vision('resultList = findAll("full_folder_path_to_filename.png")')
r.vision('for result in resultList: result.highlight(1)')
r.close()
```

References for above custom SikuliX code -
https://stackoverflow.com/questions/40771261/sikuli-how-to-cycle-through-findall-matches
https://answers.launchpad.net/sikuli/+question/160030
http://doc.sikuli.org/region.html#Region.findAll

**Comment by asagao-web** [comment]
Ken, thank you very much again for answering my question so quickly.
I will try more on vision command, that should work for my purpose!
