### ISSUE TITLE
Scrolling using visual automation and dom() - pending user checks

### ISSUE THREAD

**Issue by soorejmg** [tebelorg/RPA-Python#117]
Hi I am trying to scroll using tagui on a page using the Visual automation method and Dom method which you suggested in tagui  page. both are not working. The hover method worked. Wondering why the visual automation and DOm is not working. 

Please see the code below:-

import tagui as t
t.init(visual_automation = True)
lpar_url='sample url'
server_names=["svr1","svr2","svr3","svr4","svr5"]
lpar_url_host='https://sampelhost'

currentServer=server_names[0]

t.url(lpar_url)

3. Enter the Server Name to Filter Box
t.type('//input[@id="menu-filter"]', currentServer)

4. ClickSearchIcon
t.click('//span[@class="ui-button-icon ui-icon ui-icon-search"]')

5.Click on the server name
click_server_string='//span[text()="'+currentServer+'"]'

6. Click Regroup Icon
t.click('//a[@title="Regroup"]')

7. tried different Scrolling methods. Hover works but not visual automation and DOM ones. Not even clicking on the chrome brower window.
Instead of the target window, scrolling happens in jupyter notebook itslef. The windows is not changing active to the application 

t.hover(f'(//div[@class="favs favoff far fa-star"])[{2}]')
// vision method
t.vision('click("lpar.png")')
t.wait(5)
t.keyboard('[down][down]')

//dom method
t.dom('window.scrollBy(0,1000)')

**Comment by kensoh** [comment]
Hi @soorejmg the hover() method works by telling Chrome to scroll a given web element into view.

For the visual automation method, you have to first do a step to click on the web browser (for click on some part of that web browser tab using visual automation) and the tab that you want to do the scrolling down. The down keystroke will be applied to the whatever is on the screen at the moment, ie the current active window and tab.

For dom() method, it may be the website that you are testing on does not support this scrolling command. When I run below code, the program will scroll down the google search results.

```py
import rpa as r
r.init()
r.url('https://google.com')
r.type('q', 'rpa for python[enter]')
r.dom('window.scrollBy(0,1000)')
r.wait(1)
r.dom('window.scrollBy(0,1000)')
r.wait(1)
r.dom('window.scrollBy(0,1000)')
r.wait(1)
r.close()
```
