### ISSUE TITLE
Trouble executing python scripts / phantomjs - TagUI question

### ISSUE THREAD

**Issue by adoravant** [tebelorg/RPA-Python#118]
Hi, im having trouble executing a python script inside the flow, Have tried inserting the whole chunk of code inside it,,. execution seems fine though, the script itself never launches and the flow just keeps running ahead. Tried launching it with run file.py and run /path/file.py  both execute browser briefly before crashing with this message error:

"Fatal Windows exception, code 0xc0000005.
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report".

python enviroment is fine, added phantom as well, also the script works when executed on its own.
``
py begin
import os
import openpyxl
import shutil
import timeit

start = timeit.default_timer()

def copyRange(startCol, startRow, endCol, endRow, sheet):
    rangeSelected = []
    # Loops through selected Rows
    for i in range(startRow, endRow + 1, 1):
        # Appends the row to a RowSelected list
        rowSelected = []
        for j in range(startCol, endCol + 1, 1):
            rowSelected.append(sheet.cell(row=i, column=j).value)
        # Adds the RowSelected List and nests inside the rangeSelected
        rangeSelected.append(rowSelected)

    return rangeSelected

def pasteRange(startCol, startRow, endCol, endRow, sheetReceiving, copiedData):
    countRow = 0
    for i in range(startRow, endRow + 1, 1):
        countCol = 0
        for j in range(startCol, endCol + 1, 1):
            sheetReceiving.cell(row=i, column=j).value = copiedData[countRow][countCol]
            countCol += 1
        countRow += 1

current_path = os.getcwd()
for ROOT, DIR, FILES in os.walk(current_path):
    for file in FILES:
        if file.endswith('xlsx') and file.startswith("Publicar"):
            excels = [file]

            for case in excels:
                base = openpyxl.load_workbook("ebook.xlsx")
                excel = openpyxl.load_workbook(case)

                basesheet = base['OHSHIT']
                excelsheet = excel['Libros']

                def get_counter(filename="scriptcounter.txt"):
                    with open(filename, "a+") as f:
                        f.seek(0)
                        val = int(f.read() or 0) + 1
                        f.seek(0)
                        f.truncate()
                        f.write(str(val))
                        return val

                counter = get_counter()
                fila = counter * 100
                DataCopiada = copyRange(1, fila, 22, (fila + 100), basesheet)
                pasteRange(1, 6, 22, 105, excelsheet, DataCopiada)
                excel.save(case)

                sourcepath = "C:\\tagui\\flows\\python" + "//" + case
                destination = "C:\\Users\\Cubano\\Downloads"
                shutil.move(sourcepath, destination)
                print(counter)

                stop = timeit.default_timer()

                print('Time: ', stop - start)
                break

py finish
echo `py_result````

**Comment by kensoh** [comment]
Hi @adoravant moving issue to https://github.com/kelaberetiv/TagUI/issues/773

as this is a TagUI question for its Python integration, and not related to this RPA for Python tool.
