### ISSUE TITLE
Possible to run .snap() for all HTML elements with same class name?

### ISSUE THREAD

**Issue by PolyScrub** [tebelorg/RPA-Python#121]
Hello! 

As the title goes, I'd like to ask if is there any way to screenshot multiple HTML elements that have the same class name?

**Comment by PolyScrub** [comment]
Nevermind, solved. Found out that XPath selectors allow for specifying the n-th occurrence of a searched element.

Reference: https://stackoverflow.com/questions/4007413/xpath-query-to-get-nth-instance-of-an-element

**Comment by kensoh** [comment]
Yes! What you found is correct. With Python loop control and XPath, you can do something like the following block of code. And it will output all the result URLs on first page of google search.

```py
import rpa as r
  
r.init()
r.url('https://google.com')
r.type('//*[@name="q"]','rpa[enter]')

# wait for result to appear before using present() to check
# present() does not wait until timeout like exist() does
r.hover('//*[@class="r"]')

for n in range(1, 1000):
    if r.present('(//*[@class="r"])[' + str(n) + ']'):
        print(r.read('(//*[@class="r"])[' + str(n) + ']/a/@href'))
    else:
        break

r.close()
```

**Comment by kensoh** [comment]
Or something like below if you already know the number of elements in advance -

```py
import rpa as r
  
r.init()
r.url('https://google.com')
r.type('//*[@name="q"]','rpa[enter]')

# for eg, if there is always 10 elements
for n in range(1, 11):
    print(r.read('(//*[@class="r"])[' + str(n) + ']/a/@href'))

r.close()
```
