### ISSUE TITLE
RPA in incognito browser - try this simple hack to enable incognito mode

### ISSUE THREAD

**Issue by richylyq** [tebelorg/RPA-Python#123]
> Query

Is it possible to run the RPA in incognito browser, instead of the normal browser instance.
i saw that it is possible to run in headless mode, but i am not sure whether incognito and headless mode serves the same purpose..
I am running RPA in my local jupyter notebook so please also direct the method to change the tagui.py file if there is a need to change anything. Thanks in advance

**Comment by kensoh** [comment]
Hi @richylyq as RPA for Python is meant to replicate normal usage of web browser, it does not have an option to run incognito or headless mode. However, there are hacks to do so if you wish.

For incognito mode, first find the folder where TagUI is automatically installed.

For Windows, location of TagUI is %APPDATA%\tagui (%APPDATA% is usually C:\Users\Username\Appdata\Roaming). Then open the file src\tagui.cmd for edit. Add in the incognito switch by changing
```
set chrome_switches=--user-data-dir=chrome\tagui_user_profile --remote-debugging-port=9222 about:blank
```
to
```
set chrome_switches=--user-data-dir=chrome\tagui_user_profile --incognito --remote-debugging-port=9222 about:blank
```

For macOS / Linux it is in ~/.tagui folder (~ is the user home folder, eg /Users/username for mac). Then open src\tagui for edit. Add in the incognito switch by changing
```
chrome_started="$(uname -s)"; chrome_switches="--user-data-dir=chrome/tagui_user_profile --remote-debugging-port=9222 about:blank"
```
to
```
chrome_started="$(uname -s)"; chrome_switches="--user-data-dir=chrome/tagui_user_profile --incognito --remote-debugging-port=9222 about:blank"
```

For reference, adding running in headless mode example here - https://github.com/tebelorg/RPA-Python/issues/109

However, note that these hacks will be gone when you upgrade the package to a new version.

**Comment by kensoh** [comment]
Incognito is not the same as headless. Headless means that the browser is invisible, automation running in background without seeing the browser at all. Incognito is when you want to prevent browsing history from being saved.
