### ISSUE TITLE
Internet Explorer Usage - try using visual automation and keyboard shortcuts

### ISSUE THREAD

**Issue by MikeZnnam** [tebelorg/RPA-Python#128]
I started to work with your RPA-Python solution just a few days ago and the handling of coding is just awesome. Especially that you made the package offline ready is a huge benefit for me. 

I have to do about 3000 adjustments on attributes on a pretty old system which only supports the internet explorer. Even though not all fields are marked with tags and can be called directly. Furthermore these fields are only working in the IE. 

Is there any possibility to use directly the IE instead of chrome, with the init?

Best, 
Mike

**Comment by kensoh** [comment]
Hi Mike, thank you for sharing your positive user experience!

I see, I'm afraid the upstream project TagUI does not support IE natively. IE does not use the DevTools protocol which TagUI uses to communicate directly with Chrome through a WebSocket connection.

However, depending on your scenario, it may still be possible to automate the process. The idea is to use visual automation method - https://github.com/tebelorg/RPA-Python#visual-automationsee_no_evil

By providing snapshots of UI elements, RPA for Python can interact with the IE webpage by using computer vision to find the best match of what you are trying to interact with. You can combine with keyboard automation - https://github.com/tebelorg/RPA-Python#keyboard-automationmusical_keyboard

For eg clicking onto a field visually or an offset from an anchor (reference UI element), or tabbing to the field, or doing a `r.dclick('field.png'); r.keyboard('[ctrl]c'); value = r.clipboard();` to read values from the webpage.

The launching of IE and entering the address can also be done using visual automation and keyboard shortcuts, essentially, replicating the steps a human user would do to launch IE and go to a website.

**Comment by MikeZnnam** [comment]
Hi Kenosh, 
well I tougth so. But better then no automation ;) 

With the keyboard automation I have some problems. 
"r.click('RaumSperren.png')
r.type('SperreVon.png','29.04.2020')
r.type('SperreBis.png','29.04.2028')
r.keyboard('[TAB]')"
This code is working, but when I now add another keyboard statement, like:
r.keyboard('Raum wurde überführt[ENTER]')
The last keyboard statement is not proceeded. 

Do you know why? 

Best,
Mike

**Comment by kensoh** [comment]
Oh yes, a component for RPA for Python, SikuliX, has a limitation to use extended ASCII characters. To type the special characters, try below workaround to set and paste the text -

```py
r.vision('a = "some text with special characters"')
r.vision('paste(ucode(a))')
```

I'm afraid there isn't an API built-in to do this. With the vision() function, you can google to see how to do this in SikuliX, then use the function to do that. Alternatively, if possible, see if the various UI elements are at some fixed offset from each other. If it is, you can use the first element matched as the anchor. Then use mouse_x() and mouse_y() to click subsequent ones.

```py
r.click('Auswahl.png')
r.click(mouse_x() + 100, mouse_y())
r.click(mouse_x() + 100, mouse_y())
r.click(mouse_x() + 100, mouse_y())
```

**Comment by MikeZnnam** [comment]
Thanks for the hint with SkuliX. I will try some methods which they provide.

Yes the way you showed, with just adding additional pixels to the mouse movement was what I did as well and my kind of quick and dirty solution.
