### ISSUE TITLE
Automating RPA with Windows Task Scheduler - change initial directory

### ISSUE THREAD

**Issue by giragosian** [tebelorg/RPA-Python#135]
Hi Ken,
I am a big fan and very impressed with the solution you have developed. 
I have a very simple python file. I call that python code from a batch file in windows. 
=====================================================
### this is my python code....

import rpa as r

r.init()
r.url('https://www.google.com')
r.type('//*[@name="q"]', 'who is giragosian[enter]')
print(r.read('result-stats'))
r.wait(5)
r.snap('page', 'results_rpa_test.png')
r.wait(3)
r.close()

=====================================================
This code executes flawlessly. Even when I run the batch file manually, it runs without any issues.
=====================================================
this is the code in my batch file.... just one line....
 
py  C:\rpa_test_20200430.py
=====================================================

When I call that batch file from the Window Scheduler, I get the following errors.... 
I tried this in several devices, and I get the same result. 

Why am I getting this and how I may automate the invocation of that batch file from Windows Task Scheduler?   
How can I invoke this batch file automatically through an scheduler? 
=============================================== 

C:\WINDOWS\system32>py C:\rpa_test_20200430.py
-nurThe system cannot find the file specified.
cut: write error: Invalid argument
-nurThe system cannot find the file specified.
cut: write error: Invalid argument
-nurThe system cannot find the file specified.
-nurThe system cannot find the file specified.
cut: write error: Invalid argument
-nurThe system cannot find the file specified.
-nurThe system cannot find the file specified.
cut: write error: Invalid argument
[RPA][ERROR] - following happens when starting TagUI...

ERROR - cannot find C:\Windows\System32\rpa_python
Unable to open file: C:\Windows\System32\rpa_python.js

  phantomjs://code/bootstrap.js:113 in __die
Unable to load script C:\Windows\System32\rpa_python.js; check file syntax

  phantomjs://code/bootstrap.js:113 in __die
gawk: cmd. line:2: fatal: cannot open file `C:\Windows\System32\rpa_python.raw' for reading (No such file or directory)
gawk: cmd. line:2: fatal: cannot open file `C:\Windows\System32\rpa_python.js' for reading (No such file or directory)

[RPA][ERROR] - use init() before using url()
[RPA][ERROR] - use init() before using type()
[RPA][ERROR] - use init() before using read()

[RPA][ERROR] - use init() before using snap()
===============================================

Thank you for making your extensive knowledge and experience available to us!!!!!

**Comment by kensoh** [comment]
Hi @giragosian thanks very much for sharing your positive experience!

From above error logs, it looks like Task Scheduler starts the program in folder `C:\Windows\System32` and the error most likely is because program can't write to that Windows System protected folder, thus causing all kinds of errors.

I don't have a Windows laptop to test, but here are a few things you can try -
1. is there option in task scheduler to choose folder to start task? if yes choose the same directory as your python script, in above case, it is C:\
2. try adding `import os; os.chdir('C:\\')` before r.init() in your script, to see if changing directly before launching TagUI process works for this situation
3. try creating a simple Windows batch file with below contents, for eg automation.bat or automation.cmd both extension is ok. then add this file to task scheduler. this will ensure that the directory is changed to C:\ before running Python.
>```
>@echo off
>cd C:\
>py C:\rpa_test_20200430.py
>```

Let me know which works!

**Comment by giragosian** [comment]
Dear Ken,

You are absolutely right, it is a permission issue. Apparently Task manager by initiating this process attempts to create some files and Windows does not let that happen, due to permission issue. 

When I add one line of simple python code to print the current date/time for me in the beginning of the process, that print line runs fine, then error messages started popping up as soon as that r.init() line gets executed..... my point is all other type of python code that have nothing to do with rpa or tagui (packages/modules) code runs without any issue. However, when I run (via Windows Task Scheduler) any code that leverages those python modules, then those "permission related" error codes start showing up.  

Also, I did downloaded a 3rd party job/process scheduler, and that could call the batch job and run everything (even the calls to rpa or tagui (packages/modules)). That kinda solves my problem, as a workaround. But later I will investigate further to solve this. My thoughts are calling any method on those modules causes Python to create some files (such as rpa_python, rpa_python.js, rpa.python.log, rpa_python.raw, tagui_local.js), and because Windows Task Scheduler does not have permission to create those files, it fails..... please view the attached the image of these files getting generated. After Python finished the code execution, it cleans up theses file. But I bet that is the source of the problem.  

Anyway , I truly appreciate your thoughts and guidance on this and on every other area that you have shared with us. Over the last few days I have learn significantly on python rpa/tagui from you and hats off to you! 
![1](https://user-images.githubusercontent.com/64618128/80830010-13690f00-8b9d-11ea-9bf1-4809a743c447.png)

**Comment by kensoh** [comment]
Hi @giragosian thanks for your appreciation! Hope you and your friends will have fun using it.

What you said is yes the most likely cause, Task Scheduler not allowing the files to be created and thus can't run properly. `C:\\` sometimes is a folder which users have no permissions to modify, depending on company IT policy.

However, there should at least be some folder which Task Scheduler is allowed to create files. For the steps above, try changing the directory to your user desktop folder (provided there is no space in the user name and folder name). Hopefully that will allow TS to create files on your desktop and let it run.

But of course, using a professional scheduler should do a better job than the built-in TS!
