### ISSUE TITLE
Access web elements - try XPath or smart identifier using attributes directly

### ISSUE THREAD

**Issue by ongkokl** [tebelorg/RPA-Python#136]
Hi @kensoh 

I trying to do a simple login to a web site but got the error:
[RPA][ERROR] - cannot find //*[@id="userid"]

![web page elements](https://user-images.githubusercontent.com/50367330/80798975-349b2100-8bd8-11ea-8e0a-0994f9abf477.png)

`
import rpa as r
r.init()

r.url('https://some.web.com')
r.type('//*[@id="userid"]','ongkokleong', 'tagui[enter]')

r.close()
`

**Comment by kensoh** [comment]
Hi @ongkokl, in above website, the attribute is the name attribute, so the XPath should be -

`r.type('//*[@name = "userid"]', 'ongkokleong')`

Also, there is no 3rd parameter in above usage so `'tagui[enter]'` should not be there.

For more on XPath, can look at this - https://www.w3schools.com/xml/xpath_intro.asp

But it is still not the best resource. I haven't found a good resource on XPath. Most is either too much details for automation use cases, or too brief to be useful.

Lastly, there is smart identifier system. So above example, `r.type('userid', 'ongkokeong')` might also work, if there are no other elements with that specific string as attributes. The priority order of the smart identifier attributes is here - https://github.com/tebelorg/RPA-Python#element-identifiers
