### ISSUE TITLE
How to select on multi check boxes - use XPath with element number

### ISSUE THREAD

**Issue by ongkokl** [tebelorg/RPA-Python#137]
Hi @kensoh 

Thanks for the previous guide.

For a drop down field, how do i multi select the items that i want to tick on the checkbox?
Example i want to select item 1,2,3,4,5

![select](https://user-images.githubusercontent.com/50367330/80803195-281cc580-8be4-11ea-9efc-dc6481c7bea3.png)

`r.click('//*[@class = "mat-select-arrow"]')

r.select('//*[@class = "mat-option-text"]', '1','2','3')

r.click('//*[@class = "button_generate"]')
`

**Comment by kensoh** [comment]
There should be an XPath matching the checkbox. For example if XPath is `//*[@name = "check"]`, then you can use `(//*[@name = "check"])[1]` to refer to the first checkbox, and `(//*[@name = "check"])[2]` to the second checkbox and so on. Then just use r.click() to click one by one.

**Comment by ongkokl** [comment]
> There should be an XPath matching the checkbox. For example if XPath is `//*[@name = "check"]`, then you can use `(//*[@name = "check"])[1]` to refer to the first checkbox, and `(//*[@name = "check"])[2]` to the second checkbox and so on. Then just use r.click() to click one by one.

Hi @kensoh 

For this part kinda confuse, here I attaching the screenshot of the elements 
![select](https://user-images.githubusercontent.com/50367330/80804503-f3127200-8be7-11ea-8c82-d3f64856af84.png)

**Comment by kensoh** [comment]
In this case, if use @class then can use above method. But there are unique identifiers.

Just use `r.click('mat-option-2')`, `r.click('mat-option-3')`, ...
