### ISSUE TITLE
Click on button not running - user closed issue without further info

### ISSUE THREAD

**Issue by ongkokl** [tebelorg/RPA-Python#138]
Hi @kensoh 

Last question for the evening , my first Python RPA mini project is almost done :)

Why the r.click('//*[@class = "report-inventory__search-button-label"]') seem doesnt running ?
While i testing it with remove the r.clicks on above, it does run.

`
#r.click('//*[@class = "mat-select-arrow"]')
#r.click('mat-option-0')
#r.click('mat-option-1')
#r.click('mat-option-5')
#r.click('mat-option-6')

**r.click('//*[@class = "report-inventory__search-button-label"]')**
`

**Comment by kensoh** [comment]
If something cannot be found, it will timeout after 10 seconds and show error message. For Class attribute, normally we write as `@class` lowercase. One way to test something is run in Python interactive mode (type python command from command prompt), or use Jupyter notebook.

That way, you can test each step to see what's working and why not working. Also, if you do r.debug(True) you will get log and output to screen all the automation in the background, that can help see where the problem too.

**Comment by ongkokl** [comment]
> If something cannot be found, it will timeout after 10 seconds and show error message. For Class attribute, normally we write as `@class` lowercase. One way to test something is run in Python interactive mode (type python command from command prompt), or use Jupyter notebook.
> 
> That way, you can test each step to see what's working and why not working. Also, if you do r.debug(True) you will get log and output to screen all the automation in the background, that can help see where the problem too.

Hi @kensoh 

Thanks , I managed to figure out .

I saw the video on the redmart use case to send outlook mail. Do I need to import other library for it ?

**Comment by kensoh** [comment]
I don't think there is a video on RedMart and Outlook. For RedMart, it is normal web automation. For sending email using Gmail or MS Outlook, you can try using the visual automation method - https://github.com/tebelorg/RPA-Python#visual-automationsee_no_evil and keyboard automation https://github.com/tebelorg/RPA-Python#keyboard-automationmusical_keyboard

Here is an example combining DBS website and Gmail sending. It is for TagUI, but from there you can get an idea the syntax for RPA for Python.

https://github.com/aimakerspace/TagUI-Bricks/tree/master/DBS-Forex-Gmail

**Comment by kensoh** [comment]
No need to import any other library.

**Comment by ongkokl** [comment]
@kensoh 

I thought I had solved the issue but the click button still not working.

[RPA][28] - exist_result = exist('report-inventory__search-button-label').toString()
[RPA][28] - listening for inputs
[RPA][29] - dump exist_result to rpa_python.txt
[RPA][29] - listening for inputs
[RPA][30] - click report-inventory__search-button-label
[RPA][30] - listening for inputs
<function tagui.close()>

`r.click('//*[@class = "mat-select-arrow"]')
r.click('mat-option-0')
r.click('mat-option-1')
r.click('mat-option-5')
r.click('mat-option-6')

r.debug(True)
r.click('report-inventory__search-button-label')
r.close`

**Comment by ongkokl** [comment]
> If something cannot be found, it will timeout after 10 seconds and show error message. For Class attribute, normally we write as `@class` lowercase. 
when i copy and paste the code here, it auto changed to "**C**lass" , big cap.

**Comment by kensoh** [comment]
Thanks for sharing your solution!

Interesting web element that needs to click twice to work. I assume you are saying for normal human user click once works but for automation need to click twice. The visual automation method could also be handy as it replicates the human user click instead of simulating the click within Chrome browser. Just need to make sure that Chrome browser is in focus first (eg doing a click visually on the Chrome icon on taskbar).

**Comment by kensoh** [comment]
Closing the issue for now till further inputs

**Comment by LucieGattepailleQB** [comment]
I experienced the same issue, and the fix above works. In my case, the first r.click(element) got the view of the page to move to the element and the second r.click(element) got it to be clicked like I wanted.
Thanks a lot for finding a fix!
