### ISSUE TITLE
How to attach a specific file

### ISSUE THREAD

**Issue by ongkokl** [tebelorg/RPA-Python#139]
Hi @kensoh 

I have managed to automated the email but come to attach file I'm stuck on it.

Question
After clicked on the "Attach"  on the web base MS Outlook, windows file explorer will pop out.
From there how do i click on the specific folder and click on the file that i want to attach?

p/s: im using Juypter with the TaUI web Automation chrome extension

`r.url ('https://outlook.office365.com/mail/inbox')

#Click on new message 
r.click('//*[@id = "id__3"]')
            
#email To
r.type('//*[@aria-label = "To"]','to1@gmail.com;to2@gmail.com')

#email Cc
r.type('//*[@aria-label = "Cc"]','CC@gmail.com')

#Add a subject
r.type('//*[@aria-label = "Add a subject"]',' Inventory Report')

#email content
r.type('//*[@aria-label = "Message body"]','Dear boss\n\nAttached the daily inventory report\n\nRegards\n')

r.click('//*[@name = "Attach"]')

r.click('//*[@name = "Browse this computer"]')`

**Comment by ongkokl** [comment]
i managed to figure out , just use r.click('image.PNG') , OCR :)

**Comment by kensoh** [comment]
Oh great! For some upload forms, the r.upload() function may be able to work on it, by providing the CSS selector as input (copy selector after inspecting from Chrome Inspector).

https://github.com/tebelorg/RPA-Python#pro-functions
