### ISSUE TITLE
How to end the cmd.exe after close() - check Windows setup used to run

### ISSUE THREAD

**Issue by ongkokl** [tebelorg/RPA-Python#142]
Hi @kensoh 

I'm running with cmd batch file.
C:\Users\ongkokl\AppData\Local\Continuum\anaconda3\python.exe C:\Users\ongkokl\Desktop\RPA\STORING.py 

After all the processes end; final line is r.close()

Is there API to end all the runnning cmd.exe ?

![Capture](https://user-images.githubusercontent.com/50367330/81244414-f6bd5300-9044-11ea-9cb5-cd26a87239c1.PNG)

**Comment by kensoh** [comment]
Hi @ongkokl that sounds like the setup which you run the batch file. If the batch file is run by double-clicking on it, it should close after running. If you are running with cmd.exe command, make sure you are using cmd.exe /c switch to end process after execution - 

https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cmd

You can write a simple Python script without using RPA for Python, and test / modify your setup until it works. Then run that way for RPA for Python to see if that setup continues to work.

**Comment by ongkokl** [comment]
@kensoh 

i managed use taskkill to kill the batch file cmd.exe in the python script.
`taskkill /f /im notepad.exe`

but the remaning 2 cmd windows still active...?

![Capture](https://user-images.githubusercontent.com/50367330/81945688-01717c80-9631-11ea-8952-d80eafb4854b.PNG)

**Comment by kensoh** [comment]
I don't think it is normal behaviour for the windows not to close after finishing.

Try the following - 

1. Run a simple python script.pyb from command line on a simple automation. Try on another computer. 

2. Try your setup using batch file or scheduler on another computer. It could be some setup issue on your computer, or the way your batch file is configured to not close after running.

I don't have a Windows computer to replicate what you are experiencing. Best is try above 2 ideas on another computer to see if it is something to do with your computer or batch file config.

**Comment by ongkokl** [comment]
> I don't think it is normal behaviour for the windows not to close after finishing.
> 
> Try the following -
> 
> 1. Run a simple python script.py from command line on a simple automation. Try on another computer.
> 2. Try your setup using batch file or scheduler on another computer. It could be some setup issue on your computer, or the way your batch file is configured to not close after running.
> 
> I don't have a Windows computer to replicate what you are experiencing. Best is try above 2 ideas on another computer to see if it is something to do with your computer or batch file config.
> 
> You can also run running a simple batch file with just the line dir and see if the window close after running. If not close, confirm is issue with batch file setup to run and not close after running.

Hi @kensoh 

this is the batch file:

![image](https://user-images.githubusercontent.com/50367330/82111359-4d2e3e00-9777-11ea-94c5-75b8d37bfef3.png)

**Comment by kensoh** [comment]
Closing issue for now until further inputs on suggestions 1 to 3 above - https://github.com/tebelorg/RPA-Python/issues/142#issuecomment-629587072
