### ISSUE TITLE
Data type error? - looks like Python / Pandas programming error in user script

### ISSUE THREAD

**Issue by ongkokl** [tebelorg/RPA-Python#145]
Hi there

My data type is object , and i have used astype(str) to do the  conversion but keep on getting the error.

`r.type('//*[@name="actionForm.SO.containerNoList"]', df['Cntr_Number'].astype(str))
`
![image](https://user-images.githubusercontent.com/50367330/82747450-6d8b7780-9dcb-11ea-97a2-b55664eeac8b.png)

**Comment by kensoh** [comment]
From error message above, it looks like you have a Python / Pandas error. If you try `print(df['Cntr_Number'].astype(str))` you might also get the same error.

If it does, then this has nothing to do with the package but some error in how you write your Python and Pandas code, will need to google and debug in that direction.

**Comment by ongkokl** [comment]
> From error message above, it looks like you have a Python / Pandas error. If you try `print(df['Cntr_Number'].astype(str))` you might also get the same error.
> 
> If it does, then this has nothing to do with the package but some error in how you write your Python and Pandas code, will need to google and debug in that direction.

solved the error with this code:
`df.loc[:,'Cntr_Number'] = df.Cntr_Number.apply(lambda x: str(x)+',')`
