### ISSUE TITLE
How to type 20 fields and repeat - Python programming question

### ISSUE THREAD

**Issue by ongkokl** [tebelorg/RPA-Python#146]
Hi there

I have a single dataframe column "Number" with x number of rows.

Example:
Number
ABCD 1234567,
ABCD 3243555,
GHYT 5555557;
TYUU 3456567;
....
...
...
...

On the web application, it only allowed to enter max 20 "Number" of rows per time and then click on a "Submit" button.

So how can i implment a method that the RPA will repeat the copy and paste for x number of times until it finished all the rows?

Copy and paste the first 20 rows -> click on Submit.
Copy and paste the next 20 rows -> click on Submit.
Copy and paste the next next 20 rows -> click on Submit.
.....
....
until the end of rows.

Thanks

**Comment by kensoh** [comment]
This is a Python question, answer will have to find on google or learn the basics of Python programming. A possible structure will be a while loop and inside the while loop is a for loop for 20 iterations. Then break for loop and while loop if no more items in data frame.

For the RPA for Python part, it's the usual `type()` function. For real copy and paste, `keyboard()` and `clipboard()` can be used. But above looks like just typing data into a webpage.
