### ISSUE TITLE
Send dataframe data to r.type() - Python Pandas dataframe question

### ISSUE THREAD

**Issue by ongkokl** [tebelorg/RPA-Python#148]
Hi there

Pls see the below error when i used this r.type() code. 

Is it due to the dataframe "Cntr_Number" with more than a row?
How can i overcome it?

Thanks

`r.type('//*[@name="actionForm.SO.containerNoList"]', df['Cntr_Number'])
`

![image](https://user-images.githubusercontent.com/50367330/83374805-42bea600-a3ff-11ea-9247-f32be0cd0bd6.png)

**Comment by kensoh** [comment]
This is a Python Pandas dataframe usage question. You can google how to use and access data in Pandas dataframe, or maybe other users who use dataframes can answer.

type() parameter 2 is string. As long as you provide a string value it'll work. You are providing an array of strings to type() which is incorrect usage for dataframe to return 1 value.

**Comment by ongkokl** [comment]
> This is a Python Pandas dataframe usage question. You can google how to use and access data in Pandas dataframe, or maybe other users who use dataframes can answer.
> 
> type() parameter 2 is string. As long as you provide a string value it'll work. You are providing an array of strings to type() which is incorrect usage for dataframe to return 1 value.

@kensoh 

Thanks , i have it changed to list and converted to string.
