### ISSUE TITLE
xpath error - special xpath syntax in the element, try alternative ways

### ISSUE THREAD

**Issue by ongkokl** [tebelorg/RPA-Python#149]
Hi there

Im not able to figure out this error , pls help.

My code:
`
r.type('//*[@name="{actionForm.SO.containerNoList}"]', fullStr)`
[RPA][ERROR] - cannot find //*[@name="{actionForm.SO.containerNoList}"]

web html source:

![image](https://user-images.githubusercontent.com/50367330/83939683-6f185f00-a811-11ea-9844-637cfbfc08ab.png)

**Comment by kensoh** [comment]
The {} in above element looks like a syntax that treats the string inside as a variable to get the value. One way is you google and figure out what is the string value of the variable, another way is you reference the parent and then link to it.

For example, `//*[@class="tablebody"]/textarea`, if there is only 1 tablebody element in the page. If there is more you can try `(//*[@class="tablebody"]/textarea)[n]` in the Chrome inspector to figure out which n is it.

**Comment by ongkokl** [comment]
Hi @kensoh 
It have more than 1 tablebody element, how do I use the `(//*[@class="tablebody"]/textarea)[n]` to try in the chrome inspector?


![image](https://user-images.githubusercontent.com/50367330/84609489-cd1c0500-aee9-11ea-84e7-e6eee3ff29cd.png)

**Comment by kensoh** [comment]
When you type `(//*[@class="tablebody"]/textarea)[1]` it will highlight the element 1 in Chrome inspector. Then you check whether that is same one you are looking for by right-click and inspect the element.

**Comment by ongkokl** [comment]
@kensoh 

Sorry,  i dont really get what i need to do ?

"When you **type (//*[@class="tablebody"]/textarea)[1] it will highlight the element 1 in Chrome inspector. "**

![image](https://user-images.githubusercontent.com/50367330/84638631-d4630300-af29-11ea-8f28-7aea58f9d6a6.png)

**Comment by kensoh** [comment]
Google on how to use Chrome inspector, there is a text box there for users to enter XPath to test if elements matching the XPath string exist on the web page.

**Comment by ongkokl** [comment]
Hi @kensoh 

I have managed to check and confirm it is [1] on the chrome inspector.
But still got error with it.

`r.type('(//*[@class="tablebody"]/textarea)[1]', fullStr)`

[RPA][ERROR] - cannot find (//*[@class="tablebody"]/textarea)[1]


![Capture](https://user-images.githubusercontent.com/50367330/84658268-3599cf00-af48-11ea-9f37-93be522fde6c.PNG)

**Comment by kensoh** [comment]
A possibility can be the element exists within a web frame. If search frame and there is some frame, then have to use r.frame() to select the frame first.

**Comment by kensoh** [comment]
Each web frame is actually a web page by itself. Combined into a master webpage.
