### ISSUE TITLE
Error on example - looks like TagUI can't run on your PC, try this

### ISSUE THREAD

**Issue by CryptoKR** [tebelorg/RPA-Python#151]
I get : 
[RPA][ERROR] - following happens when starting TagUI...

[RPA][ERROR] - use init() before using url()
[RPA][ERROR] - use init() before using type()
[RPA][ERROR] - use init() before using read()

[RPA][ERROR] - use init() before using snap()
[RPA][ERROR] - use init() before using close()

when trying:

r.init()
r.url('https://www.google.com')
r.type('//*[@name="q"]', 'decentralization[enter]')
print(r.read('result-stats'))
r.snap('page', 'results.png')
r.close()

What does it mean???

**Comment by kensoh** [comment]
It looks like for some reason, the tool that this package depends on (TagUI), can't run on your PC.

Most often it is related to company firewall and internet policy block, but could be stg else.

It is not easy to troubleshoot this. The easiest way is to actually download and install TagUI using below links and follow the test steps to run to see what is the error when launching.

https://github.com/kelaberetiv/TagUI
https://tagui.readthedocs.io/en/latest/setup.html
