### ISSUE TITLE
Get HREF where title=xy - this is an XPath question, try this way

### ISSUE THREAD

**Issue by MikeZnnam** [tebelorg/RPA-Python#152]
I'm struggeling with a little problem. For the project which I'm currently working on, I have to get the HREF link of several elements where the titel is = "Löschen". Is there any function from RPA Python which I could use for this?

Thank you in advance!

**Comment by kensoh** [comment]
The XPath syntax should be something like this - 
r.read('//*[@title="Löschen"]/@href')

For the nth occurrence, try stg like this - 
r.read('(//*[@title="Löschen"]) [n]/@href')
r.read('(//*[@title="Löschen"]/@href)[n]')

**Comment by ashoktcr** [comment]
Can you please tell me how to read  only href link from below
<a href="https://url.com">Test</a>  ?
