### ISSUE TITLE
How to scrape element array - use XPath with element number

### ISSUE THREAD

**Issue by pennsong** [tebelorg/RPA-Python#154]
First of all, thanks for your great work, I'd like to know how to get the elements array as in chrome console: $$("div.item"), then, i can iterate the arrays to click the items, thanks in advance

**Comment by kensoh** [comment]
Hi Penn, in theory, you can pass back the object through stringified JSON using `r.dom()`, then parse it back into an object.

However, it is much easier to code and maintain the script, if you use XPath to reference the elements array. The syntax is `(XPath)[n]` where n is the nth element that matches the XPath provided. `r.count()` can be used to detect how many elements in total to loop through and process. [See eg here](https://github.com/tebelorg/RPA-Python/issues/24).
