### ISSUE TITLE
Need assistance with Chrome form submit button on Mac

### ISSUE THREAD

**Issue by SNavgale** [tebelorg/RPA-Python#171]
Hi,

I have HTML snippet of page I am trying to work with. It was working few days ago and suddenly stopped working.
The page I am trying to work with is https://www.halifax-intermediaries.co.uk/tools_and_calculators/mortgage_affordability_calculator/default.aspx

`"input type="submit" name="ctl00$ContentPlaceHolder$ctl00$submitproduct" value="Calculate" onclick="pageTracker._trackPageview('/tools/AffordabilityCalculator/submit-click');WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ContentPlaceHolder$ctl00$submitproduct&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))" id="ctl00_ContentPlaceHolder_ctl00_submitproduct" title="Calculate" class="submit" "`

I have tried both but the button doesn't get clicked.
r.click('ctl00_ContentPlaceHolder_ctl00_submitproduct')
 as well as 
r.click('//*[@id="ctl00_ContentPlaceHolder_ctl00_submitproduct"]')

Is there a alternative way to get this button clicked?

Regards,
Sanjay

**Comment by ck81** [comment]
I tried `r.click('//input[@id="ctl00_ContentPlaceHolder_ctl00_submitproduct"]')`

It's working.

You might want to reboot your machine and retry it.  

> Is there a alternative way to get this button clicked?

Yes, in case you need another way to click, you can try using the DOM method.  I know Ken didn't document clearly, his TagUI actually allows you to send javascript commands directly to the web page!  To me, this is another feature that really differentiates TagUI/TagUI-Python from many other RPA tools.

You can try the following command.  It will click the button too:
```
t.dom('return document.querySelector("#ctl00_ContentPlaceHolder_ctl00_submitproduct").click()')
```

Note that you are now sending javascript command, so you need to use the javascript selector and not XPath.

**Comment by SNavgale** [comment]
Thanks ck81, it worked with r.dom().

**Comment by kensoh** [comment]
Thanks @ck81! Adding on, it is possible to do XPath selection with dom(), but the code to do that is quite complex -

```py
r.dom('document.evaluate(\'//*[@name="q"]\', document, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0).click()')
```
\
Above is an example if clicking on the search bar on google.com, the XPath is `//*[@name="q"]`. Note that the single quote around the XPath has a \ escape character because the whole string inside the dom() is enclosed in single quote. Without the escape character, to Python it means end of the string input for dom(), which is not what we want.
