### ISSUE TITLE
Feature: Check if TagUI installed already

### ISSUE THREAD

**Issue by iainn** [tebelorg/RPA-Python#172]
I'm working on a project where I want to pre-build the Docker image as much as possible to reduce the execution time of the flow as much as possible. Could you check if the .tagui directory exists before, so that I can pre-download it and also have SikuliX prepared as well.

**Comment by iainn** [comment]
Closing as I've managed to get this working.

**Comment by kensoh** [comment]
Yes Iain, by default the package will only download TagUI if it has not been downloaded before.

If it has, then it will check if the package is having the latest delta files for the current version.

And if both conditions are satisfied then there will be no downloading of any other files.
