### ISSUE TITLE
Typing Issue

### ISSUE THREAD

**Issue by Leeladhar13** [tebelorg/RPA-Python#184]
Hi Ken,
I just started to explore RPA for Python and started with one basic example using pandas but when i tried to iterate over dataframe and type the values through variable then it is not typing the value from variable instead it is typing Variable name.
The following is the code snippet:

import rpa as r
import pandas as pd

FilePath = r"C:\Users\Leeladhar\Desktop\Testing_DE.xlsx"
Input_DF = pd.read_excel(FilePath)
r.init()
r.url('https://www.google.com/')

for index,row in Input_DF.iterrows():
	#print(row['Subscriber ID'])
	sub_Id = str(row['Subscriber ID'])
	
	r.type('//*[@name="q"]','+sub_Id+')

r.close()

Can you please tell why it is happening like this?

![Output](https://user-images.githubusercontent.com/73610755/97552466-4e3bea80-19fa-11eb-9da1-7ace0e05140b.PNG)

**Comment by Leeladhar13** [comment]
Issue got resolved. I have Casted Value to String and Written the method as below
r.type('//*[@name="q"]', sub_Id)

It Worked fine.

**Comment by kensoh** [comment]
Hi @Leeladhar13 sorry for my super late reply, happy to see that you are using this Python package!

Yes, for Python, if you are using variable, no need to put quotation marks like '+sub_Id+' just put sub_Id.
