### ISSUE TITLE
[ANACONDA][JUPYTER] Error with TagUI/RPA example with fresh installation

### ISSUE THREAD

**Issue by jlreycas** [tebelorg/RPA-Python#196]
hi, I also get this

[RPA][ERROR] - following happens when starting TagUI...

[RPA][ERROR] - use init() before using url()
[RPA][ERROR] - use init() before using type()
[RPA][ERROR] - use init() before using read()

[RPA][ERROR] - use init() before using snap()
[RPA][ERROR] - use init() before using close()

when trying:

import tagui as r

r.init()
r.url('https://www.google.com')
r.type('//*[@name="q"]', 'decentralization[enter]')
print(r.read('result-stats'))
r.snap('page', 'results.png')
r.close()

from https://github.com/tebelorg/RPA-Python

I downloaded the latest Anaconda package today (Anaconda3-2020.11-Windows-x86_64.exe) and did pip rpa install under the console in Spyder => so I've got the package correctly installed. Otherwise I haven't got another versio of Python running on my computer, just that from Anaconda. 

The example that you listed in similar error reports (https://tagui.readthedocs.io/en/latest/setup.html) works for me.
What is happening? 
Thanks

**Comment by jlreycas** [comment]
Solved it myself : 

in tagui.cmd replace this path "%LOCALAPPDATA%\Google\Chrome\Application\chrome.exe"

with the actual Chrome path, in my case: C:\Program Files\Google\Chrome\Application\chrome.exe

**Comment by kensoh** [comment]
Thanks @jlreycas for sharing back your solution! This issue has to be fixed automatically.

The cause is for some newer version of Chrome, the default installation path has changed.

This is tracked in issue https://github.com/tebelorg/RPA-Python/issues/224 with workaround until the future release is published with this fix.
