### ISSUE TITLE
How to deal with randomized-like HTML attribute value? - try relative XPath to anchor

### ISSUE THREAD

**Issue by abitamaspp** [tebelorg/RPA-Python#200]
Hi @kensoh,

I'm sorry for raising another issue, and also for the confusing title.
So I want to type something to this element, but its id attribute value is always changing. Here is element when inspected:

![image](https://user-images.githubusercontent.com/56988153/104745346-93adbf80-5780-11eb-9bbb-b00ab56df4a5.png)

The highlighted alphanumeric part is the one that is always changing everytime the page loaded/visited.

Is there any workaround other than using `click(x,y)`? Any suggestion is welcomed 😃

**Comment by Leeladhar13** [comment]
Hi
Have you tried with full XPath too?

**Comment by abitamaspp** [comment]
Hi @Leeladhar13, thank you for your suggestion 😄 
I'll let you know soon

**Comment by abitamaspp** [comment]
Thank you very much @Leeladhar13, it works! 😄 You have saved me, and I mean it. Thank you again!
I'll keep this issue opened in case you have other thing(s) to tell

**Comment by Leeladhar13** [comment]
Also you can try with
//input[contains(@id, "AccountType")]  in your case which will checks partial match for id with that name

**Comment by abitamaspp** [comment]
Hi @Leeladhar13, thanks for suggesting another way. I'll try it and let you now

**Comment by kensoh** [comment]
Thanks @Leeladhar13 for your sharing!

Hi @abitamaspp, it depends on the situation. RPA for Python does selection also if the attribute contains what you are searching for. Normally for dealing with randomised web elements, I'll find an anchor element that is fixed, then reference from that using relative XPath.

For eg `//*[@id="result"]//input` means the first input element under the element with id result.

Or `//*[@id="result"]/input` to mean the input element must be directly a child.

XPath supports very advance combinations to do very complex scenarios

**Comment by abitamaspp** [comment]
Hi @kensoh, sorry again for this late reply and thank you for your suggestions. My project had finished and delivered using full XPath. Nevertheless, I think using anchoring or partial match (as suggested by @Leeladhar13) will be far more code-maintainable, so I'll definitely try them in the future project
