### ISSUE TITLE
Brew won't allow me to install openssl 1.0.0 as version 1.1.1 is more recent

### ISSUE THREAD

**Issue by mickey06** [tebelorg/RPA-Python#204]
Using trouble shooting section found here : 
https://yuchenkuang.com/TagUI-Python-Setup/setup-tagui-python-on-mac.php#troubleshooting

I tried installing openssl via home-brew.

But it seems that I have a more recent version than 1.0.0

Error message is
> Error: openssl 1.1.1i is already installed
> To upgrade to 1.0.2t, run `brew upgrade openssl`

When I try to brew upgrade openssl, I get a warning and no upgrade
> Updating Homebrew...
> Warning: openssl 1.1.1i already installed

I tried switching versions but it seems that the latest version of brew doesn't allow that any more (Homebrew 2.7.5)

I forgot to say that I tried this before doing anything :
brew uninstall openssl
brew uninstall openssl
brew install https://github.com/tebelorg/Tump/releases/download/v1.0.0/openssl.rb

`ke@MacBook-Air ~ % brew uninstall openssl; brew uninstall openssl; brew install https://github.com/tebelorg/Tump/releases/download/v1.0.0/openssl.rb
Error: Refusing to uninstall /usr/local/Cellar/openssl@1.1/1.1.1i
because it is required by cairo, docutils, ffmpeg, fftw, glib, gnutls, gobject-introspection, harfbuzz, irssi, libass, libevent, nghttp2, open-mpi, pyenv, python@3.9, rtmpdump, srt, tcl-tk, unbound, vapoursynth, wget and youtube-dl, which are currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies openssl
Error: Refusing to uninstall /usr/local/Cellar/openssl@1.1/1.1.1i
because it is required by cairo, docutils, ffmpeg, fftw, glib, gnutls, gobject-introspection, harfbuzz, irssi, libass, libevent, nghttp2, open-mpi, pyenv, python@3.9, rtmpdump, srt, tcl-tk, unbound, vapoursynth, wget and youtube-dl, which are currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies openssl
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/core, homebrew/cask and caskroom/cask).
==> Updated Formulae
Updated 15 formulae.
==> New Casks
duckstation                                duckstation
==> Updated Casks
Updated 30 casks.

Traceback (most recent call last):
`brew extract` or `brew create` and `brew tap-new` to create a formula file in a tap on GitHub instead.: Invalid usage: Non-checksummed download of openssl formula file from an arbitrary URL is unsupported!  (UsageError)
`brew extract` or `brew create` and `brew tap-new` to create a formula file in a tap on GitHub instead.: Invalid usage: Non-checksummed download of openssl formula file from an arbitrary URL is unsupported!  (UsageError)`

**Comment by kensoh** [comment]
Hi @mickey06 this is an issue with newer Brew and macOS versions.

The solution is updated in below link. I'll fix this in new release.

https://github.com/tebelorg/RPA-Python/issues/222

Closing this issue and leaving issue above open.
