### ISSUE TITLE
Does anyone in China have problems downloading when init() first run? - for inputs

### ISSUE THREAD

**Issue by afishpro** [tebelorg/RPA-Python#206]
Hello, because of my location, the speed of accessing GitHub is very slow. After I install RPA, it will automatically download tagui_ window.zip It always times out here. I will download it in this directory and download it again. Is there a solution
![image](https://user-images.githubusercontent.com/11978864/107021858-9e87cd00-67df-11eb-8911-eb3da8e95aaf.png)

**Comment by fi-do** [comment]
Hey afishpro,

I can not find an error in your log. Hope I get it right, you assume that your internet connection is too slow? If you do not want to execute the download function from tagui.py, you can still install it manually. But I personally would avoid these manual steps.
In your case:

- download https://github.com/tebelorg/Tump/releases/download/v1.0.0/TagUI_Windows.zip
- extract archive at C:\Users\Administrator\AppData\Roaming
- install vcredist_x86 and php


Hope I was able to help you.

**Comment by afishpro** [comment]
Thank you very much for your answer. I'll try again.

**Comment by afishpro** [comment]
> 嘿afishpro，
> 
> 我在您的日志中找不到错误。希望我做对了，您认为您的互联网连接速度太慢？如果您不想从tagui.py执行下载功能，仍然可以手动安装。但是我个人会避免执行这些手动步骤。
> 在您的情况下：
> 
> * 下载https://github.com/tebelorg/Tump/releases/download/v1.0.0/TagUI_Windows.zip
> * 在C：\ Users \ Administrator \ AppData \ Roaming中提取存档
> * 安装vcredist_x86和php
> 
> 如果您在另一台计算机上有更好的连接，则也可以通过r.pack（）将其下载到那里，然后将该update.py复制到互联网连接不良的计算机上，然后通过python update.py执行它。
> 
> 希望我能为您提供帮助。

Thank you very much for your answer. This is because the country you are in is blocked from downloading the package. I'll try again here.

**Comment by kensoh** [comment]
Thanks @fi-do and @afishpro ! I've renamed the issue title so other users in China can take a look and share their solutions how they download and use the package in China. There should be other users with same problem. Maybe use proxy?

**Comment by afishpro** [comment]
> Thanks @fi-do and @afishpro ! I've renamed the issue title so other users in China can take a look and share their solutions how they download and use the package in China. There should be other users with same problem. Maybe use proxy?

yes, using a proxy can solve this problem, I don’t know if it can be directly packaged in the pip download, there is no way in China, there is gfw

**Comment by kensoh** [comment]
Hi @afishpro proxy can be set in environment variables or directly in Python. Can you see if the following work for you?

https://stackoverflow.com/questions/11726881/how-to-set-an-http-proxy-in-python-2-7
https://stackoverflow.com/questions/31639742/how-to-pass-all-pythons-traffics-through-a-http-proxy

This is a personal project, but for the upstream TagUI project, there is a weekly Zoom call at Thursday 4pm (UTC+8), which you can join to troubleshoot this together, since this seems probable to be an issue with TagUI if user is unable to download files from GitHub. Here's the Zoom meeting invitation URL - kelaberetiv/TagUI#914

**Comment by kensoh** [comment]
Adding on, the download() function uses the urllib / urllib.request modules which will use the environment proxy setting.

**Comment by kensoh** [comment]
There's also a Telegram group chat for TagUI and RPA for Python users, if you use Telegram - https://t.me/rpa_chat
