### ISSUE TITLE
Google Chrome window minimizing issue in Jupyter Notebook - replicate manual steps

### ISSUE THREAD

**Issue by emshihab008** [tebelorg/RPA-Python#208]
Hello,
I need a suggestion. In line number 3, I use r.keyboard('[win][up]') to maximize the google crome window. But when I try to run this below code in Jupyter notebook, r.keyboard('[win][up]') is not working because crome is opening as minimizing window. How can I resolve this issue?

r.init(visual_automation = True)
r.url('https://www.google.com')
r.keyboard('[win][up]')
r.wait(3)
r.type('//*[@id="tsf"]/div[2]/div[1]/div[1]/div/div[2]/input','github')
r.close

**Comment by kensoh** [comment]
Hi Ekram, are you still facing this issue? My Chrome browser launches ok in normal size. One way to handle this is, after you do init() from Jupyter Notebook, how will you manually open that Chrome window and maximise it?

Once you know how you do it manually, you can just repeat the same steps using click() or keyboard() functions. Let me know if you run into issues doing that!
