### ISSUE TITLE
How to minimize Chrome window - same as your manual process, click() or keyboard()

### ISSUE THREAD

**Issue by lfernandes** [tebelorg/RPA-Python#209]
Hello,

I would like to know to get access to selenium webdriver to minimize the Browser window.

Actually, I found [here](https://www.edureka.co/community/53664/maximize-minimize-browser-window-selenium-webdriver-python) a way to do minimize as following:

```
driver = webdriver.Chrome()
driver. minimize_window()
```

But i didn't find this driver on RPA Python library.

Thanks.

**Comment by fi-do** [comment]
Hey @lfernandes ,
it looks like to me that TagUI handles the browser not RPA for Python.
A suggestion as workaround could be to use win32gui or wnck to minimize your browser.

Hope I was able to help you,
fi-do

**Comment by kensoh** [comment]
Hi @lfernandes RPA for Python users TagUI which has its own websocket connection to control Chrome through DevTools Protocol. Thus Selenium functions are not available as Selenium is not used here when automating Chrome.

To do this easily in RPA for Python, there are 2 ways.

One way is you visually click, eg `click('minimise.png')`, on the browser window to minimize it. Another way is you can use keyboard shortcuts with `keyboard()` to open up the browser menu and choose minimize.
