### ISSUE TITLE
How do I set the downloads folder for file downloads? - use this solution, inviting inputs

### ISSUE THREAD

**Issue by Hitha8** [tebelorg/RPA-Python#210]
Hi!!

Whenever I try to download something from any website, it is directly getting downloaded to a predefined path. Is there any way I can define my own download path?

Thank you so much in advance!

**Comment by fi-do** [comment]
Hey @Hitha8,
when using the download function you can also add an absolute path to your filename.
For example downloading a picture from a website and save it to my directory web at tmp.
```
r.init()
r.download("https://your-url.de/pic.jpg", "/tmp/web/pic.jpg")
```
I think using windows should working similar.

Hope it will help you,
fi-do

**Comment by Hitha8** [comment]
Hello @fi-do 

Thank you so much for your reply.
I am generating a file from a web application, I do not have an URL for it. Is there any way I can give a default folder path where it can dump all the files generated from the application?
Currently those reports are getting downloaded to path where I have my code.

**Comment by fi-do** [comment]
Ahh okay, understood.
I think this relates directly to TagUI. Kensoh already [mentioned](https://github.com/kelaberetiv/TagUI/issues/567#issuecomment-531472830) a hack for this kind of problem.
Another workaround would be to check your code directory for changes and move new files to your target directory.

All the best,
fi-do

**Comment by kensoh** [comment]
Hi @Hitha8 what @fi-do said is correct. Above link is doing directly in TagUI. To do this in Python, it will be -

```py
r.send("chrome_step('Page.setDownloadBehavior',{behavior: 'allow', downloadPath: '/some_path/some_path'});")
```
The send() function will send a TagUI instruction to the TagUI process to run, including any JavaScript functions to be run within TagUI's engine. Note that this is different from dom() which sends JS code to the web browser to run on webpage.

**Comment by kensoh** [comment]
Adding on, if this is a common problem for users, then we should figure out a way to let user set the directory more easily.
