### ISSUE TITLE
Help regarding visual automation

### ISSUE THREAD

**Issue by emshihab008** [tebelorg/RPA-Python#211]
Hi,
Can anyone help me how this code works?

r.init(visual_automation = True)
r.dclick('outlook_icon.png')
r.click('new_mail.png')
r.type('message_box.png', 'message')
r.click('send_button.png')
r.close()

**Comment by fi-do** [comment]
Hello @emshihab008,
according to the api reference:
```

r.init(visual_automation = True) # start tagui
r.dclick('outlook_icon.png') # double click on outlock icon
r.click('new_mail.png') # click on new mail icon
r.type('message_box.png', 'message') # write message in your message box
r.click('send_button.png') # click on send button icon
r.close() # closing tagui
```

When using a local outlook client, maybe initialize tagui with "chrome_browser = False".

Hope it helps,
fi-do

**Comment by emshihab008** [comment]
Hi @fi-do,
Thank you for your information. I have understood the coding part. I have problem with png file ('outlook_icon.png', 'new_mail.png' , 'message_box.png','send_button.png').  When i run this code, this code shows the following output.

C:\Python\Python39\python.exe C:/PzcharmProjects/qwerty.py
[RPA][ERROR] - cannot find outlook_icon.png
[RPA][ERROR] - cannot find new_mail.png
[RPA][ERROR] - cannot find message_box.png
[RPA][ERROR] - cannot find send_button.png

I cannot find out how it works? Before running the code, should I have to take a snapshot of above png files? 

![visual automation problem](https://user-images.githubusercontent.com/76218957/108641005-2981ec00-749d-11eb-81fc-303b4f68408d.PNG)

Regards,
Ekram

**Comment by emshihab008** [comment]
It worked. Thank you very much
