### ISSUE TITLE
ERROR - use .tag extension for flow filename - likely accidentally overwrite with TagUI

### ISSUE THREAD

**Issue by magestik247** [tebelorg/RPA-Python#212]
Hi everyone
Everything was working correctly yesterday, today this error appeared: ERROR - use .tag extension for flow filename.

I can't run .py files
this happens on windows and linux but the error does not appear on the jupyter netebook projects
how do i solve this?

**Comment by kensoh** [comment]
Hi @magestik247 the error message on .tag extension is TagUI v6.14 but the TagUI version that RPA for Python is using is a forked version which is a v5.X. I believe what likely has happened is you have downloaded the latest TagUI and accidentally overwrite the copy downloaded by this package. You can try deleting the folder or renaming the folder to force download.
