### ISSUE TITLE
Going back in webpage through tagui

### ISSUE THREAD

**Issue by rajuyadav44** [tebelorg/RPA-Python#213]
I am automating on a website and after traversing through its hyperlink. I want to go back to previous webpage that is not achievable currently through tagui.

**Comment by magestik247** [comment]
Try this:  r.click('backButtonScreenShot.png'). Let me know if worked

**Comment by rajuyadav44** [comment]
No it did not worked. I was talking about browser back button.
I thought of using r.rclick() but i am not sure how can i continue.

**Comment by magestik247** [comment]
> No it did not worked. I was talking about browser back button.
> I thought of using r.rclick() but i am not sure how can i continue.

Look, to go back you do this, take a screenShot of your browsers back button and then use on click ation, like this: click screenShot_of_your_browsers_back_button.png. I did it right now and it worked.
![googleVoltar](https://user-images.githubusercontent.com/8810036/108720367-a1412c80-7518-11eb-8d5b-5076a160e015.png)

**Comment by kensoh** [comment]
Hi Guys! Alternatively, besides using computer vision, you can try if this works for you -

```py
r.dom('window.history.back()')
```

**Comment by kensoh** [comment]
Closing issue for now but please ping here if anything! Above are 2 methods, one way is using computer vision to click back on the browser, as shared by @magestik247, and the other way is your can use dom() to send the JavaScript code to the web browser to go back.

In addition, for your use case, you can also consider forming an array of URLs first, then processes those URLs by visiting them 1 by 1 later using url() function. This way there is no need to go back to previous page.
