### ISSUE TITLE
Search image in specific display area - call vision() to send custom SikuliX commands

### ISSUE THREAD

**Issue by MikeZnnam** [tebelorg/RPA-Python#214]
Hi,

I wanted to use via visual automation the image recognition.
Is it possible to reduce the area in which the system should search for the image?

Best, 
Mike

**Comment by MikeZnnam** [comment]
Intention of the question is, that my software somehow doesn‘t find the image. Or does homepages have the possibility to make parts „invisible“ for RPA image recognition?

**Comment by gabrielrf2601** [comment]
Hello @MikeZnnam. I have the same doubt. I need something like Region from Sikulix but I yet don't find this feacture in RPA. :(

**Comment by kensoh** [comment]
Hi Mike and Gabriel, by default the tool will search the default display (the one with the taskbar). Another common error could be the image snapshot taken is very different in resolution from the actual display (for eg mac Retina HD display).

Can you let me me know if you are still experiencing this problem and more details of how to replicate your issue?

For searching specific area, it is possible by calling `r.vision()` directly to send SikuliX commands directly to SikuliX. The list of functions in SikuliX can be found here - https://sikulix-2014.readthedocs.io/en/latest/genindex.html

**Comment by gabrielrf2601** [comment]
@kensoh but how can i capture the command "r.vision" return? I already have tried to use just "return", but i haven't a success.

**Comment by kensoh** [comment]
Hi Gabriel, the return value for r.vision() has no meaning for your use case. It returns True is instruction is sent successfully TagUI and False if not. But it does not mean anything related to the outcome of the custom SikuliX code. Best is write output and then read that output. [The file path](https://github.com/tebelorg/RPA-Python/issues/61#issuecomment-532963541) depends on whether you are using on MacOS/Linux or Windows.

```py
r.vision('do something')
r.vision('output_sikuli_text("some result")')
r.load('path_to_tagui/tagui.sikuli/tagui_sikuli.txt')
```

**Comment by kensoh** [comment]
For example below on my Mac laptop, shows writing some desired output from SikuliX process and reading it.

```
>>> import rpa as r
>>> r.init(True)
r.vision('output_sikuli_text("some result")')True
>>> r.vision('output_sikuli_text("some result")')
True
>>> r.load('/Users/username/.tagui/src/tagui.sikuli/tagui_sikuli.txt')
'some result'
```
