### ISSUE TITLE
Help regarding Email Automation

### ISSUE THREAD

**Issue by emshihab008** [tebelorg/RPA-Python#218]
Hello!
I am currently working on an email automation. I have a query.
1. 
I need to download a specific attachment from the email. (For example: Price quotation. If "Price Quote" is present in the subject line or in the body, And the attachment is available in the email, then I need to download the attachment. How can I do this with RPA Python?

2. 
I want to use the r.ask function to specify the start date and the end date. For the specified region, I will look for the required attachment in the Outlook email. Is this automation possible with RPA Python?

Regards,
Ekram

**Comment by fi-do** [comment]
Hola @emshihab008,
to follow up your friendly hint. I think both questions are also more about programming itself, rather than a library issue. Are you using a webclient?
If so you can work with xpath. Iterate over all emails and check if your conditions are true. If so, download the attachment or continue until you reach the end of your mails in your datetime range.

Hope it will help you,
fi-do

**Comment by emshihab008** [comment]
Thank you for your suggestion. But I am using a desktop client. I have automated the email search using visual automation, keyboard and mouse automation. But I have a small problem. I have to search for specific email from the unread mail. So for that I have to count all the unread mail. There is a library name win32com.client in Python. But it is not working. Is there any other way, I can count the unread email in outlook desktop client?

import rpa as r
import win32com.client as client

r.init(True,False)
r.dclick("outlookemail.png")
r.wait(3)
r.click("unreadmail.png")
r.click(265,200)
r.wait(3)
#range should be count of the unread mail 
for i in range(3):
    r.click(573,137)
    r.keyboard('[ctrl]a')
    r.keyboard('[ctrl]c')
    t=r.clipboard()
    if 'price' in t and 'quote' in t:
        print(t)
    r.wait(1)
    r.click(265,(200+70*(i+1)))
r.close()

![win32com problem](https://user-images.githubusercontent.com/76218957/110923113-d32bfe80-8320-11eb-82fa-14948d57aa99.PNG)

**Comment by fi-do** [comment]
Hola @emshihab008,
I think I understood your problem. I actually don't know how outlook works or looks particularly. And searching screenshots was not very helpful to me to make the correct assumptions for the surface configuration.

But to solve your date problem I would ask the user for input, like you suggested.
For example:
```
from dateutil import parser 
begin_date_range = parser.parse(r.ask(text_to_prompt = "Start Date")) 
end_date_range = parser.parse(r.ask(text_to_prompt = "End Date"))
```

Maybe you can find a field in Outlook with the number of new emails. So you can utilize this for your loop.
Furthermore, when looping through your mails you can check if the date of the mail is in your range, if not skip.
```
if  begin_date_range <= mail_date <= end_date_range:
    process_mail
else:
    continue
 ```

Hope it will help you,
fi-do

**Comment by emshihab008** [comment]
Hi @fi-do ,
Thank you. I will try this one and let you know the further update.

Regards,
Ekram
