### ISSUE TITLE
showing TypeError: mouse_x() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by emshihab008** [tebelorg/RPA-Python#219]
Hello everyone,
How can I resolve the following issue? Is it possible to automate with r.mouse_x, r.mouse_y function?
Task: I have to open pdf file. Then I have to copy specific data. For this reason, I used r. mouse function.

import rpa as r
r.init(visual_automation= True, chrome_browser= False)
r.dclick("testinginvoice.png")
r.wait(3)
#r.keyboard('[ctrl]a')
print(r.read(r.mouse_x(56),r.mouse_y(505),r.mouse_x(289),r.mouse_y(540)))
r.close()

Output:
C:\Python\Python39\python.exe C:/PzcharmProjects/Practice.py
Traceback (most recent call last):
  File "C:\PzcharmProjects\Practice.py", line 6, in <module>
    print(r.read(r.mouse_x(56),r.mouse_y(505),r.mouse_x(289),r.mouse_y(540)))
TypeError: mouse_x() takes 0 positional arguments but 1 was given

Process finished with exit code 1

**Comment by fi-do** [comment]
Hey @emshihab008,

it looks like to me that the functions r.mouse_x and y don't make use any argument.
When you are already have the coordinates, why not use them?
`r.read(56, 505, 289, 540)`

Hope it will help you,
fi-do

**Comment by emshihab008** [comment]
Hi fi-do,
The solution you provided, worked. Thank you very much.
Can you help me giving solution of my another raising issue? 
[https://github.com/tebelorg/RPA-Python/issues/218]
#218 

Regards,
Ekram
