### ISSUE TITLE
Is is possible to use IE8 or other web browser - Edge native possible, Firefox v59 ok

### ISSUE THREAD

**Issue by HelloZhou3301** [tebelorg/RPA-Python#220]
As the title shows, does angone hava a solution? When i use command promt to turn ie8, i can not use url or xpath in the broswer

**Comment by fi-do** [comment]
Hey @HelloZhou3301,

to me it looks like that ie8 is not supported. Your wanted functionalities only works with chrome or as an alternative change the chrome symlink to a chromium binary.

Hope it will help you,
fi-do

**Comment by MikeZnnam** [comment]
> Hey @HelloZhou3301,
> 
> to me it looks like that ie8 is not supported. Your wanted functionalities only works with chrome or as an alternative change the chrome symlink to a chromium binary.
> 
> Hope it will help you,
> fi-do

Hi @fi-do,

did you made python rpa running with chromium? I always receive the error that phantomjs error was not found. Chromium opens during init(), but I can not proceed any actions via RPA.
Any hints how to solve phantomjs error?

best,
Mike

**Comment by fi-do** [comment]
Hola @MikeZnnam,

yes I can execute rpa with chromium. I mean it is not officially supported, so maybe you get some surprises but so far it worked for me.
Does your phantomjs error also occur with chrome? How does your error message exactly look like?

All the best,
fi-do

**Comment by MikeZnnam** [comment]
Hi Fi-Do,

are you also running it on a raspberry? Maybe PhantomJS is not compatible to raspberry?

Best,
Mike

Am 17.03.2021 um 12:51 schrieb Dominik ***@***.***>:

﻿

Hola @MikeZnnam<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMikeZnnam&data=04%7C01%7Cmike.mannz%40eufh-mail.de%7Ca6429c8bdd314e6b0b0a08d8e93afe67%7C1ef963868d9c4d1e9eaae395786e1480%7C0%7C0%7C637515786879611504%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2L5F5Oh5lgkKmfkysI9xwz88KmFYU6lPWcP1VnvNAJA%3D&reserved=0>,

yes I can execute rpa with chromium. I mean it is not officially supported, so maybe you get some surprises but so far it worked for me.
Does your phantomjs error also occur with chrome? How does your error message exactly look like?

All the best,
fi-do

**Comment by fi-do** [comment]
Hm, 
think this framework will target x86 architecture. Maybe you can tinker out an workaround for ARM, for example with https://github.com/piksel/phantomjs-raspberrypi. Did you also check the other dependencies?

**Comment by kensoh** [comment]
Thanks @fi-do @MikeZnnam for all your exchanges!

Hi @HelloZhou3301, this package cannot control IE from backend. It can however, control Microsoft Edge from backend. Need to make a couple of lines modification to invoke Edge and kill Edge process instead of Chrome. [More info here](https://github.com/kelaberetiv/TagUI/issues/946).

However, if you are ok to run the new Microsoft Edge, it is also based on Chromium, then probably no point because it is similar to Chrome already might as well use Chrome directly.

Adding on, for IE, you can use visual automation and computer vision, OCR, keyboard shortcuts to control it like a desktop app.

**Comment by kensoh** [comment]
Firefox v59 can also be automated natively through backdoor. But that's many versions ago already.

**Comment by kensoh** [comment]
Closing issue for now but please feel free to add on to discuss or reopen!

For running on Raspberry Pi, back at AI Singapore's TagUI project,
there's an internal todo to explore testing and running on that platform.
