### ISSUE TITLE
Linux RPA Installation Problems - user resolved, issue due to resolution

### ISSUE THREAD

**Issue by MikeZnnam** [tebelorg/RPA-Python#221]
Hi,
I wanted to setup a RPA environment on my linux.  
I installed Java, Tesseract and Co, as well as Chrome. But I don't get it running. Do you have any idea? How can I check if I installed java and co right? Is there any path varible which I have to configure, like in windows? 

Thanky a lot! 
Mike

Python Version: 
![grafik](https://user-images.githubusercontent.com/50210738/110477251-3c263300-80e3-11eb-987b-9a197477e6d8.png)

Installed Java: 
![grafik](https://user-images.githubusercontent.com/50210738/110476091-e604c000-80e1-11eb-9229-73bf3a50f33e.png)

Installed Tesseract: 
![grafik](https://user-images.githubusercontent.com/50210738/110476069-e00edf00-80e1-11eb-8486-390c1f6462a7.png)

Install RPA:
![grafik](https://user-images.githubusercontent.com/50210738/110476128-eef59180-80e1-11eb-9185-d3d07a88a38d.png)

RPA Error: 
![grafik](https://user-images.githubusercontent.com/50210738/110476217-06347f00-80e2-11eb-935f-25a2e6b74809.png)

**Comment by fi-do** [comment]
Hey @MikeZnnam,

which php version are you using?
`php --version`
Does the rpa error also occur with python3?

**Comment by MikeZnnam** [comment]
Hey,

I made it running PHP 7.2.24 is installiert. But my scripts don‘t read the web elements ids :( any idea?

Best,
Mike
Am 09.03.2021 um 19:02 schrieb Dominik <notifications@github.com>:

﻿

Hey @MikeZnnam<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMikeZnnam&data=04%7C01%7Cmike.mannz%40eufh-mail.de%7C9a7b2f514fda435595df08d8e3257463%7C1ef963868d9c4d1e9eaae395786e1480%7C0%7C0%7C637509097295874766%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sqBwkNN%2BbFqAPP49zLyR%2FWIgW5zScYwvhCYDTFFrRSc%3D&reserved=0>,

which php version are you using?
php --version
Does the rpa error also occur with python3?

**Comment by MikeZnnam** [comment]
Correction it realizes the ids, and also responses true, but clicks are not proceeded...

Am 09.03.2021 um 19:02 schrieb Dominik <notifications@github.com>:

﻿

Hey @MikeZnnam<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMikeZnnam&data=04%7C01%7Cmike.mannz%40eufh-mail.de%7C9a7b2f514fda435595df08d8e3257463%7C1ef963868d9c4d1e9eaae395786e1480%7C0%7C0%7C637509097295874766%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sqBwkNN%2BbFqAPP49zLyR%2FWIgW5zScYwvhCYDTFFrRSc%3D&reserved=0>,

which php version are you using?
php --version
Does the rpa error also occur with python3?

**Comment by MikeZnnam** [comment]
Problem solved, it was an resolution issue.

Am 09.03.2021 um 21:32 schrieb Mannz, Mike <mike.mannz@eufh-mail.de>:

﻿
Hey,

I made it running PHP 7.2.24 is installiert. But my scripts don‘t read the web elements ids :( any idea?

Best,
Mike
Am 09.03.2021 um 19:02 schrieb Dominik <notifications@github.com>:

﻿

Hey @MikeZnnam<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMikeZnnam&data=04%7C01%7Cmike.mannz%40eufh-mail.de%7C9a7b2f514fda435595df08d8e3257463%7C1ef963868d9c4d1e9eaae395786e1480%7C0%7C0%7C637509097295874766%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sqBwkNN%2BbFqAPP49zLyR%2FWIgW5zScYwvhCYDTFFrRSc%3D&reserved=0>,

which php version are you using?
php --version
Does the rpa error also occur with python3?
