### ISSUE TITLE
SyntaxError: (unicode error) 'unicodeescape' - use \\ instead of \ in Python strings

### ISSUE THREAD

**Issue by emshihab008** [tebelorg/RPA-Python#227]
Hi,
I am planning to open file through RUN. But when I am trying to write path using r.keyboard, the following error is showing. How can I solve this issue? Is there any other way ?

import rpa as r
r.init(visual_automation= True, chrome_browser= False)
r.keyboard("[win]r")
r.keyboard("C:\Users\shihab\Downloads\Book.pdf")
r.keyboard("[enter]")
r.close()

Output:
File "C:\PzcharmProjects\Invoice_extraction.py", line 4
r.keyboard("C:\Users\shihab\Downloads\Book.pdf")
                                                   ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

**Comment by kensoh** [comment]
Hi Ekram, this is a Python error. I think in Python, to type backslash `\` you need to use double backslash `\\`. Because in Python strings, a backslash `\` has special meaning to mean escape characters like `\n` for new line `\t` for tab and others.

**Comment by emshihab008** [comment]
Thank you Kensoh.
