### ISSUE TITLE
Plans for integration with Robot Framework - anyone interested to do that? :)

### ISSUE THREAD

**Issue by maximveksler** [tebelorg/RPA-Python#229]
Is there a plan for RPA-Python integration with Robot Framework?

The [reporting](https://youtu.be/vTBqHqIB9BY?t=109) capabilities of the [robot framework](https://robotframework.org/) and its ability to tie several aspects of testing / RPA into a [single corpus](https://robotframework.org/#libraries) on one side, vs. the clear API and pythonic approach of RPA-Python on the other side make it a good fit IMHO

Would be happy to know if any efforts are set in motion on this?

**Comment by kensoh** [comment]
Thanks Maxim for raising your thoughts! I appreciate it.

For now there's no plan to integrate with Robot Framework.

RPA for Python tool is only a personal project, with focus on bringing some of the UI automation capabilities of TagUI to the Python user to use with other packages to build cool stuffs.

I think this sounds like a great opportunity, if u r familiar with RF and keen, for you to create and own the library for RF for this package. I can work with you on this.

That'll be a win for RF users, you (for full control of how you envision the library to be) as well as TagUI ecosystem.

Will copy this initial response there to follow-up 😊

**Comment by kensoh** [comment]
Hi @maximveksler,

Nived from the Telegram group chat has just launched his TagUI library for Robocorp, ie Robot Framework -

https://github.com/nived00015/Tagui_Robocorp_Library

It may be something directly usable by you already, though you were looking for the Python version.

**Comment by kensoh** [comment]
CC Nived @nived00015
