### ISSUE TITLE
How to set language when r.init()?

### ISSUE THREAD

**Issue by qwer11121-coder** [tebelorg/RPA-Python#230]
When I execute r.init() and then open a url,  it open chrome in German,  however my system language is English.  Does anyone know how to set language to English? Thank you.

**Comment by fi-do** [comment]
Hey qwer11121-coder,

you can check your chrome profile and set the browser language with the following [guide](https://support.google.com/chrome/answer/173424?co=GENIE.Platform%3DDesktop&hl=en). So for example pause your script when executing and make your settings at the browser.

Hope it will help you,
fi-do
