### ISSUE TITLE
Use case of type() through web backend and then r.keyboard() - pending checks

### ISSUE THREAD

**Issue by haidvams** [tebelorg/RPA-Python#232]
here my video test and log

https://user-images.githubusercontent.com/58457168/113467347-a6c15900-946c-11eb-80f0-d7e7773c8731.mov

**Comment by kensoh** [comment]
Hi @haidvams double check the following - 
1. that the Chrome browser is activated in foreground (if not need to do a click on task bar to bring it to foreground)
2. do type() using an image snapshot of search bar (using type() from website id may not actually focus on search bar)
