### ISSUE TITLE
Can not even launch it :( - pending some checks and more replication details

### ISSUE THREAD

**Issue by svolodarskyi** [tebelorg/RPA-Python#234]
Hello, it might sound silly, however can not even launch it. 
has anybody had same issue?

Trying sample code:
`r.init()
r.url('https://www.google.com')
r.type('//*[@name="q"]', 'decentralization[enter]')
print(r.read('result-stats'))
r.snap('page', 'results.png')
r.close()`

**Comment by kensoh** [comment]
Hi @svolodarskyi just to be sure, did you include the first line to import the package? If yes, can you tell more what is the error message that you get after running above code?

```py
import rpa as r
```

Also, can you run below script to see what is your TagUI installation directory?
```py
import os
import platform
if platform.system() == 'Windows':
    tagui_directory = os.environ['APPDATA'] + '/' + 'tagui'
else:
    tagui_directory = os.path.expanduser('~') + '/' + '.tagui'
print(tagui_directory)
```
