### ISSUE TITLE
SyntaxError: invalid syntax issue - looks like Python programming syntax error

### ISSUE THREAD

**Issue by emshihab008** [tebelorg/RPA-Python#235]
Hi,
When I am trying to run this code, it is showing the below error. How can I solve this issue?

r.init(True,True)
r.url("https://www.ilovepdf.com/pdf_to_excel")
r.click("a[id='pickfiles'] span")
r.keyboard("[ctrl]l")
r.keyboard("[ctrl]a")
r.keyboard("[delete]")
r.keyboard("G:\\RPA testing\\Good Receicing Process")
r.keyboard("[enter]")
f0="plo.png"
f1="pl1.png"
f2="pl2.png"
f3="pl3.png"
for i in range(0,3):
    r.dclick((f["i++"])
    r.wait(2)
    r.click("covertpdftoexcel.png")

Output:
C:\Python\Python39\python.exe C:/PzcharmProjects/Incoming_Goods_Receiving_Process.py
  File "C:\PzcharmProjects\Incoming_Goods_Receiving_Process.py", line 54
    r.wait(2)
    ^
SyntaxError: invalid syntax

Process finished with exit code 1

**Comment by kensoh** [comment]
Hi Ekram, this is a Python programming error, you can't do something like `f["i++"]`.

Also that line `r.dclick((f["i++"])` is missing a right close bracket.

**Comment by emshihab008** [comment]
In the above programming, my plan is to open the document given as png file (f0,f1,f2,f3) using for loop. Can i do that?
for example: r.dclick(f0), r.dclick(f1),r.dclick(f2)...........

And i have removed bracket. Now the output is:

  File "C:\PzcharmProjects\Incoming_Goods_Receiving_Process.py", line 53, in <module>
    r.dclick(f["i++"])
NameError: name 'f' is not defined

**Comment by kensoh** [comment]
Hi Ekram yes you can do that, above is incorrect Python syntax. You can check on Python on the 2 topics -

1. Defining a list of strings
2. Looping through a list

**Comment by emshihab008** [comment]
Yes. I had a plan to use list. But for my case, range will be dynamic by counting file on the folder. Maximum document will be 10. That's why I go for  range function:
for i in range(0, count(file)):

**Comment by emshihab008** [comment]
The problem is solved. 

list=["pl0.png","pl1.png","pl2.png","pl3.png"]
count=0
length= len(list)
for i in list:
        count=count+1
        if count <=fie_count:
            r.dclick(i)
            r.wait(2)
            r.click("covertpdftoexcel.png")
            r.wait(3)
            r.click("back.png")
            r.wait(2)
            r.click("a[id='pickfiles'] span")
