### ISSUE TITLE
[RPA][INFO] - to use RPA for Python on Windows, avoid space in folder path name

### ISSUE THREAD

**Issue by emshihab008** [tebelorg/RPA-Python#238]
Hi,
I have encountered a problem in the below code. When I run the code , it is showing below error output. But when i skip the 2nd portion (# 2. Rename the downloaded folder), the code runs properly. What is the reason for this problem?

# 1. Email automation for downloading the attachments..........................................................................................................
`import win32com.client as client
import datetime

outlook = client.Dispatch('Outlook.Application')
namespace = outlook.GetNameSpace('MAPI')
account=namespace.Folders['rpatesting008@outlook.com']
inbox=account.Folders['Inbox']
start_date = datetime.date(2021,4,4)
end_date = datetime.date(2021,4,14)
count=0
for message in inbox.Items:
    if message.Subject.startswith('Packing List') and message.ReceivedTime.date()<= end_date and message.ReceivedTime.date()>= start_date:
        save_path = 'G:\\RPA testing\\Good Receicing Process\\{}'
        for file in message.attachments:
            count = count + 1
            file.SaveAsFile(save_path.format(file.FileName))
print(count)
file_count =count

# 2. Rename the downloaded folder................................................................................................................................................ 
import os
path=os.chdir("G:\\RPA testing\\Good Receicing Process")

i=0
for file in os.listdir(path):
    new_file_name = "pl{}.pdf".format(i)
    os.rename(file,new_file_name)
    i=i+1

# 3. RPA automation for converting pdf into excel document.............................................................................................
import rpa as r
r.init(True,True)
r.url("https://www.ilovepdf.com/pdf_to_excel")
r.click("a[id='pickfiles'] span")
r.keyboard("[ctrl]l")
r.keyboard("[ctrl]a")
r.keyboard("[delete]")
r.keyboard("G:\\RPA testing\\Good Receicing Process")
#r.keyboard("[ctrl]v")
r.keyboard("[enter]")
list=["p0.png","p1.png","p2.png","p3.png"]
count1=0
for i in list:
        count1=count1+1
        if count1 <= file_count:
            r.dclick(i)
            r.wait(2)
            r.click("//span[@id='processTaskTextBtn']")
            r.wait(1)
            r.click("//a[normalize-space()='Download EXCEL']")
            r.wait(1)
            r.click("//*[name()='path' and contains(@d,'M6.533 15.')]")
            r.wait(1)
            r.click("a[id='pickfiles'] span")
r.close()`

**Output:**
5
[RPA][INFO] - to use RPA for Python on Windows, avoid space in folder path name
[RPA][ERROR] - use init() before using url()
[RPA][ERROR] - use init() before using click()
[RPA][ERROR] - use init() before using keyboard()
[RPA][ERROR] - use init() before using keyboard()
[RPA][ERROR] - use init() before using keyboard()
[RPA][ERROR] - use init() before using keyboard()
[RPA][ERROR] - use init() before using keyboard()
[RPA][ERROR] - use init() before using dclick()
[RPA][ERROR] - use init() before using click()
[RPA][ERROR] - use init() before using click()
[RPA][ERROR] - use init() before using click()
[RPA][ERROR] - use init() before using click()
[RPA][ERROR] - use init() before using dclick()
[RPA][ERROR] - use init() before using click()
[RPA][ERROR] - use init() before using click()
[RPA][ERROR] - use init() before using click()
[RPA][ERROR] - use init() before using click()
[RPA][ERROR] - use init() before using dclick()
[RPA][ERROR] - use init() before using click()
[RPA][ERROR] - use init() before using click()
[RPA][ERROR] - use init() before using click()
[RPA][ERROR] - use init() before using click()
[RPA][ERROR] - use init() before using dclick()
[RPA][ERROR] - use init() before using click()
[RPA][ERROR] - use init() before using click()
[RPA][ERROR] - use init() before using click()
[RPA][ERROR] - use init() before using click()
[RPA][ERROR] - use init() before using close()

**Comment by Lmac99** [comment]
The **main folder from where your** #3 script is being executed has space on its name. 
The way to go is to rename it without spaces.

An example:
Path\some folder <- if you run from here it will not work
Path\someFolder\some Folder <- it will raise the error.

Path\someFolder <- works fine
Path\some folder\someFolder <- when executed from here also works


you can create dummy folders to test this, i recommend.

**Comment by kensoh** [comment]
Thanks @Lmac99! What you said is correct, there is a limitation with one of the components of the upstream TagUI project. 

I know this is embarrassing. There is [an open issue](https://github.com/kelaberetiv/TagUI/issues/987) to explore whether a workaround can be implemented to automatically address this. But until then, @emshihab008 please run your Python script from a folder without space in the full path.

**Comment by kensoh** [comment]
PS - by the way Ekram, nice code doing a series of automation workflows end-to-end!!

**Comment by emshihab008** [comment]
Hi @Lmac99,
Thank you for your suggestion. It worked.

**Comment by emshihab008** [comment]
Thanks @kensoh.

**Comment by tasbolat1** [comment]
Hi @kensoh,
I have this problem even though script's location does not contain space. Is there any reason that this problem arises?

Thanks,
tas

**Comment by kensoh** [comment]
Hi Tas, the exact condition that triggers this is below, it depends primarily on your current working directory where you run the package or your environment. Usually that is the location where the Python script is, but it can be some other folder. Can you try running the script by first changing directory to where it is and then run `python script.py`?

```py
if platform.system() == 'Windows' and ' ' in os.getcwd():
```

**Comment by tasbolat1** [comment]
@kensoh thank you for quick reply,
I know that this issue is about Windows, but I am running rpa in Linux. When I run the following code
```
import os
os.getcwd()
```
I get directory with no space and my filename does not have space in it.

**Comment by kensoh** [comment]
Hi @tasbolat1 can you paste the error message that you have? The only part of the code that gives below message checks that that the OS is Windows from `platform.system()` before checking for space in the current working directory.

```
[RPA][INFO] - to use TagUI on Windows, avoid space in folder path name
```

**Comment by tasbolat1** [comment]
Hi @kensoh,
when I run 
```
import platform
platform.system() 
```
I get the following:
`'Linux'`

When I run 

```
import rpa as r
r.init()
r.url('https://www.google.com')
r.close()
```
I get the following:

```
[RPA][ERROR] - following happens when starting TagUI...


[RPA][ERROR] - use init() before using url()
[RPA][ERROR] - use init() before using close()

False
```

**Comment by kensoh** [comment]
I see.. Your environment issues looks to be different from the space problem.

Can you try running the following from your terminal prompt to see what happens?

```
~/.tagui/src/tagui ~/.tagui/src/samples/1_yahoo chrome
```

What might happen is perhaps if your Linux has no display screen, then running Chrome in visible mode will not work.

**Comment by kensoh** [comment]
Closing for time being until further inputs
