### ISSUE TITLE
Explore whether to have a headless option for advanced tech stacks - added [done]

### ISSUE THREAD

**Issue by kensoh** [tebelorg/RPA-Python#240]
eg building an implementation on Docker for Linux without displays / Xvbf

*source - Allan*

**Comment by kensoh** [comment]
This is added in v1.34, available with `pip install rpa --upgrade`

Headless mode can be enabled with `r.init(headless_mode = True)`.
For headless mode, `chrome_browser` parameter needs to be True (default).

Validated with following -

```py
r.init(headless_mode = True)
r.url('https://www.google.com')
r.type('//*[@name="q"]', 'decentralization[enter]')
print(r.read('result-stats'))
r.snap('page', 'results.png')
```

**Comment by skadefro** [comment]
Thank you.

**Comment by lanSeFangZhou** [comment]
can rpa deploy online like a service?
