### ISSUE TITLE
Google chrome cannot read and write to its data directory - try this and rerun

### ISSUE THREAD

**Issue by gojay222** [tebelorg/RPA-Python#242]
I had a few automations working fine on my work laptop until a company system update. Right now if I run the program, I will get:
"Google chrome cannot read and write to its data directory: chrome\tagui_user_profile"

Any idea how to fix this? It is on my work laptop so I don't have admin access.

Thanks,
Jay

**Comment by kensoh** [comment]
Hi Jay, can you share more what OS are you using? Windows, macOS, Linux?

Sounds like after the system upgrade, access to your user application data folder is blocked.

A solution to try is to remove your Chrome user profile and run the package again to see if that helps.

In Windows it is in %APPDATA% folder it is tagui\src\chrome\tagui_user_profile folder

In macOS/Linux it is in ~/.tagui/src/chrome/tagui_user_profile folder

You can try moving that folder away to somewhere else and rerun.

**Comment by deepesh-coforge** [comment]
Thanks @kensoh  it worked for me (for windows) 
Sharing what i did for others reference tagui\src\tagui.cmd one needs to look for "chrome_switches"
change     --user-data-dir = chrome\tagui_user_profile    to   --user-data-dir = %APPDATA%\tagui\src\chrome\tagui_user_profile
and then re run.
I hope it helps.

**Comment by kensoh** [comment]
Thanks @deepesh-coforge for sharing! Can I check with you if you are running in headless mode or normal visible Chrome?

I've created a new issue to look into this. If you are running using visible Chrome and you have an issue with the Chrome user profile directory which can be resolved using the solution you mentioned above, then this should be added. https://github.com/tebelorg/RPA-Python/issues/244

**Comment by deepesh-coforge** [comment]
@kensoh yes, I was using visible chrome for browser automation and it was resolved using the above solution. My path didn't have spaces in them, so not sure about that. Thanks!

**Comment by kensoh** [comment]
Oic.. Then this needs to be fixed permanently and automatically. Thanks @deepesh-coforge for your feedback!
 
I'll implement that in issue #244.
