### ISSUE TITLE
[RPA][ERROR] - cannot find XPath - use frame() in this case to specify frame

### ISSUE THREAD

**Issue by LinoLuiz** [tebelorg/RPA-Python#243]
I'm trying to enter text in the 'placa' field, but RPA doesn't find XPath. I've tried by ID, Name, among others. The same problem occurs for the other fields and buttons on the page.

```
import pyautogui as p
import rpa as r

r.init()
r.url('https://www.meudetran.ms.gov.br/veiculo.php#')
p.sleep(2)
r.type('//*[@id="id_sc_field_placa"]', 'Teste')
```
[RPA][ERROR] - cannot find //*[@id="id_sc_field_placa"]

**Comment by kensoh** [comment]
Hi @LinoLuiz you can try the following -

```py
import rpa as r

r.init()
r.url('https://www.meudetran.ms.gov.br/veiculo.php#')
r.frame('ifrm-pdr-portal')
r.type('sc_clone_placa', 'Teste')
...
```

The web page uses frames, you can check by searching in Inspector (below image). So there is a need to use frame() to tell the tool that you are looking for elements in that frame and not elsewhere. A web frame is a separate web page / HTML doc.

![Screenshot 2021-05-04 at 3 01 04 AM](https://user-images.githubusercontent.com/10379601/116920512-4a2ca600-ac85-11eb-9718-b079a5777cf8.png)

Also, the input field seems to have duplicates. You can either append [2] at the end to mean the 2nd match, or use what I did by providing the name attribute which directly points to the correct element.

![Screenshot 2021-05-04 at 2 57 21 AM](https://user-images.githubusercontent.com/10379601/116920680-88c26080-ac85-11eb-9a1e-26c52e513ee6.png)

Lastly, there is no need to wait explicitly, the tool will auto-wait up to timeout of 10 seconds before throwing error.

Even if you need to wait, you can use r.wait() and do not need to import another package like pyautogui to do that.

**Comment by LinoLuiz** [comment]
Thank you so much for your help @kensoh! I researched a lot and found no solution.
