### ISSUE TITLE
Some HTML data are not found - looks like images out of view not loaded, try this

### ISSUE THREAD

**Issue by sangasangasanga** [tebelorg/RPA-Python#249]
Hi @kensoh , I was just testing the lazada sample script with a little modification. It shows an error saying the html class is not found after it runs for the first 20 pictures.  I inspected the HTML codes, the HTML code didn't change. I am not sure what is causing the error.

> https://www.google.com/search?q=indonesian+car+license+plate&rlz=1C1CHBF_enSG917SG917&hl=en&sxsrf=ALeKk027L568aIL3WeZQGgHuKmOiv_6Q1A:1620290243419&source=lnms&tbm=isch&sa=X&ved=2ahUKEwig_pDD07TwAhXE8HMBHZMoB2AQ_AUoAXoECAEQAw&biw=1536&bih=750
>all_images = []
total_images = count('//*[@class="isv-r PNCib MSM1fd BUooTd"]/a/div/img')
>for n from 1 to total_images
    if(//*[@class="isv-r PNCib MSM1fd BUooTd"]/a/div/img)[`n`] 
    read (//*[@class="isv-r PNCib MSM1fd BUooTd"]/a/div/img)[`n`]/@src to image_link
    js all_images.push(image_link)
>for n from 1 to total_images
    https://`all_images[n-1].split('//')[1]`
    snap page

**Comment by kensoh** [comment]
Hi @sangasangasanga in your previous issue you are using RPA for Python. In above you are using TagUI in human language. Are you developing using Python version or human language?

Oh in above example if you try to scroll down the page yourself you will find that the images not yet shown on the screen isn't loaded yet. Maybe you can try using keyboard step to do [pagedown] a few times to load more images first. Also, see if you can find a better relative XPath. Above class looks like some randomised identifier and may change in between runs.

If you are using RPA for Python, you can do your testing in Jupyter notebook or Python interactive mode. If you are using TagUI in human language you can add a `live` step in your script as the breakpoint, or run TagUI with `tagui live` to start live mode.

**Comment by sangasangasanga** [comment]
@kensoh Here is a sample of the code.

> import rpa as r
> r.init(visual_automation = True)
> r.url('https://www.google.com/search?q=indonesian+car+license+plate&rlz=1C1CHBF_enSG917SG917&hl=en&sxsrf=ALeKk027L568aIL3WeZQGgHuKmOiv_6Q1A:1620290243419&source=lnms&tbm=isch&sa=X&ved=2ahUKEwig_pDD07TwAhXE8HMBHZMoB2AQ_AUoAXoECAEQAw&biw=1536&bih=750')
> all_images = []
> total_images = r.count('//*[@id="islrg"]')
> print(total_images)
> 
> for n in range (1, total_images+1):
>     print(n)
>     # print(r.read('//*[@id="islrg"]/div[1]/div['+str(n)+']/a[1]/div[1]/img/@src'))
>     image_link = r.read('//*[@id="islrg"]/div[1]/div['+str(n)+']/a[1]/div[1]/img/@src')
>     all_images.append(image_link)
>     # print('divisible?' + str(n) +' : ' + str((n % 3)))
>     if(n % 3 == 0):
>         r.keyboard('[pagedown]')
>     if(r.exist('more_results.png')):
>         r.click('more_results.png')
> 
> for n in (1, total_images):
>     print(n)
>     print(all_images[n-1].split('//')[0])
>     r.url('https://'+all_images[n-1])
>     r.snap('page', str(n)+'.png')
> r.close()

**Comment by sangasangasanga** [comment]
Thanks @kensoh. That works. Appreciate your help :)
