### ISSUE TITLE
Google Chrome cannot read or write to its data directory - pending checks and details

### ISSUE THREAD

**Issue by emshihab008** [tebelorg/RPA-Python#253]
Hello,
I am encountering a problem. when i try to oprn url, it is showing below error.

Regards,
Ekram
![taguierror](https://user-images.githubusercontent.com/76218957/118530881-76e0c300-b745-11eb-9bb3-3c1c20b163e0.PNG)

**Comment by kensoh** [comment]
Hi Ekram, this looks like a folder permissions issue.

1. Did this error always happen or it recently happen after some software/OS/Chrome upgrade?

2. Try downloading the latest version with `pip install rpa --upgrade` and see if that helps.

3. Can you add below to your Practice.py script and show me what's your current directory?

```py
import os; print(os.getcwd())
```

4. Check your TagUI installation folder with the following, there is a tagui folder there. Try deleting and run again?
```py
import os; print(os.environ['APPDATA'])
```

**Comment by emshihab008** [comment]
Thanks Ken. There was a problem with rpa upgrade. Now it is working perfectly.
