### ISSUE TITLE
[RPA][ERROR] - cannot find error during looping - elements are missing in web page

### ISSUE THREAD

**Issue by emshihab008** [tebelorg/RPA-Python#255]
Hi,
I have an enquiry. When I try to run the below code, everytime it is showing error between the loop for some values What could be the reason? 

`
import rpa as r
import openpyxl
from openpyxl.reader.excel import load_workbook
final_excel=openpyxl.load_workbook("G:\\RPA_testing\\final_data.xlsx")
r.init(True, True)
r.url("https://docs.google.com/forms/d/e/1FAIpQLScbqkbocpe5TfTgpYT9FkA8j45qfSHfNfQ9FeBhWEY6nR876A/viewform?vc=0&c=0&w=1&flr=0")
file_count=14
postiong_count = 0
for m in range(1,file_count+1):
    data=final_excel_sheet.cell(m+1,1).value
    print(data)
    r.type("/html[1]/body[1]/div[1]/div[3]/form[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/input[1]","Inbound")
    r.type("/html[1]/body[1]/div[1]/div[3]/form[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/input[1]", data)
    r.type("/html[1]/body[1]/div[1]/div[3]/form[1]/div[2]/div[1]/div[2]/div[3]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/input[1]", "Truck/LKW")
    r.type("//div[4]//div[1]//div[1]//div[2]//div[1]//div[1]//div[1]//div[1]//input[1]", "start_time")
    r.type("//div[5]//div[1]//div[1]//div[2]//div[1]//div[1]//div[1]//div[1]//input[1]", "end_time")
    r.click("//span[@class='appsMaterialWizButtonPaperbuttonLabel quantumWizButtonPaperbuttonLabel exportLabel']")
    r.click("//a[normalize-space()='Submit another response']")
r.close()

`

Output:

aaaaaaaaaa
bbbbbbbbb
ccccccccccc
[RPA][ERROR] - cannot find /html[1]/body[1]/div[1]/div[3]/form[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/input[1]
[RPA][ERROR] - cannot find /html[1]/body[1]/div[1]/div[3]/form[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/input[1]
[RPA][ERROR] - cannot find /html[1]/body[1]/div[1]/div[3]/form[1]/div[2]/div[1]/div[2]/div[3]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/input[1]
[RPA][ERROR] - cannot find //div[4]//div[1]//div[1]//div[2]//div[1]//div[1]//div[1]//div[1]//input[1]
[RPA][ERROR] - cannot find //div[5]//div[1]//div[1]//div[2]//div[1]//div[1]//div[1]//div[1]//input[1]
[RPA][ERROR] - cannot find //span[@class='appsMaterialWizButtonPaperbuttonLabel quantumWizButtonPaperbuttonLabel exportLabel']
dddddddd
eeeeeeee
ffffffffffff
ggggggggg
[RPA][ERROR] - cannot find /html[1]/body[1]/div[1]/div[3]/form[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/input[1]
[RPA][ERROR] - cannot find /html[1]/body[1]/div[1]/div[3]/form[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/input[1]
[RPA][ERROR] - cannot find /html[1]/body[1]/div[1]/div[3]/form[1]/div[2]/div[1]/div[2]/div[3]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/input[1]
[RPA][ERROR] - cannot find //div[4]//div[1]//div[1]//div[2]//div[1]//div[1]//div[1]//div[1]//input[1]
[RPA][ERROR] - cannot find //div[5]//div[1]//div[1]//div[2]//div[1]//div[1]//div[1]//div[1]//input[1]
[RPA][ERROR] - cannot find //span[@class='appsMaterialWizButtonPaperbuttonLabel quantumWizButtonPaperbuttonLabel exportLabel']
hhhhhhhh
iiiiiiiiiiiiiii
jjjjjjjjjjjjjjj
kkkkkkkkk
qqqqqqqq
wwwwww
zzzzzzzzzzz

**Comment by kensoh** [comment]
Hi Ekram, this would be because these elements really do not exist at some of the loop iterations.

It could be the Google Forms HTML structure varies slightly during different iterations. The reason for that may be intentional by Google to prevent automation, or maybe just part of the web design implementation used.

**Comment by kensoh** [comment]
Closing the issue for now, but will look out for your inputs!
