### ISSUE TITLE
Nginx and Gunicorn /usr/bin/env: bash: No such file or directory - deploy without using virtual environment

### ISSUE THREAD

**Issue by abitamaspp** [tebelorg/RPA-Python#258]
Hi Kensoh and everyone,

I have my Flask app deployed at Amazon Linux 2 EC2 instance, served using Nginx and Gunicorn. Similar to SNavgale's problem [(#186)](https://github.com/tebelorg/RPA-Python/issues/186), TagUI in my app only runs when I run it under the default Flask development server (run locally on `127.0.0.1:[port here]`). Here's what I get if I serve my app with Nginx and Gunicorn:

![image](https://user-images.githubusercontent.com/56988153/119334859-c8dd9780-bcb5-11eb-927a-1833b1e800c9.png)

I've upgraded the TagUI to `1.36.0` version, tried `headless_mode = True` and false, but still get the same message.

Regards,
Abitama

**Comment by kensoh** [comment]
Hi @abitamaspp, there are 2 ways to explore this problem. First way is do the checks mentioned in #186.

Most importantly is test whether Chrome runs correctly there on your server. Many run issues I heard from users on Linux is being able to launch Chrome. Following is how Chrome is invoked, where by default $chrome_command is google-chrome, $TAGUI_DIR is the tagui/src folder, $chrome_switches is --remote-debugging-port=9222 about:blank, $window_size I think can ignore and $headless_switch is --headless --disable-gpu

```
$chrome_command --user-data-dir="$TAGUI_DIR/chrome/tagui_user_profile" $chrome_switches $window_size $headless_switch
```
---

Hi Guys, can you try the latest package with `pip install rpa --upgrade` and let me know if it works now?

- There has been a fix implemented to run on macOS properly, in response to a recent macOS change
- For Ubuntu, still require to install PHP with `apt-get update; apt install php;`
- For Linux OSes, the default for this package is to use Chrome, so Chrome browser needs to be installed
- For Linux or macOS, Chrome does not allow a user to run it as root, a hack is needed if you really need root
- Using Chromium browser is possible but a simple hack is required to change the package default to use Chromium
- Using Microsoft Edge is also possible but a hack would be needed until upstream TagUI supports Edge option

Below is a working Google Colab notebook with some of the above hacks implemented fyi - 
https://colab.research.google.com/drive/13bQO6G_hzE1teX35a3NZ4T5K-ICFFdB5?usp=sharing

Also, free feel to join Telegram group chat for TagUI community to post any questions - https://t.me/rpa_chat

PS - this RPA package is based on a forked version of TagUI open-source RPA tool

---
The second way is progressively test your Python script from basic to the full script, for eg
```
python demo.py
```
**Level 1 - demo.py**
```
import rpa as r
print('TEST MESSAGE')
print(r.tagui_location())
```

**Level 2 - demo.py**
```
import rpa as r
r.debug(True)
r.init()
r.close()
```

**Level 3 - demo.py**
```
import rpa as r
r.debug(True)
r.init()
r.url('https://google.com')
r.snap('page','web.png')
r.close()
```

**Comment by kensoh** [comment]
The assumption is on your server there is access to GitHub to auto-download and install TagUI. Otherwise you have to use pack() to create a zip to move there instead - https://github.com/tebelorg/RPA-Python#core-functions

**Comment by abitamaspp** [comment]
Hi Ken, thank you for responding my issue

May I know how to check whether the browser runs correctly on my server? I use Chromium there and to me, that browser seems to run just fine (I also had hacked `tagui` file in ~/.tagui/src so that `chrome_command`'s value is `chromium-browser`)

About access to GitHub on my server, I think it doesn't have such connection, because I use `pip install rpa --upgrade` to install the 1.36.0 version

I the mean time, I'll test my pyhton script progressively as you suggested. I'll let you know as soon as possible

**Comment by kensoh** [comment]
Hi @abitamaspp, yes the command is here. You can try replacing with the values on your system and try -

https://github.com/tebelorg/RPA-Python/issues/258#issuecomment-847462340

Alternatively you can edit the tagui/src/tagui file, look for that command and above that line, do an echo to see the actual command. After that, test it to see if Chromium crashes.

```
echo $chrome_command --user-data-dir="$TAGUI_DIR/chrome/tagui_user_profile" $chrome_switches $window_size $headless_switch
```
\
Access to GitHub I think is still needed when the package is upgraded, as it pulls updated TagUI codebase from a forked version of TagUI on GitHub to save it locally. If there is no access, you can generate and copy the files over beforehand using pack() and update() on a computer with access to download files from GitHub.

**Comment by abitamaspp** [comment]
Hi Ken @kensoh, sorry for late responding

Here's what I got after adding that echo line

![image](https://user-images.githubusercontent.com/56988153/120422032-a15f8c80-c391-11eb-9b6f-0e63e1835825.png)

**Comment by kensoh** [comment]
Thanks @abitamaspp here's 2 next steps to test -

1. try running that entire line of `chromium-browser ...` from your terminal to see what error messages appear
2. remove that echo line that you added and test this command below to test run a workflow
`/home/ec2-user/.tagui/src/tagui /home/ec2-user/.tagui/src/samples/1_yahoo headless`
3. cd to this folder home/ec2-user/.tagui and do `chmod -R 755 *` to see if permissions related problem

**Comment by abitamaspp** [comment]
Hi Ken @kensoh, thank you for still replying to my comment

I've tried the steps and TagUI runs without error, yet the TagUI scripts in my app still don't work.

For now, my team decided to deploy the Flask app on another Amazon Linux 2 EC2 instance but without using virtual environment. This time the TagUI script runs as I expected, so I think this can be a solution for others that are trying similar things as me and my team does.

Again, thank you so much for your help and suggestions, Ken 😃

**Comment by kensoh** [comment]
Thanks @abitamaspp sure! If in future any users would like to explore deployment using virtual environment, feel free to do so and ping me if you run into any issues. We can figure out together the unique blocker and solution for the virtual deployment.
