### ISSUE TITLE
Unable to type the URL in browser - maybe AVG false-positive? pending checks

### ISSUE THREAD

**Issue by akjoshi009** [tebelorg/RPA-Python#263]
Is anybody face the problem where Browser just start but unable to put the url in address bar 
Code:
import rpa as r

r.init()
r.url('https://www.google.com')
r.type('//*[@name="q"]', 'decentralization[enter]')
print(r.read('result-stats'))
r.snap('page', 'results.png')
r.close()

**Comment by kensoh** [comment]
Are you using AVG Internet Security? There is a false-positive today which deletes the tagui_chrome.php file needed to connect to Chrome. If yes, this is the workaround until whitelisting is complete - https://github.com/tebelorg/RPA-Python/issues/262

Can you run a r.debug(True) before r.init(), and also share the contents of the file below,
`print(r.tagui_location() + '/.tagui/src/tagui_chrome.log')`
