### ISSUE TITLE
Automatically replacing files when downloading - yes this is behaviour of downloading

### ISSUE THREAD

**Issue by iCreamble** [tebelorg/RPA-Python#265]
It might be something wrong with my code, but the problem is:
My automation process includes clicking on a button that downloads a file. This file, often, has the same name, so when I do it manually the file is downloaded as file.pdf, file(2).pdf, file(3).pdf and so on...
When I made the automation process, two things changed:
1. The download path is no longer the "DOWNLOADS" folder, but the script.py path;
2. The downloads keep replacing each other, always with file.pdf name, so I cant have multiple files with the same name

The automation process simply includes the click on the button:
r.click('//*[@id="print-button"]')

Is it normal? Can it be changed?

Thanks!

**Comment by kensoh** [comment]
Hi @iCreamble! I confirm that these 2 actions are the behaviour for the upstream TagUI project.

There is an open issue there to make it easier to change the download folder - https://github.com/kelaberetiv/TagUI/issues/1035

But in the meantime, it will be using this line of code to specify download location - https://github.com/tebelorg/RPA-Python/issues/210#issuecomment-812659352

For overwriting the same file, I don't know how to change this behaviour and not found anything from googling. If you find something you can share with me. Alternatively, every time you download something, you can rename the file to some other filename using Python os.rename - https://www.tutorialspoint.com/python/os_rename.htm

**Comment by kensoh** [comment]
Adding on, there is r.download() which you can try out to see if that works for you. That can specify download location.

**Comment by iCreamble** [comment]
Your suggestions worked! Thanks. I did not find a way to modify the replacement problem, but the os.rename worked fine.
Thanks!
