### ISSUE TITLE
How to get the coordinate of an element identifier - use hover('image.png') then mouse_xy()

### ISSUE THREAD

**Issue by BeanHhb** [tebelorg/RPA-Python#270]
I want to do some click operation on a captcha picture, so I need the exact coordinate of the element identifier.
I have tried this way:
`r.hover("//div[contains(@class, 'geetest_item_wrap')]/img")`
`print(r.mouse_xy())`
But the mouse doesn't move to the img visually, result in the coordinate is not right.
I wonder how to get it, tks~

**Comment by fi-do** [comment]
Hey @BeanHhb ,

not sure how the source code of the website looks like. But did you checked if your identifier works?
`print(r.exists("//div[contains(@class, 'geetest_item_wrap')]/img"))`

Hope it will help you,
fi-do

**Comment by BeanHhb** [comment]
Hi fi-do,
thanks for your advice, here is my feedback.
I check the hover() function,  and find that the function is run but mouse not go to the position visually.
Like the picture, I hover the 'circle i' icon. 
![image](https://user-images.githubusercontent.com/55520057/122503652-6ca73280-d02b-11eb-81db-a85e9f7ffcd5.png)

**Comment by kensoh** [comment]
Adding on to @fi-do's reply, @BeanHhb for r.mouse_xy() to work the mouse must be really moved to that position. To move the actual mouse cursor there, requires using visual automation method. For eg below -

**i_button.png**
![i_button](https://user-images.githubusercontent.com/10379601/124386717-43b2bd00-dd0e-11eb-9cba-66c6fc804c81.png)

**example**
```py
r.hover('i_button.png')
print(r.mouse_xy())
```

It's also possible to use `r.send()` to send custom TagUI commands to retrieve the co-ordinates of a web element without using visual automation, but it involves writing a number of lines of code to do a custom query and parsing the result. So above method using visual automation is the easiest solution.
