### ISSUE TITLE
r.keyboard() do not work after Git Bash terminal is opened - maybe Git Bash not compatible

### ISSUE THREAD

**Issue by kamesh95** [tebelorg/RPA-Python#272]
There seems to be some issue where if we open Git Bash using RPA, the subsequent keyboard, mouse clicks do not seem to do anything. The script just exits after going through all the steps after opening Git bash. Can you help here? Thank you :) 

Attached the script that I am using:

```
import rpa as r

r.init(visual_automation = True, chrome_browser = False)
r.keyboard('[win][d]')
r.keyboard('[win]')
r.keyboard('Git Bash')
r.wait(15)
r.keyboard('test command') // This is not written onto the git bash terminal
r.wait(2)
r.keyboard('[win]') // No windows menu is seen
r.close()
```

**Comment by fi-do** [comment]
Hola @kamesh95 ,

is your git bash cli window active after you called it? 
One suggestions of mine would be to call the executable directly via r.run("path/to/git_bash.exe") to avoid the keyboard steps 1-3. 

Hope it will help you,
fi-do

**Comment by kamesh95** [comment]
@fi-do Thanks for your reply, I tried running git bash via r.run but still the behaviour is same, it seems to be stuck and does not output any keys after that. The window for git bash is in focus, when I press any key it gets typed on the terminal but not sure why the same is not working via rpa as the script seems to be hung up. Can you try this at your end and let me know if it works ? Thanks!

**Comment by fi-do** [comment]
Hey @kamesh95,
I would like to help you out, but unfortunately I do not have an system operating Windows. Maybe someone else can replicate this issue.

In the mean time, can you do 2 things for me?

- Report your git bash version
- execute an "reset" command, even you do not see anything.

```

# git bash is active
r.keyboard('reset[enter]')  
r.keyboard('test command')

```
Thanks,
fi-do

**Comment by kamesh95** [comment]
@fi-do I am using Git 2.29.2.2 and below is the output of bash --version:
```
GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)
```

It cannot type in even that reset command so just exits after going through these script lines. 
One weird thing I noticed is, I am using same bash terminal in VScode. But when I try to simulate the same in VScode, it works fine. I can see all the commands and everything goes as per script. So my last resort would be to open VScode and use the terminal from there instead of opening Git Bash. 

Thanks @fi-do

**Comment by kensoh** [comment]
Adding on, it sounds like for some reason. the Git Bash window may be an exception app that can't react to the keyboard inputs from the tool. On the low-level, it uses the Java Robot class to simulate keyboard presses. It might be the simulated keyboard entries are not accepted and recognised by Git Bash.

As a last check if you would like to, you can share the logs for the keyboard actions, to see if there is any error reported. The logs can be found in tagui\src\tagui.sikuli folder. To know where tagui folder is installed on your Windows, you can use `print(r.tagui_location())`
