### ISSUE TITLE
Scroll down a webpage - use keyboard('[pagedown]') to simulate scrolling down a webpage

### ISSUE THREAD

**Issue by amank12** [tebelorg/RPA-Python#273]
There is a DIV element on web page that gets populated with more elements as I scroll down. I want to read all elements of this DIV, hence scrolling down is required.

Not sure how to scroll down using RPA-Python

**Comment by fi-do** [comment]
Hey @amank12,

for this scenario I would use the down arrow key `r.keyboard('[pagedown]')` to operate the div population until you cant find new elements in your dom structure via `r.dom('document.getElementById(your_div_tag_id);')`.

Hope it will help you,
fi-do

**Comment by amank12** [comment]
I have initialized rpa as r.init(chrome_browser = True)

r.keyboard requires visualization mode

**Comment by kensoh** [comment]
Adding on, you can do `r.init(True)` which will launch with visual automation mode. This is required for for `keyboard()`.

After that you can do a `r.click('image.png')` on the browser to make sure the browser is in the foreground, then do `r.keyboard('[pagedown]')` to scroll down the webpage as many times as required to let it load more items.

**Comment by kensoh** [comment]
PS - image.png is an image snapshot of somewhere on the browser to tell the tool to make it in the foreground

**Comment by kensoh** [comment]
If you try to do `r.hover()` on the last element of the DIV it might also work. First use `r.count()` to count the number of elements then use XPath to form the element. This would simulate scrolling down the webpage to that element, but may not work as well as the above method which really sends a keyboard pagedown to browser to scroll down the webpage.

**Comment by amank12** [comment]
> Adding on, you can do `r.init(True)` which will launch with visual automation mode. This is required for for `keyboard()`.
> 
> After that you can do a `r.click('image.png')` on the browser to make sure the browser is in the foreground, then do `r.keyboard('[pagedown]')` to scroll down the webpage as many times as required to let it load more items.

This solution worked.  Thanks.

**Comment by amank12** [comment]
This solution is closed
