### ISSUE TITLE
r.click() not working sometimes - most likely webpage HTML changed, use relative XPath

### ISSUE THREAD

**Issue by sangasangasanga** [tebelorg/RPA-Python#277]
Hi @kensoh, I created a script to crawl from reddit. It has working fine until recently, the r.click() function does not work sometimes. I am attaching the video where tagui is supposed to click on the title for the first post and it will show the full post, but it does not click on it.

> r.init(visual_automation=True)
r.url('https://www.reddit.com/search/?q=pipe%20leak&t=week&type=link')
r.keyboard('[enter]')
r.wait(5)
print(r.read('/html/body/div[1]/div/div[2]/div[2]/div/div/div/div[2]/div[3]/div[1]/div[3]/div[1]/div/div/div[2]/div/div[2]/div[1]/div[1]/a'))
r.click('/html/body/div[1]/div/div[2]/div[2]/div/div/div/div[2]/div[3]/div[1]/div[3]/div[1]/div/div/div[2]/div/div[2]/div[1]/div[1]/a')

https://user-images.githubusercontent.com/34553270/123368249-02a00780-d5ae-11eb-837b-c631aab3a6ae.mp4

**Comment by kensoh** [comment]
Hi @sangasangasanga the most likely reason is there is some change in the webpage HTML layout. The XPath you used is full XPath which is highly likely to break when small changes happen on a website. You can try the [SelectorsHub Chrome extension](https://chrome.google.com/webstore/detail/selectorshub/ndgimibanhlabgdgjcpbbndiehljcpfh?hl=en) by my friend [Sanjay Kumar](sanjayselectorshub). Using that, you can copy out the relative (and better) XPath by right-clicking on a web UI element.
