### ISSUE TITLE
Chrome downloads file where manual process opens "Save As" window - as designed

### ISSUE THREAD

**Issue by zanyzyzzyx** [tebelorg/RPA-Python#278]
Hey Ken, 

I have webpage where I want to download something.  When doing the process manually, I click on the download button and it opens the "Save As" window.  But when I run an rpa automation it instead "attempts" to download the file (shows said file in the chrome downloads cache but not in my desktop downloads folder).  I've tried clicking said download button a few different ways (id, xpath, visual automation) and they all produce the same outcome.  Any idea why this could be happening?  

Thanks!

**Comment by kensoh** [comment]
Hi @zanyzyzzyx I see, this is the default behaviour inherited from TagUI. The files will be downloaded to the folder where the automation process is running. You can do `import os; print(os.getcwd())` to know where is your current directory.

This folder is normally where your Python script is, but if you call to run from another folder then it will be your calling folder. For eg if you are in `c:\folder1` and you do `python c:\folder2\automation.py`, the file will be saved to `c:\folder1`.

**Comment by kensoh** [comment]
Adding on, you can try to use visual automation method to do the download on your own Chrome browser.

This way by clicking and selecting visually, the behaviour with be 100% the same as how you'll do it manually.

The default way of automating websites through backend websocket connection has some minor difference.
