### ISSUE TITLE
Spawning RPA script from Node.js does not work

### ISSUE THREAD

**Issue by kamesh95** [tebelorg/RPA-Python#280]
I am trying to create a flow where I will execute several RPA scripts written in python from my Node.js parent process sequentially. But the issue is when I spawn or execute the script, it does not respond. I tried adding logs to my RPA script and I see that the flow is stuck at:

```
r.init(visual_automation = True, chrome_browser = False)

// My node.js statement to start rpa script
childProcess.execSync(`py C:\\Users\\test\\Desktop\\test_rpa.py`);
```

The same script works when executed from Powershell manually. Also, other python scripts without rpa code work fine when executed from node.js

Can someone help me with this? Thanks.

**Comment by kamesh95** [comment]
Update: This only happens when I execute the node script from Git Bash, when I execute same from PowerShell, everything looks fine. So I will be using PowerShell for this. Will close this issue.

**Comment by kensoh** [comment]
I see, thanks @kamesh95 for updating back here! Yes Git Bash is not really a Linux environment and it is also not really a Windows environment. Maybe that's why the package is confused and not working properly for the right environment.
