### ISSUE TITLE
trying to run any script in Python nothing happens - pending checks and replication

### ISSUE THREAD

**Issue by marcelocecin** [tebelorg/RPA-Python#282]
Hi Ken
We are migrating to a dedicated server at Godaddy
the command `./tagui` is working normally
But when we try to run any script in Python nothing happens
How can we debug what may be happening?
thanks

![WhatsApp Image 2021-07-14 at 21 52 08](https://user-images.githubusercontent.com/2955762/125711312-a76f2a1d-9ddb-401e-8cfd-1f77a125c8bd.jpeg)

**Comment by kensoh** [comment]
Hi Marcelo, can you try adding `r.debug(True)` before you `r.init()` to see what could be the problem?

Also, this is a working reference setup for running the package on Linux (in this case is using root user and Chromium) -

https://colab.research.google.com/drive/13bQO6G_hzE1teX35a3NZ4T5K-ICFFdB5?usp=sharing

**Comment by marcelocecin** [comment]
Hi Ken
continues in the same way
Follow the Python script
```python
import rpa as r
r.setup()
r.dump(r.load('/home/rpa/.tagui/src/tagui').replace('"google-chrome"', '"chromium-browser"').replace('--disable-gpu', '--disable-gpu --no-sandbox'), '/home/rpa/.tagui/src/tagui')
r.init()
r.debug(True)
r.url('https://www.google.com')
r.type('//*[@name="q"]', 'decentralization[enter]')
print(r.read('result-stats'))
r.snap('page', 'results.png')
r.close()
```
<img width="817" alt="" src="https://user-images.githubusercontent.com/2955762/125711990-cde711ce-b108-4492-a372-ac9f2165185e.png">
and the evidence that the tagui is ok
<img width="804" alt="" src="https://user-images.githubusercontent.com/2955762/125712353-b45859d9-7520-4c96-a91d-29f30de604be.png">
thanks

**Comment by marcelocecin** [comment]
hi Ken
the strangest thing is that when I run the `tagui` command, the browser is opening headless even without including the option
thanks

**Comment by marcelocecin** [comment]
hi Ken
I will end the issue
we discovered the error trying to run the official version of TagUI v6.46 for Linux
there was an error not finding curl installed
![WhatsApp Image 2021-07-16 at 13 44 58](https://user-images.githubusercontent.com/2955762/125982071-1e23fcf1-47ae-480d-833e-74f49bf8063c.jpeg)
after installation the python version worked
thanks

**Comment by kensoh** [comment]
Thanks Marcelo for updating back here your findings! I'll follow-up with your other issue raised at TagUI repo.

The gist is running both RPA for Python and TagUI on the same computer requires 2 separate TagUI installations -

https://github.com/kelaberetiv/TagUI/issues/1079#issuecomment-881616841
