### ISSUE TITLE
Loop though options - looks like the for loop logic for this example is incorrect

### ISSUE THREAD

**Issue by rlpatrao** [tebelorg/RPA-Python#285]
Hello, is there a code example for looping through options below: 

![image](https://user-images.githubusercontent.com/18295519/126222228-9e0a4107-3458-4452-bea9-cceb98a2b64a.png)

I tried the following without any luck

```
n = r.count('//*[@id="batch_import_template_unit_operation"]/option')
for x in range(1, n):
    r.click('//*[@data-original-title="Options"]')
    # r.click('//*[@class="data-original-title"]')
    r.click('Download Import Template')
    r.select('//*[@id="batch_import_template_unit_operation"]', str(x))
    r.snap ('page', str(x) + '-option.png')
```

**Comment by kensoh** [comment]
Hi @rlpatrao from your code, I'm guessing the design is incorrect. When you loop through using range(1, n), you are incrementing 1 by 1, eg 1, 2, 3, 4, 5. However, for select() the option parameter is either the text of the option or the value attribute of the option. From above screenshot, the value isn't 1, 2, 3, 4, 5 but 1, 34, 5, 6, etc.. Thus such a for loop will not work. I'm not sure if below might work or not, but you can try it. It might work to do this way to incrementally process.

```py
r.click('(//*[@id="batch_import_template_unit_operation"]/option)[' +  str(x) + ']')
```

Above is XPath syntax to select the xth occurrence of a web element.
