### ISSUE TITLE
Cannot find rpa_python error in my project path - issue due to OneDrive app / config

### ISSUE THREAD

**Issue by qhaliff39** [tebelorg/RPA-Python#288]
Hi @kensoh. 

I have installed rpa using pip install rpa. Everything is fine with setup as the code below

`[RPA][INFO] - setting up TagUI for use in your Python environment
[RPA][INFO] - downloading TagUI (~200MB) and unzipping to below folder...
[RPA][INFO] - C:\Users\User\AppData\Roaming
[RPA][INFO] - done. syncing TagUI with stable cutting edge version
[RPA][INFO] - TagUI now ready for use in your Python environment
`

However, when I initiate rpa.init() and run my python script, following error is raised.

[RPA][ERROR] - following happens when starting TagUI...

ERROR - cannot find C:\Users\User\OneDrive\Desktop\Work\Automation\rpa_python
ERROR - automation aborted due to above 

Can you help me.

Regards,
Qhaliff

**Comment by kensoh** [comment]
Hi Qhaliff, this may be due to file and folder access permissions. Can you check that there is really that file there?

That file will be created during r.init(). And it is created in the current working directory, usually where your script is.

**Comment by kensoh** [comment]
You can confirm the current working directory with `import os; os.getcwd()` inside your Python script.

**Comment by qhaliff39** [comment]
![image](https://user-images.githubusercontent.com/71436000/128795637-40e2b081-5b86-41f9-bf21-1a35ddb10a52.png)

There is rpa_python file in my working directory and I can confirm my current working directory is C:\Users\User\OneDrive\Desktop\Work\Automation using os.getcwd().

I wonder what is the problem..

Thank you for your time btw! Can't wait to get this working and explore all the features.

**Comment by kensoh** [comment]
Try this -
1. check folder where the package is installed -
```
import rpa as r
r.__file__
```

2. in that folder, edit the file tagui.py and search for this line - 
```
tagui_cmd = tagui_executable + ' rpa_python ' + browser_option
```

3. add another line below the line in step 2
```
print(tagui_cmd)
```

4. try running again, you should be able to see the full command to run

5. get that full command and try running it from your command prompt to see what happens

If there is error, check whether your Python process has permissions to access the files there. I know when I install Python from Microsoft store, any files created by the Python process can only be access by it and not other apps. This might be the reason why TagUI can't read the file rpa_python. One way is try installing python from python.org and run that python instead to see if same thing happens.

**Comment by qhaliff39** [comment]
Noted, I have installed python from python.org. 

`r.__file__` brings up `C:\Users\User\anaconda3\Lib\site-packages.`

I did step 2 and 3. The full command printed was `C:\Users\User\AppData\Roaming/tagui/src/tagui rpa_python chrome`

When i run the command in command prompt there is an error. It cannot locate chrome.exe

`C:\Users\User>C:\Users\User\AppData\Roaming/tagui/src/tagui rpa_python chrome
ERROR - cannot find Chrome at "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
update chrome_command setting in tagui\src\tagui.cmd to your chrome.exe`

I went through the chrome.exe and it's in C:\Program Files\Google\Chrome\Application\chrome.exe. So I updated the chrome_command in tagui.cmd to this path.

However the following error occured.

Google chrome cannot read and write to its data directory. chrome\tagui_user_profile.

**Comment by kensoh** [comment]
Think this may be the possible solution. Save in other folder outside of the OneDrive folder. Another user has same problem - 

https://t.me/rpa_chat/4766

**Comment by qhaliff39** [comment]
Excellent! r.init() is working fine now. Why is this happening do you suppose? Is Onedrive preventing the accessing of the rpa_python file?

**Comment by kensoh** [comment]
Great! I've no idea, but googling found that it is common for accessing files on OneDrive to have problems - https://www.guidingtech.com/fix-cant-open-files-onedrive-error-windows/

**Comment by qhaliff39** [comment]
I see, thank you @kensoh . I've thoroughly enjoy exploring what rpa-python has to offer. Thanks for your hard work.

**Comment by kensoh** [comment]
Thank you @qhaliff39 for your appreciation. I created this package, and still maintain / support it using my personal time. For TagUI RPA - https://github.com/kelaberetiv/TagUI - I created it some years back and been developing it at AI Singapore.

**Comment by kensoh** [comment]
Hope the package can be a good automation tool in your digital toolbox!
