### ISSUE TITLE
chrome.exe - Application Error (The exception Breakpoint) - pending clues

### ISSUE THREAD

**Issue by Mavericks334** [tebelorg/RPA-Python#292]
Hi @kensoh ,

While running the following code i receive the error attached.

```
import rpa as r
r.init()
```

![image](https://user-images.githubusercontent.com/30084130/129399282-f50dec5d-cff5-4d90-a790-7fe45ad48f39.png)

How do i fix this issue.

Regards,
Ren.

**Comment by kensoh** [comment]
Haven't heard this reported by any users before, try googling and see if any of the answers help, for eg -

https://silicophilic.com/exception-breakpoint-0x80000003/
https://www.technipages.com/fixing-google-chrome-error-code-status_breakpoint
https://answers.microsoft.com/en-us/windows/forum/all/the-exeption-breakpoint-a-breakpoint-has-been/b0606452-1497-4e3b-92ec-d47327aeaa07
https://windowsreport.com/breakpoint-has-been-reached/

**Comment by kensoh** [comment]
Seems like the most common cause is overclocking of CPUs. But you could provide other info (detailed exact steps to reproduce problem, do the steps always create this error, did this error happen before I thought you are using fine, did it happen suddenly, does it still happen after you restart computer, does it happen on another laptop you have etc, does it happen when you are using Chrome manually instead of through this RPA package etc...)

![Screenshot 2021-08-15 at 12 44 00 AM](https://user-images.githubusercontent.com/10379601/129453344-93547125-77a7-4212-8e8c-6a4d64654ff2.png)

**Comment by Mavericks334** [comment]
Hi @kensoh ,

I was unable to work on the automation in my Virtual machine due to Firewall issues for the specific process. When i try the same on my 1st desktop this error pops up. On the VM i dont get this error. Which is strange.

Regards,
Ren.

**Comment by kensoh** [comment]
I see, can you try installing TagUI human language version using the steps here and see if you have the error?

https://tagui.readthedocs.io/en/latest/setup.html

If yes, TagUI has a weekly Zoom Q&A call to troubleshoot tricky issues like this, you can join if you are available.

It is every Thursday at 4-5pm Singapore time (UTC+8) - https://github.com/kelaberetiv/TagUI/issues/914

**Comment by Mavericks334** [comment]
Hi @kensoh ,

The issue is fixed by updating the latest chrome version. However, the url does not open in the browser and it just hangs with the below information

```
[tagui] START  - listening for inputs

[tagui] INPUT  -
[1] {"id":1,"method":"Page.setDownloadBehavior","params":{"behavior":"allow","downloadPath":"C:\\Users\rerere\"}}
[tagui] OUTPUT -
[1] {"id":1,"result":{}}

[tagui] INPUT  -
[2] {"id":2,"method":"Page.navigate","params":{"url":"about:blank"}}
[tagui] OUTPUT -
[2] {"id":2,"result":{"frameId":"213E57C893C61E4933F726D2A78EB0F7","loaderId":"4D5E65D0B042EB520FA51D3E07DB1571"}}

[tagui] INPUT  -
[3] {"id":3,"method":"Runtime.evaluate","params":{"expression":"document.title"}}
[tagui] OUTPUT -
[3] {"id":3,"result":{"result":{"type":"string","value":""}}}
```
```
[RPA][INFO] - setting up TagUI for use in your Python environment
[RPA][INFO] - unzipping TagUI (~200MB) from rpa_python.zip to below folder...
[RPA][INFO] - C:\Users\rerere\AppData\Roaming
[RPA][INFO] - done. syncing TagUI with stable cutting edge version
[RPA][INFO] - TagUI now ready for use in your Python environment
```

**Comment by Mavericks334** [comment]
I also tried 

`r.url('yahoo.com,chrome_browser=False)`

to avoid the issue and load in edge since upgraded to 1.44 still opens in Chrome and just hangs and does not proceed further with below error code

``[RPA][ERROR] - following happens when starting TagUI...`
`
Regards,
Ren,

**Comment by kensoh** [comment]
I see, the Python package does not support running in MS Edge. Can you try below on your working VM and this computer, to see if there are any clues on the tagui_chrome.log when running below script?

```py
import rpa as r
r.init()
r.url('https://google.com')
r.close()
```

**Comment by Mavericks334** [comment]
The below details are missing in system where Chrome just sits and waits. The url is not added.
```
tagui] INPUT  - 
[4] {"id":4,"method":"Runtime.evaluate","params":{"expression":"window.location.href = \"https://google.com\";"}}
[tagui] OUTPUT - 
[4] {"id":4,"result":{"result":{"type":"string","value":"https://google.com"}}}

[tagui] INPUT  - 
[5] {"id":5,"method":"Runtime.evaluate","params":{"expression":"document.location.href"}}
[tagui] OUTPUT - 
[5] {"id":5,"result":{"result":{"type":"string","value":"https://www.google.com/"}}}

[tagui] INPUT  - 
[6] {"id":6,"method":"Runtime.evaluate","params":{"expression":"document.title"}}
[tagui] OUTPUT - 
[6] {"id":6,"result":{"result":{"type":"string","value":"Google"}}}
```
With this error in Jupyter.

`[RPA][ERROR] - following happens when starting TagUI...`

Regards,
Ren

**Comment by kensoh** [comment]
I see, can you try this? - https://github.com/tebelorg/RPA-Python/issues/292#issuecomment-899682243

**Comment by Mavericks334** [comment]
I tried it and few files are not being copied. Is there a work around with Proxies where we could give the proxy details for the site to open something like this

```
proxies = {"http":"xyxyx:8080"}
auth = HTTPProxyAuth("username", "password")
```
Regards,
Ren

**Comment by kensoh** [comment]
1. Can you share more which few files you mean? For the installation steps here for TagUI - https://tagui.readthedocs.io/en/latest/setup.html

For setting proxy for normal Chrome browser, I have not done it before you can google to search, should be doable.

2. For setting proxy for Python, you can do this way - https://github.com/tebelorg/RPA-Python/issues/97#issue-547148648

**Comment by kensoh** [comment]
**Above is my 3rd reminder to ask you to try installing TagUI directly to see if that works.**

If you still ignore my suggestion I cannot help you anymore and will stop replying your issues.

**Comment by Mavericks334** [comment]
Hi @kensoh, I have tried that. No all files are being copied. The other machine is also my office machine. I not sure what else to do. Since i dont have the access on this machine to install any JDKS

**Comment by kensoh** [comment]
Can you list which are the files below which are not copied? OpenJDK not needed if not using r.init(True).

![Screenshot 2021-08-19 at 12 39 26 AM](https://user-images.githubusercontent.com/10379601/129937758-5c03fcef-d2b2-4d6c-9684-230a8086f208.png)

**Comment by Mavericks334** [comment]
Will tryit again and let you know

**Comment by kensoh** [comment]
If you can try by today 4pm Singapore time (UTC+8), you can join the weekly Zoom Q&A call to troubleshoot more -

https://github.com/kelaberetiv/TagUI/issues/914

**Comment by Mavericks334** [comment]
closing the issue as i'm able to work on another machine
