### ISSUE TITLE
Automating Shadow DOM elements - use dom step and JavaScript to interact

### ISSUE THREAD

**Issue by Mavericks334** [tebelorg/RPA-Python#295]
Hi @kensoh,

How do I automate an element that is inside Shadow DOM? Using Xpath and r.click() is not working.

Regards,
Renato.

**Comment by kensoh** [comment]
Hi Renato, can you share a sample website and what element you want to click on?

If it is inaccessible might need to use visual automation method to click on image snapshots.

**Comment by Mavericks334** [comment]
Hi @kensoh 

Tried to find the label. No success with that as well. This is an internal site unfortunately it is not accessible outside

`search_text=r.search('Reason')`

`<div class="label">Reason</div>`

While try visual automation to see if it works.

Regards,
Ren.

**Comment by Mavericks334** [comment]
This site has an example with google downloads. Hope it is helpful. However, it is based on selenium

https://www.seleniumeasy.com/selenium-tutorials/accessing-shadow-dom-elements-with-webdriver

**Comment by kensoh** [comment]
Hi Renato, this will require learning JavaScript to know what standard JS functions to use for selecting dropdown box or clicking a button. I'm afraid googling to learn more is the only path, same as above if you use Selenium's method.

Need to send the raw JavaScript to do the automation on the shadow dom.

You can read TagUI's codebase, of course, but that will probably take 10X more time than googling the JavaScript code directly. Because a lot is done in TagUI's backend to perform a simple action, to make it work most reliably.

**Comment by Mavericks334** [comment]
Hi @kensoh found thee solution using JS function calls. Code is longer than expected

```
r.dom("root1 = document.querySelector('body > app-root > div > app-queue > div > app-workqueue-tabs > div > div.row.proton-container__workqueue-cards > div > app-workqueue-cards > div > div:nth-child(4) > scc-filters').shadowRoot")
r.dom("return root1.querySelector('div > div.container > div:nth-child(9) > div.label').click()")

r.dom("root1 = document.querySelector('body > app-root > div > app-queue > div > app-workqueue-tabs > div > div.row.proton-container__workqueue-cards > div > app-workqueue-cards > div >div:nth-child(4) > scc-filters').shadowRoot")
r.dom("root2 = root1.querySelector('div > div.container > div:nth-child(9) >div.dropdown-container.ng-star-inserted > div.dropdown-content > div > scc-filter-item').shadowRoot")
r.dom("root3 = root2.querySelector('div:nth-child(23) > scc-checkbox-filter').shadowRoot")
r.dom("return root3.querySelector('div.search > -textbox > div > input').value("01")")
```

**Comment by kensoh** [comment]
Oh great! Yes, it is a pain to navigate shadow dom. Thanks for sharing back your solution.

In this case you have to navigate 3 layers down before doing the actual selection.

**Comment by Mavericks334** [comment]
hi @kensoh,

With the above solution i'm able to send values. When I manually enter values the filter shows that specific values. When it is sent via code the filter is not working.

Any suggestions on this

**Comment by kensoh** [comment]
A) Do you mean this works -

```
r.dom("return root3.querySelector('div.search > -textbox > div > input').value=01")
```

B) But this fails?

```
r.dom("return root3.querySelector('div.search > -textbox > div > input').value="+co)
```

The code in B looks correct, so I don't know why A works but B fails.

But you have typo in the variable RC `rc=['01','02]`. Check carefully your code again.

**Comment by Mavericks334** [comment]
> A) Do you mean this works -
> 
> ```
> r.dom("return root3.querySelector('div.search > -textbox > div > input').value=01")
> ```
> 
> B) But this fails?
> 
> ```
> r.dom("return root3.querySelector('div.search > -textbox > div > input').value="+co)
> ```
> 
> The code in B looks correct, so I don't know why A works but B fails.
> 
> But you have typo in the variable RC `rc=['01','02]`. Check carefully your code again.

Both dont work for the auto filtering part. When i enter the values manually only that value reflects but with the code all the values in the system reflect.

**Comment by kensoh** [comment]
I see, you can try out more using the Chrome console how to do this or try using visual automation method.

**Comment by Mavericks334** [comment]
> I see, you can try out more using the Chrome console how to do this or try using visual automation method.

Hi @kensoh, the item that i'm trying to send data to is not a image icon. How do i use visual automation to click on it.

**Comment by kensoh** [comment]
Yes visual automation can be anything on the screen, for eg some text box can also be captured.
See this - https://github.com/tebelorg/RPA-Python#visual-automationsee_no_evil
And this - https://github.com/aimakerspace/TagUI-Bricks/tree/master/MS-Word-Letter

Use r.keyboard() to send keystrokes, it's on the GitHub page -
https://github.com/tebelorg/RPA-Python#keyboard-automationmusical_keyboard

**Comment by Mavericks334** [comment]
@kensoh i tried and it did not work. How could i get this code to work. Which is written in selenium java. I tried every thing and it did not work.

```
case "Reason Code":
        filterElement = getSccFilterShadowRootElement()
                .findElement(By.cssSelector("div.container div[class*=ng-star-inserted]:nth-of-type(9)"));
```

**Comment by kensoh** [comment]
If you are using dom(), in JavaScript, it will be `root3.querySelector("div.container div[class*=ng-star-inserted]:nth-of-type(9)")`, assuming root3 is the shadow dom you derived here - https://github.com/tebelorg/RPA-Python/issues/295#issuecomment-916303989

`r.dom("return root3.querySelector('div.search > -textbox > div > input').value="+co)` should be `r.dom("return root3.querySelector('div.search > -textbox > div > input').value= '"+co + "'")` if co variable is a string.

Otherwise you can use visual automation to control Chrome, using here - https://github.com/tebelorg/RPA-Python/issues/295#issuecomment-918164969
