### ISSUE TITLE
Remote desktop connection / [RPA][ERROR] - cannot find image.png - pending checks

### ISSUE THREAD

**Issue by aaguirre8** [tebelorg/RPA-Python#300]
Hi Kensoh!

I made a simple script to download some data from LinkedIn. The script works perfectly fine in my computer and 3 other computers I tested. 
The script is the following:
`
import rpa as r

r.init(visual_automation = True, chrome_browser = False)
r.keyboard('[win]')
r.keyboard('firefox[enter]')
r.wait(2)
r.keyboard('https://www.linkedin.com/psettings/member-data[enter]')
r.click('sign_button.png')
r.keyboard('rewrite_with_your_username[tab]')
r.keyboard('rewrite_with_your_password[enter]')
`

However, when I try to run the script on a remote desktop connection the following error pops up:

[RPA][ERROR] - cannot find sign_button.png

What have I tried?

- Verify if there's a mismatch between the png and the display's image I try to click on.
- Replace the png file with a new one.
- Check if the directory's path is ok.
- Verify if dependencies are installed (OpenJDK). It is installed, otherwise, it wouldn't initiate the visual_automation.

I'm not sure if the issue is the remote desktop connection. Can you help me out please?

**UPDATE**
If I run the script outside the VDI, call a click command on the VDI icon and run the rest of the script, it works. Does this give you a hint?

**Comment by kensoh** [comment]
Hi Alex, this looks like probably an issue that could be replicated with the TagUI upstream project. Are you able to join a Zoom call on Thursday 4-5pm Singapore time (UTC+8)? Then you can show me more about the issue. Below is the meeting link -

https://github.com/kelaberetiv/TagUI/issues/914

**Comment by kensoh** [comment]
Oh I see... Then condition 1 is met already. Ok see you at the Zoom call tomorrow we can troubleshoot more :)

**Comment by mrmanu** [comment]
Hello, did you finally find the problem? A similar thing has happened to me, I´m working on a remote desktop and images that are detected well, stop working for no apparent reason. The captures are from the remote machine and they are correct. What could be happening?

**Comment by aaguirre8** [comment]
Hi @mrmanu !
I didn't really find the root cause of this, it seems that on a VM something goes wrong with the pixels and the bot doesn't find an exact match, thus the error. 
The workaround I did was using pyautogui with open-cv. That combination allows you to set a threshold finding a match with the image. So instead of looking for a 1.0 match with the saved image, you can set the threshold to 0.8 and it will look for that set of pixels having a 0.8 matching likelihood. Anything above the 0.95 threshold rises the error again.

**Comment by mrmanu** [comment]
It seems like a good solution, I will try that. Thanks!
