### ISSUE TITLE
Does dead pixels on monitor affect RPA process? - don't think so, pending details

### ISSUE THREAD

**Issue by richylyq** [tebelorg/RPA-Python#302]
Sounds like a dumb question to ask but my colleague and I were running the same rpa codes that we come up with, it works fine on my machine but on his, the workflow went haywire. His monitor has quite a dead pixel patch which led to this question on whether dead pixels will affect. 
it works for both of us running on headless mode anyway 🤯

**Comment by kensoh** [comment]
Hi @richylyq, first I agree that this is a mindblown question haha... Can you share here what is your RPA script?

If visual automation is used, may need to retake screenshots on your colleague computer to match correctly.

If you can share info on what is your OS and what is your colleague OS that will help.

**Comment by richylyq** [comment]
hey @kensoh 
the script is to key in the search term into Google's image search engine and download the images after clicking on the thumbnails. we didnt use visual automation, i think the differences with both of machines is my Windows OS has been updated to the latest KB patch while his is stuck at a rather old version, and the dead pixels on his screen.

**Comment by kensoh** [comment]
I see.. Here are some ideas to explore -

1. Try running in visible mode and see what happens, see if there are clues. if not try remaining steps below
2. Try running line by line in Python interactive mode or Jupyter Notebook until the step which you see error
3. Make a note of the error and share back here, and also do a r.snap('page', 'result.png') to capture screenshot
4. Check the folder print(r.tagui_location()), inside there is tagui\src\tagui_chrome.log, attach that log here
