### ISSUE TITLE
Select the Chrome Window to send keyboard() inputs - pending trying suggestion

### ISSUE THREAD

**Issue by alx-xlx** [tebelorg/RPA-Python#303]
I am trying to send
```
r.keyboard('[shift]t')
```

to the Chrome Browser, but instead, it goes to the jupyter notebook from where I am running the code.

How do I select the Chrome Window to make sure it is on foreground. and not in the background ?

**Comment by kensoh** [comment]
Hi @alx-xlx that's because Jupyter Notebook is in foreground and in focus. You can do what you will normally do to move Chrome to foreground. For example you may do a r.click('chrome_icon.png') to bring that Chrome window to foreground.

**Comment by alx-xlx** [comment]
I did as you said and got 
![](https://i.imgur.com/ph9MCSj.png)

**Comment by kensoh** [comment]
Can you try setting your Windows display Zoom % to 100% or the recommended % to see if it helps?

For Windows, that is a common cause of this error of not being able to match correctly -
https://github.com/tebelorg/RPA-Python#rpa-for-python-snake
