### ISSUE TITLE
type() sometimes miss out first character at element? - pending replication details

### ISSUE THREAD

**Issue by freeforsong** [tebelorg/RPA-Python#305]
for example
I use 
`t.type("/html/body/main/input", "1234567890")`
but the text is show "234567890"?

**Comment by kensoh** [comment]
I haven't heard of this feedback from users before. Do you have a website where this happens?

My best guess is for that website, maybe the text field is partially loaded and once the tool detects that it is there it will start typing. But maybe the text box control is partially loaded and end up missing some text. You can try adding a r.wait() to intentionally wait for some time to see if that helps.

Or r.hover() on something that you know confirms that the webpage has been fully loaded. Before using type().

**Comment by freeforsong** [comment]
I see what you mean，It should be because the page has changed due to input， thinks for you help！

**Comment by freeforsong** [comment]
I see what you mean，It should be because the page has changed due to input， thinks for you help！
