### ISSUE TITLE
Error running sample web automation - use r.timeout(), looks like Google requires sign-in

### ISSUE THREAD

**Issue by AnuradhaVIyer** [tebelorg/RPA-Python#306]
I get the attached image when I run the RPA for Python. I checked the locale and it is set to LANG=en_US.UTF-8
[](url)
![image](https://user-images.githubusercontent.com/24716763/133840092-7dd16d96-681c-4145-8eb5-2ed4f112ec81.png)

**Comment by kensoh** [comment]
Hi @AnuradhaVIyer this is probably Google requiring you to sign in before allow you to browse it.

You can add r.timeout(300) to wait up to 5 minutes while you sign into the website -

```py
r.init()
r.timeout(300)
r.url('https://www.google.com')
r.type('//*[@name="q"]', 'decentralization[enter]')
print(r.read('result-stats'))
r.snap('page', 'results.png')
r.close()
```
