### ISSUE TITLE
An error occurred in the method snap - can't replicate, pending replication details

### ISSUE THREAD

**Issue by freeforsong** [tebelorg/RPA-Python#307]
In mac os，the tagui open the chrome  browser in default size，then the  method snap(xpath,path) is right. 
But ,when i maximize the chrome browser, the method snap(xpath,path)  will Intercept the wrong area？
it only happens in snap(xpath,path)  ,like this 
`t.snap("/html/body/div[2]/div/div[3]/div[2]/div","/Users/apple/test.png")`
 if use snap('"page",path), it can work. 
How to avoid this problem？

**Comment by kensoh** [comment]
Hi @freeforsong, I was not able to replicate. When I run the following in Python interactive terminal, the before and after images are ok.

```
import rpa as r
r.init()
r.url('https://www.google.com')
r.snap('//*[@name="q"]', 'before.png')
# maximise Chrome browser here
r.snap('//*[@alt="Google"]', 'after.png')
r.close()
```

**Comment by kensoh** [comment]
before
![before](https://user-images.githubusercontent.com/10379601/133964216-727ea428-462b-433b-af4e-b76973ce3700.png)

after
![after](https://user-images.githubusercontent.com/10379601/133964220-dfb8850b-ab4f-4ab3-aafd-ee7a0c49ee82.png)

**Comment by kensoh** [comment]
By maximising I mean adjust window size to larger to fill up the screen. However the zoom level I left it the same as 100%.

Changing zoom levels will cause snap or click step to fail, because the coordinates system would be mess up to automate.
