### ISSUE TITLE
Is there a solution to this problem now - see this solution for restricted network / internet

### ISSUE THREAD

**Issue by wuhao5925968** [tebelorg/RPA-Python#310]
[RPA][INFO] - setting up TagUI for use in your Python environment
[RPA][INFO] - downloading TagUI (~200MB) and unzipping to below folder...
[RPA][INFO] - C:\Users\HP\AppData\Roaming
[RPA][INFO] - done. syncing TagUI with stable cutting edge version
[RPA][ERROR] - failed downloading from https://raw.githubusercontent.com/tebelorg/Tump/master/TagUI-Python/tagui...

**Comment by Lamarche-Lam** [comment]
> [RPA][INFO] - setting up TagUI for use in your Python environment
> [RPA][INFO] - downloading TagUI (~200MB) and unzipping to below folder...
> [RPA][INFO] - C:\Users\HP\AppData\Roaming
> [RPA][INFO] - done. syncing TagUI with stable cutting edge version
> [RPA][ERROR] - failed downloading from https://raw.githubusercontent.com/tebelorg/Tump/master/TagUI-Python/tagui...

Try modify the init() function in tagui.py. You might want to use os.path.isfile('path to the file') to skip the download of the existing files. After that call r.init() until the the tagui for python environment is ready.

**Comment by wuhao5925968** [comment]
I don't understand what you mean

> > [RPA][INFO] - 设置 TagUI 以在您的 Python 环境中使用
> > [RPA][INFO] - 下载 TagUI (~200MB) 并解压到以下文件夹... 
> > [RPA][INFO] - C:\Users\HP \AppData\Roaming 
> > [RPA][INFO] - 完成。将 TagUI 与稳定的尖端版本同步
> > [RPA][错误] - 从https://raw.githubusercontent.com/tebelorg/Tump/master/TagUI-Python/tagui下载失败...
> 
> 尝试修改tagui.py 中的init() 函数。您可能希望使用 os.path.isfile('path to the file') 跳过现有文件的下载。之后调用 r.init() 直到 python 环境的 tagui 准备好。

I don't understand what you mean

**Comment by kensoh** [comment]
See this thread with the same issue on company network blocking automatic downloading from certain GitHub endpoints -

https://github.com/tebelorg/RPA-Python/issues/287#issuecomment-888735714

**Comment by Lamarche-Lam** [comment]
> I don't understand what you mean
> 
> > > [RPA][INFO] - 设置 TagUI 以在您的 Python 环境中使用
> > > [RPA][INFO] - 下载 TagUI (~200MB) 并解压到以下文件夹...
> > > [RPA][INFO] - C:\Users\HP \AppData\Roaming
> > > [RPA][INFO] - 完成。将 TagUI 与稳定的尖端版本同步
> > > [RPA][错误] - 从[https://raw.githubusercontent.com/tebelorg/Tump/master/TagUI-Python/tagui下载失败](https://raw.githubusercontent.com/tebelorg/Tump/master/TagUI-Python/tagui%E4%B8%8B%E8%BD%BD%E5%A4%B1%E8%B4%A5)...
> > 
> > 
> > 尝试修改tagui.py 中的init() 函数。您可能希望使用 os.path.isfile('path to the file') 跳过现有文件的下载。之后调用 r.init() 直到 python 环境的 tagui 准备好。
> 
> I don't understand what you mean

Sorry that I cannot talk you through this in a lucid way. Since you used the translator, I assumed that Chinese makes more sence to you so allow me to explain it in Chinese:
当您使用 r.init() 的时候它会自动检测您计算机上是否存在支撑这个网页自动化的js, php, py, cmd(windows 下) 文件，它会自动下载这些所需的文件。由于网络的原因，这个连接到GitHub下载服务的服务器在我们这很不稳定，所以很容易在下载所需文件的时候被迫终止。
这会导致您一直重复运行r.init()去下载这些文件。

如果您一直没有成功完成过r.init()这个过程的话，tagui.py(init() 函数所在的py文件) 前面设定了解压文件的语句会在每次解压的时候覆盖之间您下载过的所需文件，进而导致整个过程重复。

所以我当时提的建议是在tagui.py 每次需要下载的文件时加上一个 os.path.isfile(‘所需文件.文件后缀')的判断，如果不存在才下载从而来推进r.init()的完成。但是这样子很容易导致未完成的文件损坏，所以这是个野路子。

作者 @kensoh 给您提出的 #287 (comment) 应该能更好的解决您的问题，您可以先试试他的方法。
