### ISSUE TITLE
How use proxy? - set from Chrome using visual and keyboard automation

### ISSUE THREAD

**Issue by BlondinkaQ** [tebelorg/RPA-Python#312]
r.url('https://2ip.ru/', proxy = "http://160.116.88.224:3128")

**Comment by kensoh** [comment]
Hi @BlondinkaQ for setting proxy, the underlying browser is Chrome. You can use [visual automation](https://github.com/tebelorg/RPA-Python#visual-automationsee_no_evil) and [keyboard automation](https://github.com/tebelorg/RPA-Python#keyboard-automationmusical_keyboard) to control Chrome to set the proxy using the same steps as you would set them manually (from Chrome Settings --> proxy).
