### ISSUE TITLE
I can't download TagUI - company network policy does not allow access, try this

### ISSUE THREAD

**Issue by HeliangCN** [tebelorg/RPA-Python#318]
sorry，I've got a problem at the beginning。The console output is as follows：

`D:\workspace\pythonProject\RPA-Python-1.45.0\venv\Scripts\python.exe D:/workspace/pythonProject/RPA-Python-1.45.0/sample.py
[RPA][INFO] - setting up TagUI for use in your Python environment
[RPA][INFO] - downloading TagUI (~200MB) and unzipping to below folder...
[RPA][INFO] - C:\Users\hel\AppData\Roaming
[RPA][INFO] - done. syncing TagUI with stable cutting edge version
[RPA][ERROR] - failed downloading from https://raw.githubusercontent.com/tebelorg/Tump/master/TagUI-Python/tagui...
<urlopen error [WinError 10054] 远程主机强迫关闭了一个现有的连接。>
[RPA][ERROR] - use init() before using url()
[RPA][ERROR] - use init() before using type()
[RPA][ERROR] - use init() before using read()

[RPA][ERROR] - use init() before using click()
[RPA][ERROR] - use init() before using snap()
[RPA][ERROR] - use init() before using snap()
[RPA][ERROR] - use init() before using url()
[RPA][ERROR] - use init() before using type()
[RPA][ERROR] - use init() before using snap()
[RPA][ERROR] - use init() before using close()

Process finished with exit code 0
`

**Comment by hyfkin** [comment]
you can use this url “https://gitee.com/rongzhi-space/TagUI/tree/master/src/” to download those files  or you can find that in TagUI from github
