### ISSUE TITLE
How to make the script beat after this error? - use if condition with init()

### ISSUE THREAD

**Issue by BlondinkaQ** [tebelorg/RPA-Python#322]
how to make the script beat after this error?
write me a sample script
try exept and if else not workig

```
[RPA][ERROR] - following happens when starting TagUI...

The following command is executed to start TagUI -
"C:\Users\Administrator\AppData\Roaming/tagui/src/tagui" rpa_python chrome

It leads to following output when starting TagUI -

START - automation started - Wed Oct 27 2021 05:52:50 GMT-0700 (Pacific Daylight Time)

LIVE MODE - type done to quit
```

**Comment by fi-do** [comment]
Hey @BlondinkaQ,

I try to understand your issue. Can you give a specific example that provokes this error? Normally this happens when the tagui process isn't working anymore.

Best regards,
fi-do

**Comment by BlondinkaQ** [comment]
@fi-do  
just occurs from time to time on windows, after restart everything works again and I can't pass it through try except

**Comment by kensoh** [comment]
Adding on, one way is to do error checking this way, since init() returns False if anything goes wrong during initialisation -

```
if not r.init():
    # do what you want on error initialising
```

**Comment by kensoh** [comment]
Adding on further, from above error message it looks like sometimes on your PC, after the TagUI process runs it dies, thus the Python process cannot "latch" onto it to control the process.

**Comment by kensoh** [comment]
Lastly, linking to a related enhancement issue to improve the error handling of the package - https://github.com/tebelorg/RPA-Python/issues/299

**Comment by kensoh** [comment]
Closing issue for now but please let me know if you run into any problem or new info!
