### ISSUE TITLE
Unable to load script rpa_python.js, user access permission issue - pending checks

### ISSUE THREAD

**Issue by qhaliff39** [tebelorg/RPA-Python#323]
Hi @kensoh, I am having trouble with this error on a particular Windows 10, 64 bit laptop that I have installed the automation on. The error output is as follow;

[RPA][ERROR] - following happens when starting TagUI...

Unable to load script C:\DND Automation\rpa_python.js; check file syntax

  phantomjs://code/bootstrap.js:113 in __die

[RPA][ERROR] - use init() before using url()
[RPA][ERROR] - use init() before using type()
[RPA][ERROR] - use init() before using type()
[RPA][ERROR] - use init() before using click()
[RPA][ERROR] - use init() before using url()
[RPA][ERROR] - use init() before using type()
[RPA][ERROR] - use init() before using type()
[RPA][ERROR] - use init() before using type()
[RPA][ERROR] - use init() before using type()
[RPA][ERROR] - use init() before using type()
[RPA][ERROR] - use init() before using click()
[RPA][ERROR] - use init() before using click()

Troubleshoots that I have done;

1. Installed 2010,2013 and 2015 redistributable packages. Still produced error.
2. Tried to install my app on other drives, D drive and on desktop as well, but still producing error.

Out of all 3 laptops that I have installed the app on, only 1 laptop has this issue.

Can you help me? i've been wrecking by brain to solve this.

**Comment by fi-do** [comment]
Hey @qhaliff39,

I can not recreate the issue. But try to execute your script in a path without any blanks.
For example rename DND Automation in DND_Automation.

Best regards,
fi-do

**Comment by farukaf** [comment]
Hi @qhaliff39 did you find any solution? Got the same problem in one pc without apparent reason.

**Comment by BeanHhb** [comment]
Hi all, I meet the same problem. Try 3 laptops only one laptop has this problem. All laptops are win10 64.

**Comment by kensoh** [comment]
Hi Guys, is this still an issue? Here are 2 things to check -

1. Install vcredist_x86.exe from https://www.microsoft.com/en-us/download/details.aspx?id=30679 (if this is missing, there should be an error message on initial installation to prompt user to install this file)

2. Check that the folder you are running the automation is a folder which you have write access to, for example use your Windows Desktop folder where the current user has write access to
