### ISSUE TITLE
Maximize chrome window - try changing the configuration at tagui_config.txt

### ISSUE THREAD

**Issue by JoaoAuvs** [tebelorg/RPA-Python#324]
is there any way to maximize the chrome window without using the keyboard or without the pyautogui?

**Comment by fi-do** [comment]
Hey @JoaoAuvs,

see #325

Best regards,
fi-do

**Comment by kensoh** [comment]
Adding on, another idea is editing the configuration file of the Chrome window size.

On Windows, check the %APPDATA% folder. Inside it, check for tagui folder, then src folder.

Edit the tagui_config.txt file and change the width and height to the values you want.

**Comment by kensoh** [comment]
Closing issue for now but please let me know if you run into any problem or new info!
