### ISSUE TITLE
Problem with maximizing Chrome and starting the URL - pending more details

### ISSUE THREAD

**Issue by JoaoAuvs** [tebelorg/RPA-Python#325]
When I try to maximize chrome it's maximized the notification screen.
Another problem I'm having is on chrome startup the url loading process is taking a long time even with turbo_mode activated.

![image](https://user-images.githubusercontent.com/58301591/140553271-f847aea8-c778-4c62-b71d-de1af1ffbc79.png)

**Comment by fi-do** [comment]
Hey @JoaoAuvs,

if you are using a Windows based operating system you can use the win32gui library.
[One example](https://stackoverflow.com/questions/2790825/how-can-i-maximize-a-specific-window-with-python)

Hope I was able to help you,
fi-do

**Comment by kensoh** [comment]
Adding on, you may need to do a r.click() on the Chrome browser to make sure it is in the foreground and is the active window, before you use r.keyboard() shortcut to maximise the window. For URL loading, there is some initial delay of a few seconds to open Chrome browser, run TagUI process in the background, and load the URL.

**Comment by kensoh** [comment]
Closing issue for now but please let me know if you run into any problem or new info!
