### ISSUE TITLE
How to change Chrome download directory using helper Function?

### ISSUE THREAD

**Issue by Mavericks334** [tebelorg/RPA-Python#329]
Hi @kensoh 

For the TAG UI there as a helper function to change the download folder locations based on this issue

[https://github.com/kelaberetiv/TagUI/issues/1035]

Is there something similar for the python version as well. r.download_folder() does not work

Regards,
Renato.

**Comment by fi-do** [comment]
Hey @Mavericks334,
with rpa  v1.41 you can set the default download directory via:
`r.download_location('/home/fido/PycharmProjects/test')`
Also you can check the actual download folder with:
`default_location = r.download_location()`
If you don't want to change your default directory, you can download the file directly to your destination:
`r.download("https://pics.de/picture.png", "/tmp/my_picture.png")`

I hope I was able to help you,
fi-do

**Comment by Mavericks334** [comment]
@fi-do thank you.
