### ISSUE TITLE
Call to r.snap() waits till a tab is clicked - pending more details and exploration

### ISSUE THREAD

**Issue by pachakra** [tebelorg/RPA-Python#330]
I am very new to RPA-Python. I am facing a problem where a call to snap() waits till I have clicked a tab. I wanted to know how I can fix this and run the flow without having to click on the tab.
 
I am trying to run a simple use case where I do the following.

1. Open a URL
2. Open another URL in a new tab
3. Search something in the first tab
4. Take a snapshot of the first tab
5. Switch to the second tab
6. Search something in the second tab
7. Take a snapshot of the second tab

The problem I am facing is that on step 4 - the call to snap() waits till I have clicked on the first tab. And then the code starts moving again : 
```python
import rpa as r

r.debug(True)
r.init()
r.url('https://duckduckgo.com/'>) 
r.wait()
r.dom('window.open("' + 'https://www.google.com' + '")') 
r.wait()
r.popup()  #Because I want the tab with first URL to be active
r.type('//*[@id="search_form_input_homepage"]', r'r.popup')
r.click('//*[@id="search_button_homepage"]')
r.wait()
r.snap('page', r'D:/URL1.png') #This is where the code stops. At this point, 
                               #if I click the tab for the first URL
                               #the snap() function returns

r.popup(r'google.com')
r.type('q', r'r.popup')
r.wait()
r.click('btnK')
r.wait()
r.snap('page', r'D:/URL2.png')
r.close()
```
I am using rpa version '1.45.0' on Python 3.6.5 on Windows 10 Pro.

A  little digging into the code showed that snap() calls send() which in-turn has the following line:
"while _tagui_started and not _ready(): pass"
I tried debugging and this is where the code waits until I click on the first tab (Looks like tagUI spits out something like, "[RPA][18] - listening for inputs" which causes _ready() to return True and break from the loop), but I have no idea why this is happening.

If I run in headless mode there is no problem. The code does what it is supposed to do.
If I open only one URL the snap works nicely. 

Any pointers on what I am doing wrong and how to fix this ?

**Comment by kensoh** [comment]
Hi @pachakra sorry for my very late reply! Was away for months. Did you manage to find a solution?

I believe a possible reason could be during visible mode, when the tab is not active it does not render and could not return the snap binary data back. An idea I can think of is using keyboard() to tab to switch tab, or use visual automation to click on the tab you want. You can try if that works for you. Or perhaps run in headless mode to achieve the automation.

**Comment by pachakra** [comment]
Hi @kensoh - thanks much for the response. As I mentioned (and you suggested as well) running in headless mode works, so I am using that for now. I did try adding keyboard() to switch to the tab but had the same problem. Something like this
`r.keyboard('[ctrl][shift][tab]')`
I was more curious about the behaviour when headless was set to False. Since I am not blocked for now I will close this.

**Comment by kensoh** [comment]
Hi @pachakra, sure. Thanks for your feedback. It is probably some limitation in Chrome rendering, I can replicate it.
