### ISSUE TITLE
TagUI closing without any apparent errors - pending more details and update

### ISSUE THREAD

**Issue by manishdash12** [tebelorg/RPA-Python#331]
Hi,

I am using the rpa-python to run some visual automation tasks. The task runs fine all on its own. 
But sometimes after long times (like 1-1.5 hours), everything suddenly crashes. 

When the crash happens, the sikuli terminal and the chrome browser both shuts down.

**tagui.log**
```
...
...
...
[tagui] INPUT  - [3899] vision region = Region(880,387,42,39)
[tagui] ACTION - region = Region(880,387,42,39)
[tagui] OUTPUT - [3899] SUCCESS

[tagui] INPUT  - [3900] vision pattern = Pattern("abc2.png").similar(0.9)
[tagui] ACTION - pattern = Pattern("abc2.png").similar(0.9)
[tagui] OUTPUT - [3900] SUCCESS

[tagui] INPUT  - [3901] vision ans = region.exists(pattern)
[tagui] ACTION - ans = region.exists(pattern)
[tagui] OUTPUT - [3901] SUCCESS

[tagui] FINISH - stopped listening
IDE terminated: returned: 0
```

**rpa-python warnings**
```
[RPA][ERROR] - TagUI process ended unexpectedly
[RPA][ERROR] - use init() before using vision()
[RPA][ERROR] - use init() before using vision()
[RPA][ERROR] - use init() before using vision()
[RPA][ERROR] - use init() before using vision()
[RPA][ERROR] - use init() before using vision()
[RPA][ERROR] - use init() before using vision()
```

**Comment by manishdash12** [comment]
On further investigation, I see that `finish` is coming as an intent in the 'tagui.sikuli/tagui_sikuli.in' file for some reason.  

I will try tracking why this is sent by the rpa-python as an intent

**Comment by kensoh** [comment]
Hi @manishdash12 sorry for being away for a long time! Have you found a solution for this issue?

Normally, `finish` is sent by the TagUI process if the rpa package `close()` function is called.

However, there could be unexpected or unknown reasons why `finish` is sent from TagUI process.

**Comment by kensoh** [comment]
Closing issue for now but please let me know if you run into any problem or new info!
