### ISSUE TITLE
count() function doesn't seem to be working - seeking details and findings

### ISSUE THREAD

**Issue by chooimail** [tebelorg/RPA-Python#334]
Hi,

I've included several attachments.
I've basically tried TagUI first, as it is... and was able to get results.

So I'm now looking further into creating flows using RPA for Python, which is essentially writing the flow file in Python code/language (which I'm new to it as well).
Thus, I'm using a working *.tag flow as my reference/sample to replicate my own results using RPA for python.

**BUT, unable to achieve them.
Particularly on the .count() function.**

Attached inside the ZIP file are 3 files.
1. Working *.tag flow
2. Python script that is unable to achieve the .count() results
3. A screenshot showing the different results, counting the same element identifier from the same web page

Thank you.

Regards,
Chooi
[rpa count_does not work.zip](https://github.com/tebelorg/RPA-Python/files/7653258/rpa.count_does.not.work.zip)

**Comment by kensoh** [comment]
Hi @chooimail sorry for my slow reply was away for months! Can I check with you if you have found a solution?

Yes you are right that the code should be directly portable from TagUI to rpa package. There are some small differences for Python version but it should work in the same way for identifying and counting elements. Let me know more your findings.

**Comment by chooimail** [comment]
Hi @kensoh 

No worries, I also forgot about it.
Hence I did some testing again just now, also with other web pages.

**Solution:**
- Add a wait for the page to load, then execute the count() function

It's just a little weird that TagUI flow did not need it, while the Python script needed it.
Despite executing both flows from the same hardware, internet connection, etc...
Perhaps the browser's cache played a small part as well.

Anyway, thanks for the reminder of the "problem".
Good to know the solution as well.

**Comment by kensoh** [comment]
Using above, you will be able to make sure that the page has finished loading before using count. The difference in behaviour could be due to system performance difference in running additional Python process. Other than that, there should be negligible difference in the rpa package and TagUI.

**Comment by kensoh** [comment]
Closing issue for now but please let me know if you run into any new issue related to this!
