### ISSUE TITLE
Chinese language OCR automation results code errors - pending more details

### ISSUE THREAD

**Issue by yangyuke001** [tebelorg/RPA-Python#336]
hi @kensoh ，
Thank u for your work!
I got some mistakes when use OCR AUTOMATION recognition Chinese language:

```
r.init(visual_automation = True, chrome_browser = False)
print(r.read('Chinese_language.png'))
```
and I got 'ï¬ï¬ï¬ï¬ï¬' as output.
what should I do ?

Best regards!

**Comment by kensoh** [comment]
Hi @yangyuke001 sorry I was away for very long! Can you tell me more if you have found a solution?

It might be due to need to set up Chinese OCR language in the Tesseract subsystem used by the package.

**Comment by kensoh** [comment]
In the meantime, cross-linking to a solution tested on TagUI project - https://github.com/kelaberetiv/TagUI/issues/1215#issuecomment-1110529037

**Comment by kensoh** [comment]
Closing issue for now until further inputs, or reports from other users. But please let me know if anything!
