### ISSUE TITLE
Jython not found error message - use r.pack() to copy from own PC to intranet

### ISSUE THREAD

**Issue by BeanHhb** [tebelorg/RPA-Python#338]
Hi Ken,
I have made a demo. But it comes this error when run in other laptop.
![image](https://user-images.githubusercontent.com/55520057/147022783-e13e2418-d42b-42d0-9e98-84f1ad9df99a.png)
The tagui folder is copied from my laptop. I have to copy and paste the tagui folder to other laptop because of  the chinese network wall.
So i want to know if any way to auto-install jython at the first run time of visual automation, as like as kelaberetiv/TagUI#899.
tks.

**Comment by kensoh** [comment]
Hi @BeanHhb I see... Oh on first run, the Jython file will be auto-moved to a user folder, so you cannot copy the whole directory over like that. Instead, for firewall issues, you can use r.pack() to generate a zip to copy to company intranet. For future updates of the package you can use r.update() to generate a .py file to copy to intranet.
