### ISSUE TITLE
How to select ul>li element? r.select() not work.... - some ideas to explore

### ISSUE THREAD

**Issue by aliveoscard** [tebelorg/RPA-Python#339]
<img width="290" alt="屏幕截图 2021-12-29 091209" src="https://user-images.githubusercontent.com/77272275/147618341-769c96fc-faeb-459d-8e8d-12344da34fb4.png">
<img width="320" alt="屏幕截图 2021-12-29 091300" src="https://user-images.githubusercontent.com/77272275/147618347-5d311ba0-413a-4f8c-aedb-87ffd41b28ae.png">

**Comment by kensoh** [comment]
Hi @aliveoscard is this resolved? For the select() function, for a given selector, the options value or text can be used to do the selection. Alternatively, you can try doing click() to activate the dropdown and click() to choose the option.

**Comment by aliveoscard** [comment]
> Hi @aliveoscard is this resolved? For the select() function, for a given selector, the options value or text can be used to do the selection. Alternatively, you can try doing click() to activate the dropdown and click() to choose the option.

I try it,thanks for your help!
