### ISSUE TITLE
How to activate a page? - some thoughts to explore, or use visual automation

### ISSUE THREAD

**Issue by rmrao-peruri** [tebelorg/RPA-Python#340]
I want to open a page (https://www.nseindia.com/all-reports), click a link [bhavcopy file (csv)] and download the file.
Attaching the Jupytr notebook for your reference
The downloadNseEodPrice function fails to download the file unless I navigate to the Chrome opened by RPA and click on the page.
Surprisingly the call to input is successful though the hello text is not visible on the browser

I am sure I am making some silly mistake.  Can you pls help?

[nseDownload.txt](https://github.com/tebelorg/RPA-Python/files/7798899/nseDownload.txt)

**Comment by kensoh** [comment]
Hi @rmrao-peruri is this still an issue? Could you try copying all the Jupyter notebook code into a .py file and see if it happens? Do also paste the code here and let me try to replicate if it also happens on my computer.

Sounds like it might be the webpage has some logic that only allows download to happen if a user is really focusing on the browser and not through automation. We'll see.. In any case, there are alternative methods like using visual automation which can simulate a real user's actions and should be able to get around that.

**Comment by kensoh** [comment]
For example, something like `r.click('chrome_icon.png')` can be used to click on the Chrome icon to bring it to foreground.
