### ISSUE TITLE
Does RPA work in WSL2 Ubuntu - it should, try installing PHP to see if it helps

### ISSUE THREAD

**Issue by PurnaChandraPanda** [tebelorg/RPA-Python#342]
I tried the sample in ubuntu, but received like the following error. Any thoughts on this??

```
[RPA][ERROR] - following happens when starting TagUI...

The following command is executed to start TagUI -
"/home/udev/.tagui/src/tagui" rpa_python

It leads to following output when starting TagUI -
/home/udev/.tagui/src/tagui: line 256: php: command not found
Unable to open file: /work/rpa-stuff/samples/rpa_python.js

  phantomjs://code/bootstrap.js:113 in __die
Unable to load script /work/rpa-stuff/samples/rpa_python.js; check file syntax

  phantomjs://code/bootstrap.js:113 in __die
```

**Comment by kensoh** [comment]
Yes the package works with Linux Ubuntu. However, some Linux versions does not come with PHP.

Try installing PHP on your Ubuntu and see if that helps. Please let me know how that goes!

**Comment by kensoh** [comment]
If it still does not work, try running directly on your Windows instead of the WSL2 Ubuntu, and let me know if that works.
