### ISSUE TITLE
Support on Windows 11, "Unable to load script error" - try this to see if it helps

### ISSUE THREAD

**Issue by PurnaChandraPanda** [tebelorg/RPA-Python#343]
I have python (latest: 3.10.*) installed on my windows 11. Then, have the rpa installed. I tried to invoke the sample.py in repo from my machine, I could not.

Could you please on check on windows if works or we need to follow steps differently? Your readme talks about mac usage only.

```
D:\work\practice\rpa-stuff\samples>python web-search.py
[RPA][ERROR] - following happens when starting TagUI...

The following command is executed to start TagUI -
"C:\Users\pupanda\AppData\Roaming/tagui/src/tagui" rpa_python

It leads to following output when starting TagUI -
Unable to load script D:\work\practice\rpa-stuff\samples\rpa_python.js; check file syntax

  phantomjs://code/bootstrap.js:113 in __die
```

**Comment by kensoh** [comment]
Hi @PurnaChandraPanda, this may be due to a dependency of the PHP used by the package missing.

There is self-check during initial setup, which you might have missed the following message.

Try installing manually the vcredist_x86.exe file from below link, to see if that helps.

```
[RPA][INFO] - MSVCR110.dll is still missing, install vcredist_x86.exe from
[RPA][INFO] - the vcredist_x86.exe file in your_directory\tagui or from
[RPA][INFO] - https://www.microsoft.com/en-us/download/details.aspx?id=30679
[RPA][INFO] - after that, TagUI ready for use in your Python environment
```

**Comment by kensoh** [comment]
Hi @jamontesg can you try from below link and install the x86 version? Because the PHP dependency is 32-bit PHP and won't work with 64-bit one. That's the most likely error. 

https://www.microsoft.com/en-us/download/details.aspx?id=30679

**Comment by jamontesg** [comment]
perfect  @kensoh.  
Using  **X86** version  solve  the issue.
Thanks for your time

**Comment by kensoh** [comment]
Welcome @jamontesg!
