### ISSUE TITLE
How is this better or different from Selenium? - more features and easier to use

### ISSUE THREAD

**Issue by slim-python** [tebelorg/RPA-Python#344]

**Comment by kensoh** [comment]
Hi @slim-python, this Python rpa package is much more. It is the equivalent of Selenium (web automation) + PyAutoGUI (desktop, keyboard, mouse automation) + Tesseract (OCR) + Telegram notifications (free server provided).

Also, its smart selector system coupled with minimal user friction will let any user create web automation in a fraction of the time and lines needed for Selenium. You can try it, will be liberating!
