### ISSUE TITLE
I wonder how to input complex key stroke.. - see this and API pro functions section 

### ISSUE THREAD

**Issue by unique0ne0** [tebelorg/RPA-Python#345]
Hi. 
I am trying to automate one of windows application using visual automation function.
During the processes, that application shows popup window twice.
Anyway most of things are very nice, but after finishing processes I need to go back to main window.
I have read an article that Tag UI doesn't have function to handle window id and try to use image click or key input [alt][tab].
In my case, I need to go back two steps so I want to input [tab] twice with [alt] key down.
How can I do this?

**Comment by kensoh** [comment]
Hi @unique0ne0 you can try if any of the following work for you.

I'll probably do using 2 lines. You can see the shortcuts in API section.

```
r.keyboard('[alt][tab]')
r.keyboard('[alt][tab]')
```
or
```
r.keyboard('[alt][tab][tab]')
```

**Comment by unique0ne0** [comment]
Thanks.
I realized this kind of solution by key strokes to go back main window might be disturbed from unexpected popup by other application in my case.
And I have found another better solution. 
It was using r.vision('switchApp("myApp")') or r.vision('myApp.focus()').
It works exactly as I wanted and it can be helpful to someone.

**Comment by kensoh** [comment]
Oh @unique0ne0 this is a nice tip, thanks for sharing back here!
