### ISSUE TITLE
How to run specific task in windows task scheduler desktop app - pending info

### ISSUE THREAD

**Issue by radhakrishr36** [tebelorg/RPA-Python#346]
Is it possible to run the window task scheduler via RPA python. This is the piece of code i am using. 
This code not working after the  **r.keyboard('task Scheduler Library[click]')** line . Kindly help me to resolve the issues.

import rpa as r
r.init(visual_automation = True, chrome_browser = False)
r.keyboard('[win]')
r.keyboard('task Scheduler[enter]')
r.wait(2.5)
r.keyboard('task Scheduler Library[click]')
r.wait(2.5)
r.keyboard('[tab]')
r.keyboard('[down]')
r.keyboard('[down]')
r.keyboard('[down]')
r.keyboard('[down]')
r.keyboard('RPA_Automation_Testing[click]')
r.keyboard('RPA_Automation_Testing[rclick]')
r.keyboard('Run[enter]')
r.wait(2.5)
r.snap('page.png', 'results.png')
r.close()

**Comment by kensoh** [comment]
Hi @radhakrishr36 below is an invalid command. For the keyboard() function, `[]` means special keys. And there is no special `[click]` keys like `[tab]`,`[win]` etc. You can probably try using visual automation to click on the app.

```
r.keyboard('task Scheduler Library[click]')
```

See examples and notes here -
https://github.com/tebelorg/RPA-Python#visual-automationsee_no_evil
https://github.com/tebelorg/RPA-Python#element-identifiers

**Comment by radhakrishr36** [comment]
Hi @kensoh,

Thanks for the update.

I changed the code now it's working in my windows machine. but the same code not working in windows server 2012 r2. I am connecting the server via RDP. 

The server machine had  python 3.6 and java jdk 1.8.11. I tested sample web automation script it's working fine  but this desktop automation not working.

It's not throw any error but same time  not working the click option.

Kindly help me to resolve the issues. these the code snippet for your reference.

import rpa as r
r.init(visual_automation = True, chrome_browser = False)
r.keyboard('[win]')
r.keyboard('task Scheduler[enter]')
r.wait(2.5)
r.click('task_scheduler.png')
r.wait(2.5)
r.click('name.png')
r.wait(10)
r.hover('RPA_automation.png')
r.click('RPA_automation.png')
r.wait(2.5)
r.click('run.png')
r.snap('page.png', 'results.png')
r.close()

![1](https://user-images.githubusercontent.com/45685274/151963566-1e05fcd5-129d-4438-b270-e44b2f7d31b9.png)
![2](https://user-images.githubusercontent.com/45685274/151963575-a0b7f718-8261-49ee-9e19-18d579964daf.png)
![3](https://user-images.githubusercontent.com/45685274/151963577-dd64e103-e290-41a9-a3a5-f0096f814f3e.png)
![name1](https://user-images.githubusercontent.com/45685274/151963583-e06dab7c-329d-480e-8ab5-61b9d106e255.png)

**Comment by kensoh** [comment]
Hi @radhakrishr36 the visual automation method requires an active session to the remote desktop, so that the display is rendered and visual matching can be done. Is there an active session? If there is, the next to check is the logs.

Go to %APPDATA% folder, look inside tagui folder, src folder, tagui.sikuli folder. Then share the logs here?

**Comment by kensoh** [comment]
Closing issue for now but please let me know if you run into any problem!
