### ISSUE TITLE
Are XPath functions supported - probably usage issue, yes see this example

### ISSUE THREAD

**Issue by ewan-chalmers** [tebelorg/RPA-Python#348]
I am trying to get the `id` attribute of an iframe so I can use that in `frame()`

This xpath correctly extracts the `id` attribute value in Chrome console
```
'string(//iframe[@title="Application List"]/@id)'
```

But when I try to use it in RPA-python...
```
    frame_id = r.read('string(//iframe[@title="Application List"]/@id)')
```

... I get not found
```
[RPA][ERROR] - cannot find string(//iframe[@title="Application List"]/@id)
```

I am wondering if xpath functions like `string` are not supported?

**Comment by kensoh** [comment]
Hi @ewan-chalmers yes XPath is supported. The correct syntax is below, without the additional string() function -

```
frame_id = r.read('//iframe[@title="Application List"]/@id')
```

**Comment by kensoh** [comment]
Adding on, I'm not sure what is XPath function like string(). 

From Google home page - https://www.google.com/

I can find `//*[@name="q"]` from the Chrome web inspector.

But searching for `string(//*[@name="q"])` shows no result.

**Comment by ewan-chalmers** [comment]
Thank you Ken. That was too obvious :(

**Comment by ewan-chalmers** [comment]
What I found was that `string()` is typically used to extract just the value of an attribute; xpath would otherwise return the attribute itself (name and value object I suppose)

See this check on Google page

```
$x('/html[@itemtype]/@itemtype')
[itemtype]
$x('string(/html[@itemtype]/@itemtype)')
'http://schema.org/WebPage'
```

![image](https://user-images.githubusercontent.com/14384447/150104924-483665fa-06ab-4df2-a873-dad44273eead.png)

**Comment by kensoh** [comment]
My guess is string() is part of the XPath expression supported by $x but is not standard XPath syntax definition. That's why when you search for `string(/html[@itemtype]/@itemtype)` in the web inspector (the HTML view) there is no result.

**Comment by kensoh** [comment]
In above case, $x returns objects while string() returns the value. But for the Python package, no objects are returned. And for read step, it will automatically be returned as a string. This is because in above example you are debugging within Chrome, the concept of object exists. But once you are in Python, there is no way to "pass" an object back to Python from Chrome. They exist in different programming process (1 in JavaScript HTML DOM in Chrome, 1 in Python process).
