### ISSUE TITLE
RPA start speed - pending replication, may be related to computer speed

### ISSUE THREAD

**Issue by Juarezroncalli** [tebelorg/RPA-Python#349]
How do I speed up RPA start and run, it's taking 45 seconds to run a 1-click script.

**Comment by kensoh** [comment]
Hi @Juarezroncalli can you tell me more and share the sample script here?

For the first run, it will download TagUI engine (100+ MB), so it will take some time depending on your internet speed and the GitHub file server speed. For subsequent runs, this delay due to downloading won't be needed.

**Comment by Juarezroncalli** [comment]
See the script, it takes 37 seconds to run. I use pyautogui and it's practically instantaneous.

import rpa as r
r.init(visual_automation = True, chrome_browser=False)
r.click(1117, 20)

**Comment by kensoh** [comment]
I see.. In above example, you are using visual automation, that requires loading computer vision and OCR model into memory. This usually takes a few seconds, unless the computer is very slow hardware.

For PyAutoGUI I'm not sure how it handles computer vision. For this package it uses OpenCV and Tesseract.

**Comment by kensoh** [comment]
Can you try on another laptop to see if it is also very slow?

**Comment by Juarezroncalli** [comment]
ok i will try on another laptop!!
