### ISSUE TITLE
[enter] button doesn't work - keyboard automation needs visual_automation = True

### ISSUE THREAD

**Issue by anikalthh** [tebelorg/RPA-Python#350]
Original issue I posted under TagUI:
Why does this function output true but it actually doesn't press the enter button on the keyboard? Is there a workaround for this issue without having to use tagui's visual automation? I would like to use the python rpa package on its own. Would love some help as I've been stuck for quite long, thank you!

Your response: If there is [enter] string in the type function and you are using web identifiers, then it sends a \r key to Chrome, which is the key to mean enter.
For making real keyboard enter keys, you can use keyboard() function with [enter], or use visual automation of type step - type textbox.png as [enter]

Follow up questions after your initial response: I can't use the keyboard function without using TagUI's visual automation, is there another way? I want to utilise your Python RPA package on its own without visual automation. Thank you!

**Comment by kensoh** [comment]
Oh I see, I'm afraid to simulate actual keyboard functions will require `visual_automation = True`. This is because the engine (SikuliX) to do that is the same as the one used for visual automation and OCR. You can do keyboard actions with type() on websites, but special modifier keys are not supported. Desktop apps not supported too.

**Comment by anikalthh** [comment]
Hello, so if I were to install SikuliX for the keyboard function, I have to install Java as well (as seen on https://www.rpa-sg.org/TagUI/setting-up-sikuli-to-work-with-tagui-on-windows.php)?

**Comment by kensoh** [comment]
Yes I confirm that is the case, I'm afraid there is a Java requirement for that component.

See if you can use other Python packages instead that can meet the requirements.
