### ISSUE TITLE
Make web automation browser independent - not for test automation, not on roadmap

### ISSUE THREAD

**Issue by amoghkokari** [tebelorg/RPA-Python#352]
It does not support safari and brave browsers. As per the code coverage, I guess only Firefox and chrome is supported. 

We can have simple fix with taking the browser input from the user during init and map it to relevant directory to fetch the templates:

init("browser"="safari")

**Comment by kensoh** [comment]
Oh this package uses TagUI RPA engine, it is a custom-built engine for automating Chromium-based browsers. Thus other browsers are not supported. Also, this is not designed for test automation, so there is no support for Brave or Chromium out of the box. It is possible to make some config changes yourself to support Brave or Chromium, but the changes will be lost once you update the package to a new version/
