### ISSUE TITLE
How to change the current context without URL? - part of the URL is required, or try these

### ISSUE THREAD

**Issue by rzjorge21** [tebelorg/RPA-Python#353]
I need to download a PDF file that opens in other tab, the problem is that when I click the <a> tag, it has two attributes, href="#" and onClick="downloadFile('SCTR', 'P0028289', '7383782')". That function opens a second tab with other url but i can't change the context to download it or take a snap. (I'm not using visual automation)

Here is my code:
```
r.click('//*[@id="table_trabajadores"]/tbody/tr[1]/td[8]/a')  # this action opens a second tab
```

**Comment by kensoh** [comment]
I see.. Sounds like in this case the URL can't be found from the href attribute. In that case, you can explore -

1. using r.popup() to set the context to the PDF tab (provide some part of the URL that you know)
2. consider using visual automation mode, so you can simulate right click and save file directly

**Comment by kensoh** [comment]
You can also try using keyboard automation to [alt]tab to change to the new tab. And some other keyboard shortcuts to download the page.
