### ISSUE TITLE
Visual automation not working for me - pending some ideas to check why

### ISSUE THREAD

**Issue by NnamdiG** [tebelorg/RPA-Python#355]
So I'm trying to use TagUI for a project that I have and I'm testing the visual automation mode. Whenever I'm trying to double click a '.png' image on my desktop, instead it is just double clicking the text in my terminal. Any ideas why this is happening?

Thank you

<img width="563" alt="Screen Shot 2022-01-31 at 2 19 08 PM" src="https://user-images.githubusercontent.com/47512167/151866527-47e557a3-4ad6-4d47-9867-fa5f3ef7fecf.png">

**Comment by sadimoodi** [comment]
i am also facign the same issue, visual automation does NOT click the right button and throws an error:
[RPA][ERROR] - cannot find xyz.PNG

**Comment by kensoh** [comment]
Closing issue for now but please let me know if you run into any problem!
