### ISSUE TITLE
Current tab in the browser in not closing? - pending details, and some ideas

### ISSUE THREAD

**Issue by Mavericks334** [tebelorg/RPA-Python#356]
Hi @kensoh,

I'm trying to close the current active tab in the browser. using key board automation and it does not work. I tried using mouse co-ordinates as well. Nothing seems to work. Any suggestions how to close the site.

```
r.init(visual_automation = True,chrome_browser = True)
r.click(2390,18) # Mouse Pointer location
r.keyboard('[ctrl]w') # Keyboard.
```

Regards,
Ren

**Comment by kensoh** [comment]
Hi @Mavericks334 your code looks correct, can I confirm that below line brings the Chrome browser to the foreground?

```
r.click(2390,18)
```

Using [ctrl]w to close the browser requires it to be in the foreground before it works.

You could add a r.wait() after that line to see visually if the browser is really in the foreground.

**Comment by kensoh** [comment]
Closing issue for now but please let me know if you run into any problem!
