### ISSUE TITLE
Can r.read( ) only get one result? - yes, use for loop to read more items

### ISSUE THREAD

**Issue by IsBeatrice** [tebelorg/RPA-Python#357]
Hi @kensoh ,
We want to use the  r.read( )  to get multiple results of the same selector, but at present, it seems that we can only get the first selector element.
Can this function only read one result? Are there any alternative solutions? Or some alternative functions to achieve the same function?

Regards,
Ren

**Comment by ck81** [comment]
Suppose the xpath to the elements you're interested is: `//span[@class="a-price"]`

`(//span[@class="a-price"])[1]` will give you item1
`(//span[@class="a-price"])[2]` will give you item 2
`(//span[@class="a-price"])[3]` will give you item 3

If your xpath is not specific, then r.read() will only return the first one.

You can use the following to retrieve all the elements.  Note that xpath array starts from 1.

~~~
num_rows = r.count('//span[@class="a-price"]')
for n in range(1, num_rows+1):
    item = r.read(f'(//span[@class="a-price"])[{n}]')
    print(f"{n}. item = {item}")
~~~

**Comment by IsBeatrice** [comment]
Hi @ck81 ，
Thanks  for your answer which has helped us a lot!

We would like to ask you from which channel did you learn this usage? Did the author update the open source document on other platforms, but we didn't find it?

We would appreciate it if we could get your reply.

Regards,
Beatrice

**Comment by ck81** [comment]
Hi @IsBeatrice,

> We would like to ask you from which channel did you learn this usage? Did the author update the open source document on other platforms, but we didn't find it?

Don't worry.  This is actually the official site for RPA-Python, or previously called TagUI-Python.  This site contains the most complete documentation.  You did not miss anything.

One of the best thing about TagUI is that it supports the standard XPath.  Note that many of the RPA tools out there, even the commercial ones, do not support or only support a subset of the full XPath.  Some supports only CSS selectors.  XPath is a lot more powerful and easier to use than CSS selectors.

XPath is an industry standard defined by W3C.  As such, just google for "XPath tutorial".  You will find 2.4 million results returned by Google.  Pick anyone that you like.

If you do not know which one to pick, maybe you can start with the following: https://rpa-sg.org/TagUI/xpath-tutorial.php

Of course, I learned a lot of tips and techniques about xpath from StackOverflow, such as the following:
- xpath get element by index
https://stackoverflow.com/questions/10025221/xpath-get-element-by-index
- How to select the first element with a specific attribute using XPath
https://stackoverflow.com/questions/1006283/how-to-select-the-first-element-with-a-specific-attribute-using-xpath

> `r.read(f'(//span[@class="a-price"])[{n}]')`

If you are asking about the f-string.  This is a python thing.  Nothing to do with TagUI.  You can find more details here: https://www.geeksforgeeks.org/formatted-string-literals-f-strings-python/

Hope this helps.

Warm Regards,
/CK

**Comment by kensoh** [comment]
Thanks @IsBeatrice for raising this question, and @ck81 for the great (and perfect) solution!
