### ISSUE TITLE
It doesn't work to download file when using RPA-Python open a website with chrome browser

### ISSUE THREAD

**Issue by CabbageDu** [tebelorg/RPA-Python#358]
I use RPA-Python open a website with chrome browser.
There is a excel file on this website,when I click the file link，it begins to download.But  there is nothing to be  downloaded actually.
But when I Open webpage manually，and click the file link,it works.

Thanks for help!

**Comment by CabbageDu** [comment]
I can't download the file when I start the browser with Tagui or RPA-Python, but I can download it by manually opening the browser.

**Comment by CabbageDu** [comment]
It has been solved.The download path is not the default path,so I cannot open the file directly。

**Comment by kensoh** [comment]
Thanks @CabbageDu for sharing back your solution!
