### ISSUE TITLE
Use init() before using url() - check this, possibly network or permission issue

### ISSUE THREAD

**Issue by avi25070** [tebelorg/RPA-Python#360]
Hi,

First of all thank you @kensoh for creating this awesome tagui. i have an issue running python tagui with my office laptop, every time i execute it shows  **use init() before using url()  error**, it works good in my personal laptop, i have done some good automation in my personal laptop without any difficulties. I need it badly in my office laptop, since i have to automate certain task there.

Could you pls help me sorting out this issue. No space in path.
<img width="576" alt="Capture" src="https://user-images.githubusercontent.com/99853755/154414059-768289cd-ff5d-4734-aeee-c83c5c374da8.PNG">

**Comment by kensoh** [comment]
Hi @avi25070 thanks for raising this issue, it looks like there is some problem running on your office laptop. Can you try to copy the whole error line above `"C:\Users\.../tagui" rpa_python chrome` and see if there is any helpful error message?

**Comment by kensoh** [comment]
Hi @avi25070 thanks for raising this issue, it looks like there is some problem running on your office laptop. Can you try to copy the whole error line above `"C:\Users\.../tagui" rpa_python chrome` and run it on the command prompt, to see if there is any helpful error message?

Run it in the same folder containing the rpa_python temporary file (your current working directory in Python)

**Comment by kensoh** [comment]
Closing issue for now but please let me know if you run into any problem!
