### ISSUE TITLE
How to use the package if internet access is blocked - use pack() and update()

### ISSUE THREAD

**Issue by jianggd417** [tebelorg/RPA-Python#362]

**Comment by fatcarter** [comment]
why close this issue, i have same question
Please tell me what is the solution to the problem?

**Comment by kensoh** [comment]
Hi @jianggd417 and @fatcarter, for using rpa package without the internet (for eg company firewall blocking automatic downloading of dependencies during init()), you can use r.pack() on a PC with internet. It will create a zip file for you to copy to your company laptop to use the package.

For updating to newer version, use r.update(). It will create a Python .py file for you to copy to company laptop.

**Comment by kensoh** [comment]
Closing this issue and keeping the duplicated similar issue https://github.com/tebelorg/RPA-Python/issues/376 open.
