### ISSUE TITLE
Setting up TagUI-Python on Windows 10 with internet restriction - use pack()

### ISSUE THREAD

**Issue by Cyruszhz** [tebelorg/RPA-Python#367]
when I start my RPA program, I come out with this issue.

[RPA][INFO] - setting up TagUI for use in your Python environment
[RPA][INFO] - downloading TagUI (~200MB) and unzipping to below folder...
[RPA][INFO] - C:\Users\Administrator\AppData\Roaming

First of all, can I just skip the downloading procedure, cause I already download the tagui-library, and move it to the folder as required?
but it still doesn't work. 

As for the downloading procedure, I come across some kind of new issues such as 
<urlopen error [WinError 10054] 远程主机强迫关闭了一个现有的连接。>
[WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

what can I do with it

**Comment by jshah3821** [comment]
Have you python and pip installed correctly in your system?

**Comment by kensoh** [comment]
Hu @Cyruszhz, this rpa package uses a forked version of TagUI. You cannot download from TagUI website to use with this package. If you have company firewall or internet restriction, you can use pack() on your personal PC to generate the zip file to copy to your company PC - https://github.com/tebelorg/RPA-Python#core-functions
