### ISSUE TITLE
How to use Mac Chrome browser installed at custom location - modify this file

### ISSUE THREAD

**Issue by niaiwomattt** [tebelorg/RPA-Python#369]
ERROR - cannot find "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
Chrome is at a non-standard location on your macOS, raise an issue on t.me/rpa_chat

**Comment by kensoh** [comment]
Hi @niaiwomattt, is Chrome installed on your Mac PC? Where is it installed? This error message happens when Chrome is not found at above location, which is the default and standard installation location for Mac.

**Comment by niaiwomattt** [comment]
I really don't install it in the standard folder, but can I configure it? I'm afraid I'm moving my position, which will cause problems with chrome.

**Comment by kensoh** [comment]
I see, if you are installing Chrome to a special folder, you can edit this file `~/.tagui/src/tagui`. Search for `Google` and there should be 3 lines of code that you can change to your installation location for Google Chrome app.

**Comment by kensoh** [comment]
Closing issue for now but please let me know if you run into any problem!
