### ISSUE TITLE
Click to the right of a matched image - here are 2 ways that are commonly used

### ISSUE THREAD

**Issue by SalvatoreMazzullo** [tebelorg/RPA-Python#370]
By default when using `r.click('image.png')` is clicked in the center of the image.
But if I would click to the right of the found image?
Is this possible? And how?
Thanks for the reply :)

**Comment by kensoh** [comment]
Hi @SalvatoreMazzullo, adding on, one way is to take a snapshot of the screen such that the centre of the image is on the right of the UI element. Another way is to use hover() to first move the mouse to the UI element, then mouse_xy() to get the coordinates, before using click() on the coordinates with some pre-decided offset.
