### ISSUE TITLE
During headless_mode = True, can click using png? - no, computer cannot see

### ISSUE THREAD

**Issue by jshah3821** [tebelorg/RPA-Python#371]
In my case click using image works fine but when i made headless mode True,Image clicking not works .
i got [RPA][ERROR] - cannot find abc.png

Waiting for reply...

**Comment by kensoh** [comment]
Hi @jshah3821, image clicking requires visible mode because computer vision is used. In headless mode, the computer cannot see anything in the headless browser.

**Comment by jshah3821** [comment]
Thanks kensoh,
I got your point.
