### ISSUE TITLE
'utf-8' codec can't decode byte 0xb0 in position 65: invalid start byte - chcp?

### ISSUE THREAD

**Issue by claireyang5588** [tebelorg/RPA-Python#374]
when i import rpa as r
then error message
[RPA][ERROR] - 'utf-8' codec can't decode byte 0xb0 in position 65: invalid start byte

what's wrong 

how to solve ,thank you

**Comment by kensoh** [comment]
Hi @claireyang5588 this Python error happens when the data or code is not in recognisable utf-8 format.

Can you share your Python .py file that can trigger this error?

**Comment by kensoh** [comment]
Adding on, a similar issue was raised in the past, and this solution be helpful - https://github.com/tebelorg/RPA-Python/issues/215#issuecomment-812646665

**Comment by kensoh** [comment]
Closing issue for now until further inputs, or reports from other users. But please let me know if anything!
