### ISSUE TITLE
Can rpa package can set ip proxy of ip proxy pool? - some options to explore

### ISSUE THREAD

**Issue by lanSeFangZhou** [tebelorg/RPA-Python#377]
Can rpa can set ip proxy of ip proxy pool?  like spider

**Comment by kensoh** [comment]
Hi @lanSeFangZhou can you tell me more about the usage scenario?

For using download() function, there's a way to set proxy in Python, but I have not verified that. For internet access through Chrome browser, for now it is to mimic the human steps needed to change the proxy from Chrome settings, using visual automation and keyboard() function.

If there is a strong use case, maybe can explore if custom IP can be controlled programmatically. Can you also share some basic steps, if possible, to replicate and test if a proxy pool is working, including the dummy proxy credentials used?

**Comment by lanSeFangZhou** [comment]
For example, i have many ip in ip proxy pool, but when i use rpa-python, i need set a ip to use.
I will try your method, thank you.
but now rpa-python don't have this function.

**Comment by lanSeFangZhou** [comment]
Do you have a email?

**Comment by kensoh** [comment]
I see.. Yes you can email me some IP proxy pool credentials at ken@tebel.org

Some test cases that will be helpful for me to test will be -

1. something that you access with download() that requires ip proxy to access
2. something that you access with Chrome browser that requires ip proxy to access

**Comment by kensoh** [comment]
Closing issue until further inputs

**Comment by lanSeFangZhou** [comment]
Hi, kensoh, Does rpa-python has api for setting a ip from ip pool? Download() function have no action.

**Comment by kensoh** [comment]
Oh for download() it uses standard Python libraries, you can try setting environment variables before running python to see if that helps. For web browser proxy, I believe need to use visual automation and keyboard to set it in the Chrome browser.

```
set http_proxy=http://proxy.myproxy.com
set https_proxy=https://proxy.myproxy.com
```

**Comment by lanSeFangZhou** [comment]
I mean how can i set with rpa-python api. I use a docker to run rpa python on linux, all process is ok, but don't know how to set a dynamic ip, it don't havr visual automation, and use rpa-python==1.27.1

**Comment by kensoh** [comment]
I see.. The API does not have functions to change IP of the browser directly or the IP of download() function (needs to be set beforehand as environment variables). You can consider running separate jobs and rotate the IPs.

**Comment by lanSeFangZhou** [comment]
Thank you, I will have a try.
