### ISSUE TITLE
Visual automation cannot find image - some ideas and areas to look through

### ISSUE THREAD

**Issue by emshihab008** [tebelorg/RPA-Python#378]
Hi,
I am having problem with visual automation. First of all, using os library, I rename the file name. Then I need to move all the files. For moving the i use keyboard automation. But when I use visual automation, it doesn't work.
If the below image 2 exists, it will click on cancel. But for me, it doesn't give any error message.  
```

if r.exist('fileinuse.png'):
    r.click('cancel.png')
```
If I use directly, it shows the below error message.
`r.click('cancel.png')`

[RPA][ERROR] - cannot find cancel.png

Image 1:
![cancel](https://user-images.githubusercontent.com/76218957/168252758-c5b86df9-c62f-4f97-bb38-c50dbcf973eb.png)
Image 2:
![fileinuse](https://user-images.githubusercontent.com/76218957/168252760-81b4ac73-39c7-468a-addb-56f571720d99.png)

```
#rename the file
import os
import datetime
today = datetime.datetime.now()
current_date = today.strftime("%y.%m.%d")
path=os.chdir("G:\\invoice_info_extraction\\email_attachment")
target_folder ="G:\\invoice_info_extraction\\archive"
i=0
for file in os.listdir(path):
    if file.endswith('.pdf') and not file.endswith('.log'):
        name, ext = os.path.splitext(file)
        new_file_name = current_date+"_"+name+ ext.format(i)
        os.rename(file,new_file_name)
        
# move the file        
import rpa as r
r.init(True,False)

r.wait(2)
r.click(1012,397)
saved_path = "G:\\invoice_info_extraction\\email_attachment"
r.run('cmd /c start '+saved_path)
r.wait(3)
r.click(1012,397)
r.wait(3)
r.keyboard('[ctrl]a')
r.keyboard('[ctrl]x')
r.wait(2)
r.keyboard('[alt][f4]')
r.wait(1)
moved_path = "G:\\RPA_testing\\rpa_python\\invoice_info_extraction\\archive"
r.run('cmd /c start '+moved_path)
r.wait(3)
r.wait(1)
r.click(1012,397)
r.keyboard('[ctrl]v')
r.wait(3)
if r.exist('fileinuse.png'):
    r.click('cancel.png')

r.keyboard('[alt][f4]')
r.wait(3)
r.close()
```

Regards,
Ekram

**Comment by kensoh** [comment]
Hi Ekram, it looks like you want to click Cancel button if the popup appears.

In that case you can do either of the following -

```py
r.wait(3) # wait() because present() returns result immediately
if r.present('cancel.png'):
    r.click('cancel.png')
```

```py
# no need wait() because exist() will check up to 10 sec timeout
if r.exist('cancel.png'):
    r.click('cancel.png')
```

Some other things you can check -
- verify if the file is really there in the right folder by running `print(os.path.isfile('cancel.png'))`
- try changing your Windows display zoom % to 100% or the recommended %

**Comment by emshihab008** [comment]
Hi Kensoh,
Thanks for the information. It helped me to find out the issue. Actually, the image file was in different location. That's why, it was not working. Now I have provided the file path. It is working properly.
```
if r.exist('C:\\Users\\shihab\\cancel.png'):
    r.click('C:\\Users\\shihab\\cancel.png')
```
