### ISSUE TITLE
run command cannot identify file with a blank space - Windows syntax issue

### ISSUE THREAD

**Issue by emshihab008** [tebelorg/RPA-Python#379]
Hi,
I have an issue with run command. When I write the below code, it works perfectly. 

```
import rpa as r
r.init(True,False)

r.keyboard('[win]r')
r.wait(2)
r.keyboard('G:\\RPA_testing\\rpa_python\\production_planning\\email_attachment\\Purchase Order_202100045.pdf')
r.wait(2)
r.keyboard('[enter]')
r.close()
```

But when I am using the r.run, it shows below error message. How could I resolve this issue? 
Note that there is a blank space between pdf file name (Purchase Order).

```
import rpa as r
r.init(True,False)
r.run('cmd /c start G:\\RPA_testing\\rpa_python\\production_planning\\email_attachment\\Purchase Order_202100045.pdf')
r.close()

```
![image](https://user-images.githubusercontent.com/76218957/168575652-d38ca8ba-7a21-42aa-93b8-9cb0925124ba.png)

Regards,
Ekram

**Comment by kensoh** [comment]
This is Windows command prompt syntax issue, for path name with space, try using double quotes to see if it helps -
```py
r.run('cmd /c start "G:\\RPA_testing\\rpa_python\\production_planning\\email_attachment\\Purchase Order_202100045.pdf"')
```

**Comment by kensoh** [comment]
What error message did you get? I don't have a Windows laptop to test.

**Comment by emshihab008** [comment]
Hi,
When I run the script, it doesn't show any error message. At the same time, it doesn't open the pdf also. Here is the screenshot.

![image](https://user-images.githubusercontent.com/76218957/169077123-392f809f-8c87-404d-9e9f-079d0e2eebb2.png)

![image](https://user-images.githubusercontent.com/76218957/169077471-db4a4234-3208-4d9c-bd85-5d5590725c27.png)

**Comment by emshihab008** [comment]
It worked.

**Comment by kensoh** [comment]
Oh wonderful, I'll close the issue but let me know again if something crops up
