### ISSUE TITLE
Cannot get frame() to work - you can query directly without html/body prefix

### ISSUE THREAD

**Issue by EdGrossman** [tebelorg/RPA-Python#380]
I'm trying to access elements within a frame. The frame() function will not give me anything past html/body. Here's a simple example. Both p and q give me a 0 result even though there is an iFrame called Framename and a child div in the source. I would expect both functions to return 1. Could you tell me if I'm doing something wrong or if it's broken?

```
    r.init()
    r.url('https://allwebco-templates.com/support/S_script_IFrame.htm')
    r.frame('Framename')
    p = r.count('html/body/div')
    q = r.count('html/body/*')
```

**Comment by kensoh** [comment]
Closing issue for now until further inputs to above
