### ISSUE TITLE
How to make browser window invisible - use r.init(headless_mode = True)

### ISSUE THREAD

**Issue by JJery-web** [tebelorg/RPA-Python#381]
Hello, first of all, thank you and appreciate your development of RPA related functions.

Maybe my ability is limited. When I use RPA, I find that the window always pops up (such as Google window), which affects the use experience to a certain extent. So I would like to ask whether there are functions such as selenium (**headlesss**), such as:

- chrome_ options =Options()
- chrome_ options. add_ argument('--headless')
- self. driver = webdriver. Chrome(options=chrome_options)

Thank you again for your work and hope to get your reply!

**Comment by kensoh** [comment]
Thank you @JJery-web for sharing your appreciation. For headless mode, do it this way https://github.com/tebelorg/RPA-Python/issues/240#issuecomment-839981773

**Comment by kensoh** [comment]
`r.init(headless_mode = True)`

**Comment by JJery-web** [comment]
> `r.init(headless_mode = True)`

Yes! I try it and successful. Thank you so much. Amazing project.
: )

**Comment by JJery-web** [comment]
> Thank you @JJery-web for sharing your appreciation. For headless mode, do it this way [#240 (comment)](https://github.com/tebelorg/RPA-Python/issues/240#issuecomment-839981773)

Thank you very much for your solution. Besides, I have a personal question. What is the **difference** between RPA and selenium? Before, I used selenium for automatic crawlers, and often resisted crawlers. Does RPA have more advantages in simulating human beings?

Thank you again for your reply!

**Comment by kensoh** [comment]
Oh Selenium is for for testing, so there are a lot of options and settings designed for testing purpose.

This Python rpa package is for automating processes, so it is designed with very specific options for automation.

On a technical level, Selenium uses Chromedriver, but for rpa package I wrote the DevTools Protocol code directly to control Chrome using a web socket connection. I heard from users that it mimics a real user more closely than Selenium. And less likely to run into trouble with browser bot detection and restriction.

It also runs with a real Chrome user profile, just like a real human user.

Lastly, taking a bigger step back, Selenium is for web automation. This rpa package can do web automation, desktop automation, computer vision automation, OCR and Telegram automation. So it can do a lot more than Selenium, while having very easy to use API compared to Selenium.

**Comment by JJery-web** [comment]
> Oh Selenium is for for testing, so there are a lot of options and settings designed for testing purpose.
> 
> This Python rpa package is for automating processes, so it is designed with very specific options for automation.
> 
> On a technical level, Selenium uses Chromedriver, but for rpa package I wrote the DevTools Protocol code directly to control Chrome using a web socket connection. I heard from users that it mimics a real user more closely than Selenium. And less likely to run into trouble with browser bot detection and restriction.
> 
> It also runs with a real Chrome user profile, just like a real human user.
> 
> Lastly, taking a bigger step back, Selenium is for web automation. This rpa package can do web automation, desktop automation, computer vision automation, OCR and Telegram automation. So it can do a lot more than Selenium, while having very easy to use API compared to Selenium.

Thank you very much for your detailed and professional reply. I wish you a happy life. I have learned a lot.

**Comment by kensoh** [comment]
Thank you Jerry for your kinds wishes, I appreciate it.
