### ISSUE TITLE
Selecting a field from scrollable options - some ideas and pending replication

### ISSUE THREAD

**Issue by liazz** [tebelorg/RPA-Python#382]
I am trying to automate few things on oracle cloud website and I am trying to select a option using its xpath as there is no id or class for it but that is not working. But able to click that particular option using an image. I want to know is there any other way rather than using an image.

**Comment by kensoh** [comment]
Usually the select() function works for cases like this - https://github.com/tebelorg/RPA-Python#basic-functions

The first parameter is the identifier of that dropdown, and the second parameter can be the value or the text.

You can try that and if not, could you provide some replication steps so folks can try it out to figure out.

There's also a new Telegram group which you can post the scenario and see if other folks have come across this problem - https://t.me/pythonrpa

**Comment by liazz** [comment]
I have gone through the functions and as per my knowledge select() is used to select from a dropdown menu. I want for scrollable menu. 
Here is an image where scrollable menu looks like
![scrolable](https://user-images.githubusercontent.com/40200542/170255889-a7d39796-b042-40c5-8dde-93bcfb540fce.png)

**Comment by kensoh** [comment]
I see.. As long as it is on a webpage, there should be XPath to identify each item on the screen.

Is the website accessible publicly? Or do you have a test website with similar menu to test on?

**Comment by liazz** [comment]
No, the website is not accessible publicly.

Here is a website where you can test
https://pixinvent.com/bootstrap-admin-template/robust/html/ltr/vertical-menu-template/vertical-nav-native-scroll.html

On the left column there are list of options and you can scroll up and down for more options.

**Comment by kensoh** [comment]
I see, following works for me -

```py
import rpa as r
r.init()
r.url('https://pixinvent.com/bootstrap-admin-template/robust/html/ltr/vertical-menu-template/vertical-nav-native-scroll.html')
r.click('//*[@data-i18n="nav.chartist.main"]')
r.click('//*[@data-i18n="nav.chartist.chartist_line_charts"]')
```
\
The identifier is found by right-clicking and inspecting on the element using Chrome browser.

Above is XPath syntax to point to any attribute in the element, in this case it is trying to match with data-i18n attribute.

**Comment by kensoh** [comment]
Closing till further inputs
