### ISSUE TITLE
How to select for a drop-down box with attribute span - see this example code

### ISSUE THREAD

**Issue by Sunywdev** [tebelorg/RPA-Python#386]
The drop-down selection box of the website is a span, which cannot be selected when using select

**Comment by kensoh** [comment]
Do you have a sample script that can run that that website? So that other folks here can test out?

span shouldn't be a problem, the logic for the select() function checks for child elements of a parent element, without restriction on the type of element. If the website is not publicly accessible, you can try automate clicking on it first, then click on the option you want.

**Comment by Sunywdev** [comment]
import rpa as r

r.init(chrome_browser=True)
r.url('https://ant.design/components/select-cn/')
r.select('//*[@id="components-select-demo-basic"]/section[1]/div[1]/div/span[2]', 'Jack')

**Comment by Sunywdev** [comment]
import rpa as r

r.init(chrome_browser=True)
r.url('https://ant.design/components/select-cn/')
r.select('//*[@id="components-select-demo-basic"]/section[1]/div[1]/div/span[2]', 'Jack')

**Comment by Sunywdev** [comment]
Like this, I can't get him to pick Jack, is there something wrong with the way I use it?

**Comment by kensoh** [comment]
This dropdown looks like not a standard dropdown box. There are not child elements under it even when clicked on -

![Screenshot 2022-06-01 at 1 11 03 AM](https://user-images.githubusercontent.com/10379601/171362671-12b0bb78-20dc-438d-8079-649c2ed3db91.png)

In that case you can do that in 2 clicks, first click on the dropdown, then click on the option. Both XPath identifiers below can be found by right-clicking and inspecting on the element. There is probably nicer looking XPaths that you can rewrite to. For eg the option can be clicked with - `r.click('//*[@class="ant-select-item-option-content" and text()="Jack"]')`

```
r.click('//*[@id="components-select-demo-basic"]/section[1]/div[1]/div/span[2]')
r.click('/html/body/div[5]/div/div/div/div[2]/div[1]/div/div/div[1]')
```

**Comment by Sunywdev** [comment]
Ok brother, thank you for your detailed answer, I think I already know how to get the value, I will close this issue
