### ISSUE TITLE
Need help from RPA for Python Community - 30-60min call for master thesis

### ISSUE THREAD

**Issue by emshihab008** [tebelorg/RPA-Python#387]
Hi Everyone,
My name is Ekram,  currently studying Master’s degree in Automotive Production Engineering with a focus on Automation and Digitization in Germany. I would like to inform you that I am writing my master thesis in the field of RPA. My task is to conduct a feasibility study about adoption of open source RPA tool in Industry. For my thesis work, I have worked on RPA for Python. Now, I need to evaluate my solution consulting with RPA expert as well as gather some openion based information. If anyone can give 30-60 minutes, it would be a great help. I look forward to hearing from you.

Regards,
Md Ekramul Mostaquim

**Comment by kensoh** [comment]
Hi Ekram, that's great, hopefully some user respond to your post. I'll pin your message in the Telegram group

**Comment by emshihab008** [comment]
Hi Kensoh,
Thank you very much for your support.

Regards,
Ekram
Whatsapp: +4915224893493
Email: ***@***.***
