### ISSUE TITLE
Closing system popups - pending replication and some ideas to explore

### ISSUE THREAD

**Issue by boeschl** [tebelorg/RPA-Python#388]
Hi Everyone, thanks for this amazing tool that I have enjoyed a lot automating some stuff around.

I have a case where the customer website shows everything on popups and have manage to grab all the files required for each iteration. The problem resides that I need to close all the previous pop-up to start a new iteration. How can this be done? The only option I found was to perform a close, but that means then to log again into the system which is not very efficient

Thanks in advance for any ideas

**Comment by kensoh** [comment]
Hi @boeschl, how would you normally do the process of closing popups? Maybe you can try to automate in the same way.

If by popup you mean is a new tab, you can try using r.keyboard('[ctrl]w') or something to that effect to close it. But be sure to do something like r.click('image.png') to make sure the Chrome browser is made to be in the foreground to 'receive' the keystrokes to close.

**Comment by boeschl** [comment]
Thanks @kensoh it work perfectly!! Well initially closed the program itself then actually moved the focus correctly
