### ISSUE TITLE
I want to paste the copied content into the input box - make browser in focus

### ISSUE THREAD

**Issue by Sunywdev** [tebelorg/RPA-Python#391]
here is my code
```
import rpa as r

r.init(chrome_browser=True, visual_automation=True)
r.url('https://www.baidu.com')
sf = 'zzzz'
r.clipboard(sf)
r.click('//*[@id="kw"]')
r.keyboard('[ctrl]v')
```

**Comment by Sunywdev** [comment]
I referenced the content here[https://github.com/tebelorg/RPA-Python/issues/73](url)

**Comment by kensoh** [comment]
Hi @Sunywdev, try doing a `r.click('image.png')` before you do the `r.keyboard()` step. image.png can be the Chrome browser icon or some background on the webpage. The most likely reason is the web browser is not in the foreground, so [ctrl]v ends up in some other application that is in the foreground at the time `r.keyboard()` is executed. Doing a click visually ensures that the Chrome browser is in the foreground and in focus to paste data into it.

**Comment by liunaqq** [comment]
I can not r.click('XX.png') or r.click(XX,XX),I am bad,Do you have any other solutions？

**Comment by kensoh** [comment]
Hi @liunaqq , can you share more on what error message do you get and the exact details of your code? Using above need visual automation.
