### ISSUE TITLE
Pulling table of data into variable and typing it into a large text field - try this

### ISSUE THREAD

**Issue by coffeysa** [tebelorg/RPA-Python#392]
Hi,
Trying to pull a table of information from webpage a and dump into a large free text field in webpage b. The read process removes the formatting elements so it appears as one long string. Is it possible to keep the formatting? I can see that clipboard allows this, but the flow to copy and paste from one webpage repeatedly would not be kind to script.

Thanks!

**Comment by kensoh** [comment]
I see.. You can try to replicate the exact steps how you copy and paste. You can use functions like mouse(), keyboard(), hover(), click() to visually control the mouse and keyboard to do the selection, copy and paste.
