### ISSUE TITLE
How to check if a download has completed? - I think download() is blocking

### ISSUE THREAD

**Issue by dead-py** [tebelorg/RPA-Python#394]
I'm automating a process to download a .zip containing some .csv files, but i'm not managed to check if it is actually finished to download that .zip

How to improve these lines of code?
I used r.wait(), but that's based on my current internet speed, that's the average time to download that file:

```
    link = r.read('//*[@id="dataset-resources"]/ul/li/div/ul/li[2]/a/@href')
    r.download(link, script_dir + '\\2022.csv.zip')
    r.wait(15.0)
    r.close()
```

Is there any way to check if the file is 100% downloaded instead of waiting an amount of time?

**Comment by kensoh** [comment]
I think download() will run until the download completes, before next line executes, I think there should be no need to wait.

For downloading trigger from click on a website link or button, ways to check would have having a while loop with some delay to see if the downloaded file exists, or use visual automation to check that the downloading is completed.

**Comment by kensoh** [comment]
Adding on, for example below, it will keep running until the download completes before running the next line
```py
import rpa as r
r.download('https://github.com/tebelorg/Tump/releases/download/v1.0.0/TagUI_macOS.zip')
print('done')
```

**Comment by dead-py** [comment]
It worked perfectly fine as you described, thank you!
