### ISSUE TITLE
Simulate the left mouse button long press function - use hover() and mouse()

### ISSUE THREAD

**Issue by JJery-web** [tebelorg/RPA-Python#395]
Hello, dear developer.

I recently encountered a problem. I need to simulate a human to **long press** an element with the mouse, and then **release** the mouse after a period of time.

What function should this process call or how to handle it better? I found that _click_ doesn't seem to have a long press function.

Thank you! Looking forward to receiving your reply.

**Comment by kensoh** [comment]
Hi @JJery-web for such scenario you can use visual automation to hover the mouse on the element, then use mouse() to do the pressing (see https://github.com/tebelorg/RPA-Python#pro-functions). Below is something you can try out -

```py
# visually click on the browser to ensure it is in the foreground and in focus
r.click('chrome.png')

# move the mouse to the location of the button you want to long press
r.hover('button.png')

# do the mouse down and up magic according to your needs
r.mouse('down')
r.wait(30)
r.mouse('up')
```

**Comment by JJery-web** [comment]
> Hi @JJery-web for such scenario you can use visual automation to hover the mouse on the element, then use mouse() to do the pressing (see https://github.com/tebelorg/RPA-Python#pro-functions). Below is something you can try out -
> 
> ```python
> # visually click on the browser to ensure it is in the foreground and in focus
> r.click('chrome.png')
> 
> # move the mouse to the location of the button you want to long press
> r.hover('button.png')
> 
> # do the mouse down and up magic according to your needs
> r.mouse('down')
> r.wait(30)
> r.mouse('up')
> ```

Thank.

I also want to ask how to add proxy IP? I found that the scraped had been detected recently. I'm sorry to bother you again.

**Comment by kensoh** [comment]
I see, there are a few ways to set the proxy IP for Chrome, you can google to see which way is most suitable.

Then in your script, maybe you can do a long wait, so that you can set the proxy settings and save it for future runs.

```py
r.wait(300)
```

**Comment by kensoh** [comment]
No probs feel free to ask any questions. If I don't reply, helpful folks from the community will also help out!

There's also a Telegram group to post and ask any questions, if you use Telegram - https://t.me/pythonrpa

**Comment by JJery-web** [comment]
> No probs feel free to ask any questions. If I don't reply, helpful folks from the community will also help out!
> 
> There's also a Telegram group to post and ask any questions, if you use Telegram - https://t.me/pythonrpa

Thank you very much for your reply!
I wish you a happy life and hope this project will develop better!
