### ISSUE TITLE
Can't find image to click on using visual automation - some ideas to check

### ISSUE THREAD

**Issue by mimranarif777** [tebelorg/RPA-Python#397]
Hi Imran here, I am unable to click/dclick any icon on my windows desktop using RPA for Python e.g. using r.dclick("Paint_icon.png"). Anybody to correct me what I am doing wrong? Thanks.

**Comment by kensoh** [comment]
Some ideas to check -
- check if that image file exists in the current folder, can check with print(os.getcwd())
- try changing windows display zoom % to recommended % or 100%
- check that the icon is really visible on the screen
- check that the icon is on your primary monitor (the one with windows yaskbar)

**Comment by mimranarif777** [comment]
> Some ideas to check -
> 
> * check if that image file exists in the current folder, can check with print(os.getcwd())
> * try changing windows display zoom % to recommended % or 100%
> * check that the icon is really visible on the screen
> * check that the icon is on your primary monitor (the one with windows taskbar)

Thanks Kensoh, it worked. I was missing image file in cwd. Thanks.
