### ISSUE TITLE
Can RPA running in the background？- yes use r.init(headless_mode = True)

### ISSUE THREAD

**Issue by warlegtree** [tebelorg/RPA-Python#398]
The RPA-python is great and easy to use.  I have wrote my first RPA program for web automation. I would like to know if the program can run in the background，I mean each time I run the program, chrome launch, but some environments don't install the X windows and GNOME Desktop so how can I run my program  in this case ?

Tks.

**Comment by kensoh** [comment]
Thanks for sharing positive feedback! You can try headless mode (invisible browser without a display) this way https://github.com/tebelorg/RPA-Python/issues/240#issuecomment-839981773

For more advanced setup on Linux without display see this Colab notebook example that runs using Xvfb - https://colab.research.google.com/drive/13bQO6G_hzE1teX35a3NZ4T5K-ICFFdB5?usp=sharing

**Comment by warlegtree** [comment]
Thanks a lot. I will try it. : )
