### ISSUE TITLE
The captcha slider could not stay sliding - try a single step and slower motion

### ISSUE THREAD

**Issue by Turbolento** [tebelorg/RPA-Python#399]
Hi, I want to simulate the mouse dragging the captcha slider, but it turns out that every time I slide it halfway, the mouse is released.How can I solve these problems? Thanks for the help。

      r.hover(254, -659)
      r.mouse('down')
      r.hover(254, -659)
      r.hover(353, -659)
      r.hover(492, -659)
      r.hover(520, -659)
      r.mouse('up')
![1](https://user-images.githubusercontent.com/30725265/175006878-a5ed3008-85e8-4868-ab8d-53808524a06e.gif)

**Comment by kensoh** [comment]
Thnaks for the detail info and video. I see, I haven't come across this strange behavior. What happens if you slide in one step? The automation will simulate moving the mouse cursor from starting point to end point over 1 second.

r.hover(254, -659)
r.mouse('down')
r.hover(520, -659)
r.mouse('up')

**Comment by Turbolento** [comment]
> Thnaks for the detail info and video. I see, I haven't come across this strange behavior. What happens if you slide in one step? The automation will simulate moving the mouse cursor from starting point to end point over 1 second.
> 
> r.hover(254, -659) r.mouse('down') r.hover(520, -659) r.mouse('up')

Hi, kensoh, thank you for your kind reply.
I tried to slide in one step, but this captcha security check will not pass, I guess it is due to even speed sliding.
So I tried using selenium to slide using a variable speed and it works.
Is rpa_python able to implement this variable speed sliding?

**Comment by kensoh** [comment]
Oh I see.. I've just checked, the default timing is 0.5 seconds, maybe too fast. You can try below to make it slower -
```py
# setting for mouse movement to 2 seconds
r.vision('Settings.MoveMouseDelay = 2')
```

**Comment by Turbolento** [comment]
I did what you said, but it still failed. The error message is "Verification failed, please try again". 
![image](https://user-images.githubusercontent.com/30725265/175193012-ae145693-88d9-4fc3-b578-9320c4714e8f.png)

**Comment by Turbolento** [comment]
Hi, kensoh, Thank you again for your help.
This issue has been solved. I tried to do like the following code and it worked.

    r.vision("""Settings.DelayBeforeMouseDown=0;
    Settings.DelayBeforeDrag=0;
    Settings.DelayBeforeDrop=0;
    Settings.MoveMouseDelay=0.15""")
    r.hover(254, -659)
    r.mouse('down')
    r.hover(353, -659)
    r.hover(492, -659)
    r.hover(520, -659)
    r.mouse('up')

**Comment by kensoh** [comment]
Adding on, the following settings may not be needed, because rpa package does not uses the dragDrop() function of SikuliX, but directly uses the mouse down --> moving --> mouse up. https://sikulix-2014.readthedocs.io/en/latest/scripting.html

```
Settings.DelayBeforeMouseDown=0;
Settings.DelayBeforeDrag=0;
Settings.DelayBeforeDrop=0;
```

**Comment by kensoh** [comment]
This is a good working example, I've added to readme - https://github.com/tebelorg/RPA-Python#api-reference

**Comment by Turbolento** [comment]
Thank you very much! This content is very helpful.
