### ISSUE TITLE
How does RPA-Python perform Non-Headless look like in Google Colab?

### ISSUE THREAD

**Issue by gtpeter** [tebelorg/RPA-Python#400]
Hi, Ken Soh

I have just installed /set up everything same as what you recommend in #291 ,  and everything run smoothly without error.

My thought (or understanding) is,  RPA-Python would pop up a new Chrome Tab to perform the search etc.  But nothing was pop up during the test,   Yet I could view and download the result.png screenshot. 

I am very newbie in Python, RPA and Google Colab,   so my question:  "is this normal for RPA-Python in Google Colab, because it is web-based?"  or "Shall I expect something pop up to perform the automation visually?"

Thanks
Peter

**Comment by kensoh** [comment]
Yes previous version of the Colab notebook is running in headless mode, but the latest version is running normal Chrome with a virtual display.

**Comment by kensoh** [comment]
A virtual display in Linux means a display that exists in memory and cant be seen on the screen.

**Comment by gtpeter** [comment]
> Hi Peter, can you share more what do you mean? For running in Colab, you are running on Google Linux servers on the cloud, so you cannot see any Chrome browsers. For the Colab notebook it is using virtual display to run. This mode is better than headless as it works with more websites. Some websites will block headless mode browsers because it is automated user.

Yes, Ken Soh.  
You are right, it is all because of my limited knowledge to understand your description correctly. 
I haven't started any real Automation project,  should I encounter any issue, I would definitely look for you again,  Thanks !
