### ISSUE TITLE
Linux r.init() r.pack() failed to download TagUI_Linux.zip - internet restriction

### ISSUE THREAD

**Issue by lanSeFangZhou** [tebelorg/RPA-Python#402]
can tagui load from local file, not online?

**Comment by lanSeFangZhou** [comment]
much time was cost on this file install

**Comment by lanSeFangZhou** [comment]
I have begun to doubt whether rpa can run on the linux system, please help

**Comment by kensoh** [comment]
If you don't have internet access, you can use r.pack() on a Linux system with internet, then move the generated file over to use. Condition to use the package is you first need to have internet access on a computer to automate downloading from GitHub. For pack() you need to use on the same type of OS to generate the right zip file for the OS.

**Comment by kensoh** [comment]
As mentioned in another thread, below working example of rpa package running on Ubuntu (Google Colab) is proof that the package can run on Linux OS - https://colab.research.google.com/drive/13bQO6G_hzE1teX35a3NZ4T5K-ICFFdB5?usp=sharing

**Comment by lanSeFangZhou** [comment]
thank you, i'll have a try
