### ISSUE TITLE
Run rpa in linux, wait for a long time, but have no response - some ideas to check

### ISSUE THREAD

**Issue by lanSeFangZhou** [tebelorg/RPA-Python#404]
1.I have get rpa.py and rpa_python.zip from your colab, and work nornal;

2.but when I run:
# run r.setup() to download TagUI, modify to run Chromium browser and as root user
import rpa as r; r.setup(); r.dump(r.load('/root/.tagui/src/tagui').replace('"google-chrome"', '"chromium-browser"').replace('$headless_switch', '--no-sandbox'), '/root/.tagui/src/tagui')

log is:
(base) root@ubantu-rpa:/home/rpa_workspace2# python rpa_demo1.py 
开始时间: 2022-07-01 17:00:58.161098
准备开始
[RPA][INFO] - setting up TagUI for use in your Python environment
[RPA][INFO] - downloading TagUI (~200MB) and unzipping to below folder...
[RPA][INFO] - /root
[RPA][INFO] - done. syncing TagUI with stable cutting edge version
[RPA][INFO] - TagUI now ready for use in your Python environment
[RPA][INFO] - visual automation (optional) requires special setup on Linux,
[RPA][INFO] - see the link below to install OpenCV and Tesseract libraries
[RPA][INFO] - https://sikulix-2014.readthedocs.io/en/latest/newslinux.html

It have no log, and don't do next step, can you know the reason?

**Comment by lanSeFangZhou** [comment]
when exec: 
r.init() ，
it have no log, and wait for a long time, have no response

**Comment by lanSeFangZhou** [comment]
![image](https://user-images.githubusercontent.com/25838116/176874079-b399b810-6f54-4c7f-948d-45276e6cfe72.png)

**Comment by lanSeFangZhou** [comment]
after one hour, it still have no result or log, do you have some methods to resolve this problem?
I have try it on windows and mac m1,  it's ok.

**Comment by lanSeFangZhou** [comment]
I'm looking forward your help. I want to run python-rpa on linux successful and deploy it in docker, then can run online.
Hope for your answer, than you very much!

**Comment by lanSeFangZhou** [comment]
I'm looking forward your help. I want to run python-rpa on linux successful and deploy it in docker, then can run online.
Hope for your answer, than you very much!

**Comment by lanSeFangZhou** [comment]
Can you provide a docker, so that rpa-python users can void the envoriment problems, or what can I do something for this project?

**Comment by kensoh** [comment]
I see.. Here are some ideas you can explore -

1. did you install Chromium browser? If there is no browser init() will hang. You can try running `chromium-browser` command from the terminal and see what happens
2. does your Linux have display monitor? if no monitor you need to use init(headless_mode = True), or you can use the Colab example to use virtual display
3. you can try this Docker image by OpenRPA creator (choose edge tag) - https://hub.docker.com/r/openiap/nodered-tagui
4. you can try this dockerfile from OpenRPA creator - https://github.com/open-rpa/openflow/blob/master/OpenFlowNodeRED/Dockerfiletagui

For 3-4 I have not verified that they work for Python rpa package, but you can try out to see if they help.

**Comment by kensoh** [comment]
Hopefully above ideas can be useful and solve the problem. If not let me know. I may not be able to check frequently due to work and family, but will try my best to help. If you do it successfully, see if you can host the docker image on Docker Hub and your dockerfile on GitHub, then I can link from this RPA for Python GitHub page to your solution.

**Comment by lanSeFangZhou** [comment]
Thank you, I will have a try now.

**Comment by lanSeFangZhou** [comment]
Does linux have to have a screen to run rpa?
When i run chromium-browser --version, that's ok.
But when I run chromium-browser --no-sandbox, it's have a error:

[1353829:1353829:0704/111028.221794:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
[1353829:1353829:0704/111028.221888:ERROR:env.cc(226)] The platform failed to initialize.  Exiting.

**Comment by lanSeFangZhou** [comment]
I think colab is a linux system, and also don't have a screen, is it right?

**Comment by kensoh** [comment]
You read point 2, and check the Colab link again. The Colab has no screen but it used virtual display. Check the code carefully.

If you don't want to use a virtual display. Use headless mode mentioned in point 2.

**Comment by kensoh** [comment]
Yes web browser requires a display screen to run. It's either using virtual adapter or headless mode solution above.

**Comment by lanSeFangZhou** [comment]
I have tried the Colab code on ubuntu and used virtual display.,  when it exec r.init(), it also have no response for long long time.

Use headless mode have the same result.

When I exec the command on ubuntu linux:

chromium-browser --no-sandbox
[1421218:1421218:0704/163751.252709:ERROR:ozone_platform_x11.cc(247)] Missing X server or $DISPLAY
[1421218:1421218:0704/163751.252896:ERROR:env.cc(226)] The platform failed to initialize.  Exiting.

It's failed.

But when I exec :
chromium-browser --no-gpu --no-sandbox --disable-setuid-sandbox --headless --dump-dom https://www.baidu.com

It can work.

How can I confirm whether it is the chromium-browser problem that result in exec r.init(headless_mode=True) have no response?

**Comment by lanSeFangZhou** [comment]
chromium-browser --no-sandbox --headless
[0704/165643.737355:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[0704/165643.758294:WARNING:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.

**Comment by kensoh** [comment]
When I get a chance, I'll grab the exact chrome command from the source code so that you can try.

Note that the Colab example the code is designed for virtual display (recommended because many websites will block headless browsers), so the setup commands may not work directly for headless mode.

**Comment by lanSeFangZhou** [comment]
Thank you very much， I’m still on test，I feel that because of chromium-browser not support very well on ubuntu linux.

**Comment by kensoh** [comment]
Hi @lanSeFangZhou I have made a detailed reply for another user with similar problem, can you try the steps in below link?

https://github.com/tebelorg/RPA-Python/issues/403#issuecomment-1174973646 and https://github.com/tebelorg/RPA-Python/issues/403#issuecomment-1174976909

Note that this approach is using the virtual display method, which is the best practice for web automation without display.

**Comment by kensoh** [comment]
Made an updated comment to the user's reply at above issue #403

**Comment by kensoh** [comment]
Closing this until further inputs, and keeping #403 open due to similar issue
