### ISSUE TITLE
OCR Chinese - download Tesseract Chinese OCR files and try out this method

### ISSUE THREAD

**Issue by pythonLiNM** [tebelorg/RPA-Python#405]
How can OCR recognize Chinese ，ths!!

**Comment by kensoh** [comment]
See below comment which is verified to work for TagUI engine, the engine used by RPA for Python -

1. download the Tesseract Chinese OCR files and put them in the correct SikuliX directory -
https://github.com/kelaberetiv/TagUI/issues/1215#issuecomment-1110529037

2. use the following Python code in your Python script to switch to Chinese OCR
```py
import rpa as r
r.init(visual_automation = True)

import org.sikuli.script.TextRecognizer as TR
r.vision('Settings.OcrReadText = True')
r.vision('Settings.OcrLanguage = "chi_sim"')
r.vision('TR.reset()')
```
