### ISSUE TITLE
run() not running Windows program - wrong Python syntax \\ for backslash?

### ISSUE THREAD

**Issue by cmcau** [tebelorg/RPA-Python#406]
I'm trying to run Tableau Desktop, but it just won't start.  This is my code:

```py
import rpa as r
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

r.init(visual_automation = True, chrome_browser = False)

r.run('C:\Program Files\Tableau\Tableau 2022.1\bin\tableau.exe')
```

But after attempting many different combinations I still can't make it work

**Comment by kensoh** [comment]
Is there any error message? In python you need to use double backslash to denote backslash because it is a special character. For eg c:\\Windows instead of c:\windows

**Comment by kensoh** [comment]
PS - to create code block in markdown syntax, use triple backticks instead of single backtick.

I have modified your post with the correct syntax to show the text as Python code block.

**Comment by cmcau** [comment]
hmmm, OK, so 
r.run('C:\\Windows\\notepad.exe')

runs notepad very easily, but 

r.run('C:\\Program Files\\Tableau\\Tableau 2022.1\\bin\\tableau.exe')

does NOT run Tableau Desktop - no errors, it just doesn't open at all.

**Comment by kensoh** [comment]
You try to go to command prompt, and run the following to see what happens.

C:\Program Files\Tableau\Tableau 2022.1\bin\tableau.exe

**Comment by cmcau** [comment]
Yes, it starts in about 5 seconds. I have to wrap the command in quotes because of the space in Program Files - would that have an impact?

**Comment by cmcau** [comment]
I get this in the logfile when using the subprocess code:

`
START - automation started - Tue Jul 12 2022 19:56:57 GMT+1000 (AUS Eastern Standard Time)

LIVE MODE - type done to quit
 [RPA][STARTED]
[RPA][0] - listening for inputs
`

But it still doesn't start Tableau.

I don't know what else to do, but can you download Tableau Desktop from https://www.tableau.com/support/releases/desktop/2022.2 (you don't have to register to download) and see what is going wrong? (I know, I'm asking a LOT)

**Comment by kensoh** [comment]
I don't have a Windows laptop to try this, only a Mac and a Linux.

You can try to use the following keyboard automation method to launch, it uses the Windows run popup window.

```py
import rpa as r
r.init(visual_automation = True)
r.clipboard('C:\\Program Files\\Tableau\\Tableau 2022.1\\bin\\tableau.exe')
r.keyboard('[win]r')
r.keyboard('[ctrl]v')
r.keyboard('[enter]')
```

If this doesn't work, it means Tableau is not designed to run from command line. In that case, you can run it using the shortcut link to Tableau app, it may have some other settings and parameters when running it to make it run.

Another idea is creating a dummy batch file below and use the run() function on this. That may somehow work.

**runner.cmd**
```
C:\Program Files\Tableau\Tableau 2022.1\bin\tableau.exe
```

**Comment by kensoh** [comment]
Or in the worst case you can automate the manual steps how you launched Tableau, using visual automation and keyboard automation to automate interacting with desktop apps (examples in the Use Cases section).

**Comment by kensoh** [comment]
Closing issue until further inputs, hope the ideas above work
