### ISSUE TITLE
keyboard() stuck when there is unicode in input - use clipboard() + keyboard()

### ISSUE THREAD

**Issue by niuniu132** [tebelorg/RPA-Python#410]

**Comment by niuniu132** [comment]
r.keyboard('dsasd') works well, but r.keyboard('发生') make tagui stuck.
My os is montrey 12.4.  m1 chip

**Comment by kensoh** [comment]
The SikuliX engine used by the package has a limitation with international languages. Try below instead -

```py
r.clipboard('发生')
r.keyboard('[ctrl]v')
```

**Comment by niuniu132** [comment]
thanks for your answering,  works well.
