### ISSUE TITLE
Snap doesn't running background - need display to capture desktop snapshot

### ISSUE THREAD

**Issue by colopez1** [tebelorg/RPA-Python#411]
Hi friends,

I'm trying to print screen with snap() function and it works fine, but, when I run the script in background the snap function only capture a black screen.

My explample is: I have a remote computer where script is running and only captures a black screen when a task scheduled is running, but, when I run the script and I see the remote desktop, then, it captures the remote desktop screen.

**Comment by kensoh** [comment]
Are you using snap() to capture desktop image or web browser image? For desktop image, I heard that only when there is a real display (through remote desktop for eg), then there is a valid display to capture the snapshot of the screen.

**Comment by colopez1** [comment]
@kensoh thanks for your fast response.
