### ISSUE TITLE
Error on running init() on Google Colab - see example for running as root user

### ISSUE THREAD

**Issue by ongkokl** [tebelorg/RPA-Python#414]
Related to #360 

I trying it running on Colab and hit the same error also.
Pls enlighten.

![image](https://user-images.githubusercontent.com/50367330/181904397-4ce1d94c-5c2d-41f8-ad83-dc51f27b35bf.png)

**Comment by kensoh** [comment]
Oh to run Chrome as root user you need to use the no sandbox switch. See below Colab working example.

https://colab.research.google.com/drive/13bQO6G_hzE1teX35a3NZ4T5K-ICFFdB5?usp=sharing

Is it correct to say that your company only allows using Python tools and packages through Colab?

Am thinking if there are other ways which you can use the Python rpa package in your environment.

**Comment by ongkokl** [comment]
Hi Ken ,

Somehow in my local it still manage to run even with the error somehow. The error will not appear if I restart Python and run like a first time in vscode.

Thanks for the advise.

**Comment by kensoh** [comment]
Try to use a variation of the setup used in the working Colab example -
```py
import rpa as r; r.setup(); r.dump(r.load('/root/.tagui/src/tagui').replace('"google-chrome"', '"chromium-browser"').replace('$headless_switch', '--no-sandbox'), '/root/.tagui/src/tagui')
```
For example, below downloads the TagUI engine, and makes a fix to work for root user -
```py
import rpa as r; r.setup(); r.dump(r.load('/root/.tagui/src/tagui').replace('$headless_switch', '--no-sandbox'), '/root/.tagui/src/tagui')
```
