### ISSUE TITLE
How can I specify the coordinates to capture an image on the screen? - use snap()

### ISSUE THREAD

**Issue by niuniu132** [tebelorg/RPA-Python#415]
can you give a example?

**Comment by kensoh** [comment]
Generally it will be `r.snap(x1, y1, x2, y2, 'filename.png')`. For eg below in the sample.py mentioned in readme -

```py
# another eg is boundary of area of interest x1, y1, x2, y2 for read() and snap()
# for eg r.read(200, 200, 600, 400), r.snap(200, 200, 600, 400, 'results.png')
```

There are more complicated ways to do that, for eg using custom code to get coordinates based on web identifier. But it would involve writing much custom do and piggy-back into TagUI engine's internal functions to do that.

**Comment by niuniu132** [comment]
Thanks so much ken, I tried r.snap(x1, y1, x2, y2, filename_to_save='XX'), and got error

**Comment by niuniu132** [comment]
Delete the keyword then work well.

**Comment by kensoh** [comment]
Welcome @niuniu132! Hope you enjoy using the package
