### ISSUE TITLE
Can't open or find files downloaded during the RPA proccess.

### ISSUE THREAD

**Issue by phelipe-barbosa** [tebelorg/RPA-Python#417]
Hi,

I am running rpa library on a windows machine, and trying to download a zip repository in github.

```
def download_zip_from_gitrepo(repo_name: str, username: str, password: str) -> bool:
    r.init()
    r.url('https://github.com/') # Access the page.
    r.click('Sign in') # click on sign in.

    r.type('Username or email address', username) # Type your username
    r.type('Password', password) # Type your password
    r.click('commit') # click on sign in.
    r.click(repo_name) # click in repository name at left.

    r.click('btn-primary btn') # click on "code" green button.
    r.click('octicon octicon-file-zip mr-2') # Click in "Download Zip" and with that I expect the file will be downloaded on my local machine.

    r.close()
    return print("Done.")
```

When I run this code, rpa download the file from githubUI, but I can't open the file and the location is not founded on my computer. I tried to use `r.download(url)` but doesn't work with my URL. I was expecting that the zip file downloaded should be located in "downloads" folder.

Do you know how can I solve this problem?

**Comment by phelipe-barbosa** [comment]
I found the `r.download_locations` code and the downloaded file was there.

**Comment by kensoh** [comment]
That's right @phelipe-barbosa, `r.download_location()` can be used to set or return the current download location. The default location is the directory where Python is initiated, usually where your Python script resides, ie `os.getcwd()`.

Using `r.download()` directly may not work for some cases where the URL you found isn't the actual final URL but an URL that redirects to another final destination. Or it could be the website blocking downloading directly from URL.
