### ISSUE TITLE
Issue while installing and running - try running this command, pending checks

### ISSUE THREAD

**Issue by chanderbhargava** [tebelorg/RPA-Python#418]
hi there, I am trying to install it on my laptop. getting following error while running the sample code

The system cannot find the path specified.
[RPA][ERROR] - following happens when starting TagUI...

The following command is executed to start TagUI -
"C:\Users\cmbha\AppData\Roaming/tagui/src/tagui" rpa_python chrome

It leads to following output when starting TagUI -
The system cannot find the path specified.

[RPA][ERROR] - unknown error encountered
[RPA][ERROR] - use init() before using url()
[RPA][ERROR] - use init() before using type()
[RPA][ERROR] - use init() before using read()

[RPA][ERROR] - use init() before using snap()
[RPA][ERROR] - use init() before using close()

it is fresh installation.  I have already tried upgrade command too

C:\PythonWork\OpenProcess>pip install rpa --upgrade
Requirement already satisfied: rpa in c:\users\cmbha\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (1.48.1)
Requirement already satisfied: tagui>=1.48.1 in c:\users\cmbha\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from rpa) (1.48.1)

**Comment by kensoh** [comment]
Can you try to run the given command from your command prompt and see what happens?

```
"C:\Users\cmbha\AppData\Roaming/tagui/src/tagui" rpa_python chrome
```

Hopefully that'll give more clues what might be the cause of error. What is your Windows version?

**Comment by dongfat** [comment]
![图片](https://user-images.githubusercontent.com/56581685/186567330-6cf0462f-18c1-4b5b-8dbf-e178d37a33e7.png)

**Comment by kevin3** [comment]
hi @kensoh  I have this issue as well 
when I run it in cmd I got "ERROR - cannot find rpa_python"

**Comment by kensoh** [comment]
This normally happens if PHP is missing and user missed out manual set up steps.

1. What is your OS? (Mac, Ubuntu, Windows have specific steps to make PHP available)
2. try r.debug(True) before doing r.init() to see if there are other clue
