### ISSUE TITLE
Something wrong during initial run - likely network issue, check another laptop

### ISSUE THREAD

**Issue by jorgehtml** [tebelorg/RPA-Python#419]
Hello, when i try to run my code, nothings happens and show this message (image below) in the terminal, can you help me?
![image](https://user-images.githubusercontent.com/78984109/185208483-852285c8-b390-47a9-9812-43e43738408b.png)

**Comment by kensoh** [comment]
Hi @jorgehtml, this happens if automated download fails. It might be your company network or your internet provider not allowing automated download from github.com. Can you try on another laptop to see if the same problem happens?

**Comment by kensoh** [comment]
Closing for time being until further inputs or similar issues being raised
