### ISSUE TITLE
Reference iFrame by class in method frame() - use dom() to set id, then frame('id')

### ISSUE THREAD

**Issue by diegostefano** [tebelorg/RPA-Python#420]
Hi, people!

Is there any way to reference an iFrame by class in the method "frame" instead of using its ID or name?

The iFrames in the page I'm automating don't have IDs or names.

Thanks in advance for any assistance!

**Comment by kensoh** [comment]
As ID and name is a unique way to specify something on a webpage, these are the 2 attributes supported for frame(). However, if you are familiar with JavaScript, you can google and write a 1-line JavaScript code and use dom() to set an id attribute for the frame you want to automate on. After that use frame() to select it with the id you have given it.

**Comment by zailaib** [comment]
![image](https://user-images.githubusercontent.com/10792685/230855343-eaef76ab-c9a1-46a5-b067-75e294bd22c6.png)

id is a dynamic value

**Comment by kensoh** [comment]
I see.. If you know JavaScript, you can use dom() function to set the id attribute for this iframe so that it's referenceable.

Another way is getting the src URL and visiting that iframe page directly using url(), before automating normally.

**Comment by LucasValentimCamara** [comment]
You can try use this following javascript command using DOM to get the id with the dinamic value.

document.querySelector('[id^="cf-chl-widget-"]').id

**Comment by kensoh** [comment]
Thanks @LucasValentimCamara! Oh in @diegostefano and @zailaib case, the goal is to reference elements inside the iframe, but that iframe does not have id or name. The only way I believe this can work is explicitly set the id value for the frame by using JavaScript code in dom() function. Then use frame(). Alternatively use visual automation to control items in the frame, or if viable, try to get the URL of the frame and load that directly in the browser.
