### ISSUE TITLE
Clicking on an element that is visually stacked under other elements - try dom()

### ISSUE THREAD

**Issue by jamesmnixon** [tebelorg/RPA-Python#422]
Ken,

Long time since I last posted here. I continue to love the tool!! I am facing an issue where it seems if I want to click on a target element, 
but that element is stacked under other elements visually, it clicks the element on top instead of the intended target. I am passing the target to r.click() as an Xpath.

Im trying to understand if this is possible in TAG UI. Is it possible that the target XPath is really just a means to collect the (x,y,z) coordinates of the element in a visual manner, but when it comes to actually 'clicking' it relies on the (x,y,z) coordinates instead of the XPath? 

just a little base help in understanding the functionality would be greatly appreciated.

Thank youm

**Comment by kensoh** [comment]
Hi James, thank you!

I see.. The way click() works is it figures out the (x, y) co-ordinates of the web element by calculating the centre of its bounding rectangle, moving to that position and simulating a click. This is the best practice for automation to mimic an actual user's click as closely as possible and trigger the website response as accurately as possible.

However, that means your scenario of clicking on an element that is below other element not possible. This won't be possible if you do it manually, so the tool would by default not be able to do that. You can however, use dom() and write some JavaScript code to select the element and doing a click() directly in JavaScript. But that requires knowing some JS coding or googling.

**Comment by jamesmnixon** [comment]
Thank you Ken! This is the high-level info I was looking for.

Pleasure,
