### ISSUE TITLE
Docker image and dockerfile for Python rpa package - ETA unknown

### ISSUE THREAD

**Issue by kensoh** [tebelorg/RPA-Python#424]
Seems like there are recurring interests for such a distribution channel, see Telegram thread https://t.me/pythonrpa/440

Until I have some free time from work / kid / family to create one myself, users can explore the following ways:

1. check out this user's dockerfile and troubleshoot the error - https://t.me/pythonrpa/390
2. try out Allan Zimmermann's @skadefro [Docker image](https://hub.docker.com/r/openiap/nodered-tagui) (choose edge tag version)
3. see working [Google cloud example](https://colab.research.google.com/drive/1or8DtXZP8ZxJYK52me0dA6O9A1dXKKOE?usp=sharing) running on Ubuntu as part of Google Colab

PS 1 - there might also be some interest from Anaconda's users to have it on conda-forge, will see more if that demand is strong. That basically requires packaging everything together without dependencies to download from github.com.

PS 2 - of course, you are most welcome to try to create the Docker image or conda-forge package should you wish to!

**Comment by kensoh** [comment]
Tagging issue https://github.com/tebelorg/RPA-Python/issues/438 which might be a potential related issue for this issue.

**Comment by skadefro** [comment]
That docker image will not be update moving forward.
I'm moving all "external" stuff to agent/package's instead.
There is now a complete solution for how to write code and debug it using [vs code extension](https://marketplace.visualstudio.com/items?itemName=openiap.openiap-assistent), deploy it as an package and distribute it to either agents running in the cloud using [docker/kubernetes](https://github.com/openiap/nodeagent/blob/main/Dockerfilechromium), to desktop users with the using [the assistant](https://github.com/openiap/assistent)) or a deamon/services. 
See detailed guide here https://openflow.openiap.io/
Example package with tagui using workitems  https://github.com/openiap/taguiagent

**Comment by kensoh** [comment]
Thanks @skadefro! I haven't tried it myself yet. Was dealing with the aftermath from AI Singapore's stop maintenance of TagUI. Will work next on a new Python rpa feature to be able to run TagUI .tagui workflow scripts - https://github.com/tebelorg/RPA-Python/issues/452 This would let existing TagUI users be able to make use of their workflow assets even after AI Singapore stopped maintaining TagUI.

**Comment by kensoh** [comment]
Closing issue because if there is a gap, the market would have already filled it by now by people creating their docker images.
