### ISSUE TITLE
cannot startup RPA-Python in windows 10 professional

### ISSUE THREAD

**Issue by Peter-YAN** [tebelorg/RPA-Python#425]
Hi all,
after i finish all the program(rpaidata.py) in my develop PC, I try RPA-Python in prod PC, windows 10 as the following steps,
1. Install the latest python 3.10.7
2. pip install rpa
3. run _python rpaidata.py_, but the following errors are shown.

_
> D:\idata\rpaidata>python rpaidata.py
> [RPA][INFO] - setting up TagUI for use in your Python environment
> [RPA][INFO] - downloading TagUI (~200MB) and unzipping to below folder...
> [RPA][INFO] - C:\Users\Administrator\AppData\Roaming
> Remote end closed connection without response
> [RPA][ERROR] - failed downloading from https://github.com/tebelorg/Tump/releases/download/v1.0.0/TagUI_Windows.zip...
> [RPA][ERROR] - use init() before using vision()
> [RPA][ERROR] - use init() before using vision()
> [RPA][ERROR] - use init() before using vision()
> [RPA][ERROR] - use init() before using vision()
> [RPA][ERROR] - use init() before using click()
> [RPA][ERROR] - use init() before using click()
> [RPA][ERROR] - use init() before using hover()
> [RPA][ERROR] - use init() before using mouse_x()
> [RPA][ERROR] - use init() before using mouse_y()
> [RPA][ERROR] - use init() before using click()
> [RPA][ERROR] - use init() before using hover()
> [RPA][ERROR] - use init() before using mouse_x()
> [RPA][ERROR] - use init() before using mouse_y()
> [RPA][ERROR] - use init() before using hover()
> [RPA][ERROR] - use init() before using mouse_x()
> [RPA][ERROR] - use init() before using mouse_y()
> [RPA][ERROR] - use init() before using hover()
> [RPA][ERROR] - use init() before using mouse_x()
> [RPA][ERROR] - use init() before using mouse_y()
> [RPA][ERROR] - use init() before using hover()
> [RPA][ERROR] - use init() before using mouse_x()
> [RPA][ERROR] - use init() before using mouse_y()
> [RPA][ERROR] - use init() before using read()
_

In fact, TagUI_Windows.zip is download and unzip in C:\Users\Administrator\AppData\Roaming.

**Comment by Peter-YAN** [comment]
network issue lead to downloading TagUI_Windows.zip failed, no executable file, so....

**Comment by kensoh** [comment]
Looks like you found the solution to download, I saw your post in another issue.

Otherwise, alternative would be using a computer without the internet block from downloading from github.com, or using r.pack() on a computer with internet access to generate a zip before copying over to the network-restricted PC.
