### ISSUE TITLE
Cannot run basic code - network issue, try pack(), use proxy, replicate problem?

### ISSUE THREAD

**Issue by ativis** [tebelorg/RPA-Python#427]
Hi, I face the below error message on Jupyter notebook:

![error](https://user-images.githubusercontent.com/32090754/193704962-34132c62-eb7f-43f2-aba6-380e8dd25bab.JPG)

**Comment by ativis** [comment]
![error2](https://user-images.githubusercontent.com/32090754/193742901-5fec910c-0153-46eb-bdcb-31b669fe8003.PNG)

**Comment by kensoh** [comment]
From above, it looks like your network is blocking automated downloading of dependencies from github.com domain. You can check out the pack() in the API to download it on a computer with internet access that allows automated downloading. Or see if some proxy settings can be modified to allow this computer to do this downloading.

The code used by the package to download is standard Python library. See here. Depending on your Python 2 or 3, you can try to run the following line directly and replicate the problem.

https://github.com/tebelorg/RPA-Python/blob/master/tagui.py#L1468

**Comment by kensoh** [comment]
Oh here - https://github.com/tebelorg/RPA-Python#core-functions and
https://github.com/tebelorg/RPA-Python/issues/36#issuecomment-543670292

r.pack() can be used on a computer with no network restriction, to generate a zip file and rpa.py file. This can then be copied to the computer with network restriction to run and it can work without internet on the target PC. No need pip install rpa.

**Comment by ativis** [comment]
@kensoh Still unable to download :( 
![image](https://user-images.githubusercontent.com/32090754/194982815-be1b9243-45e7-440b-be2b-7e90b1c287f7.png)

**Comment by kensoh** [comment]
Referring to https://github.com/tebelorg/RPA-Python/issues/427#issuecomment-1272154413 you will need to find a computer with no network restriction to do the download from github.com to use pack(). Otherwise pack() can't be used.

**Comment by kensoh** [comment]
Do share back here, if that is not possible. For eg you want to install in your company computer, but there is no way to copy files from your own PC into computer intranet or computer.
