### ISSUE TITLE
pip install rpa or tagui? - use pip install rpa, but you can also use tagui. both same

### ISSUE THREAD

**Issue by arisliang** [tebelorg/RPA-Python#428]
It looks there're 2 version of this package on pip?

1. pip install tagui: https://pypi.org/project/tagui/
2. pip install rpa: https://github.com/tebelorg/RPA-Python

strangely the 1st also refer to 2nd in the project page.

What's the difference, which one is updated?

**Comment by kensoh** [comment]
Oh that's a good question. Originally, this package is named tagui and it is pip install tagui. After I got the rpa package name, I renamed the project to rpa. For backward compatibility reason, I still publish to tagui package for every rpa release. The recommended one is pip install rpa, but you can pip install rpa or pip install tagui. Both are the same.

**Comment by kensoh** [comment]
rpa package has a dependency on tagui package because I structure it that way so that the source code only needs to be housed at tagui package. So this allows old users' script with `import tagui as t; t.init()` to work seamlessly.
