### ISSUE TITLE
Unable to use keyboard functions to input or create a new tab - try r.debug(True)

### ISSUE THREAD

**Issue by warlegtree** [tebelorg/RPA-Python#430]
Hi,

Because the 2FA, so I'm trying the keyboard function in Windows OS to automate Chrome visually. For now, I can launch the chrome but I can't type the URL or create a new tab. Is there anything wrong with my code?  

import rpa as r
r.tagui_location('C:\\TagUI_Windows\\')
r.init(visual_automation = True, chrome_browser = False)
r.run('cmd /c start "" "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"')
r.wait(2)
r.clipboard('www.baidu.com')
r.keyboard('[ctrl]v')
r.keyboard('[enter]')
r.wait(2)
r.keyboard('[ctrl]t')
r.snap('page.png', 'results.png')
r.close()

Or use below code to test the keyboard function, but it didn't work neither

import rpa as r
r.tagui_location('C:\\TagUI_Windows\\')
r.init(visual_automation = True, chrome_browser = False)
r.keyboard('[win]r')
r.keyboard('explorer[enter]')
r.close()

BR//ZZ

**Comment by kensoh** [comment]
Normally you will need to do a r.click() on the browser icon on the taskbar or somewhere on the browser, to make that it is in the foreground and in focus to receive the keystroke. But your second example is strange, and it should work.

Can you add r.debug(True) in your code to see if there are more clues what could be wrong? I assume you have installed OpenJDK, as prompted when you initially do r.init() and if you don't have OpenJDK/Java on your PC.

**Comment by warlegtree** [comment]
Hi

I have installed Zulu JDK on my laptop, is it OK？ And after add r.debug(True) in my code, I got below output 
![image](https://user-images.githubusercontent.com/16379371/194813538-e1a7a75c-3504-4f97-abe6-bc22e7fa4ad6.png)

**Comment by kensoh** [comment]
I think the requirement is 64-bit Java. As long as it is 64-bit Java and Java JDK 8 and above it's ok.

From above, if it hangs there, then something is not ok. You check the following log:

print(r.tagui_location()) --> tagui --> src --> tagui.sikulix --> see what logs are showing there?

**Comment by warlegtree** [comment]
![image](https://user-images.githubusercontent.com/16379371/195481787-8f333e62-f61b-4cb0-a277-c7d2a9afd530.png)
It seems to be caused by the lack of this jar file.

**Comment by warlegtree** [comment]
I just installed the Sikulix and the sikulix.jar is under this path: C:\Users\ezngzen\AppData\Roaming\Sikulix\SikulixLibs_201807110819. So how could I configure the path of sikulix.jar to fix this issue?

**Comment by warlegtree** [comment]
![image](https://user-images.githubusercontent.com/16379371/195751808-da7170a8-8821-4f29-aa44-5b99f690c1bc.png)

Just reinstalled the sikuli but still get the same error info "Unable to access jarfile sikulix\sikulix.jar"

**Comment by kensoh** [comment]
I see.. Not sure why SikuliX is missing. By default when unzipping, there will be files inside tagui\sikulix folder already. Unless there is other factors like anti-virus false positive or company policy deleting the file for example.

**Comment by kensoh** [comment]
The jar files should be in tagui\src\sikulix folder not the one you showed above.

**Comment by warlegtree** [comment]
Nice. My problem has been solved after moving the jar files to the right folder. Thanks a lot.
