### ISSUE TITLE
How to run RPA for Python Script unattended on remote PC - pending checks

### ISSUE THREAD

**Issue by uditi0810** [tebelorg/RPA-Python#431]
Hello all, we have taken a dedicated machine server for running RPA For python scripts. Scheduled them through Task scheduler.
They run fine when we are connected to the machine through Remote Desktop Connection (RDC) but it fails after we kill the session. It is not able to take the clicks etc and do any UI Automation. Please guide me on how to run scripts without human intervention. we need to run them on a daily basis.

**Comment by kensoh** [comment]
Are you using `r.init(visual_automation = True)`? I think visual automation requires a real display being rendered to work.

You can do r.debug(True) to check more what happens. There will be log output when running and a rpa_python.log

**Comment by Sebs66** [comment]
Hello, I got a similar problem using a AWS VM, what I found was that when you kill the connection to the VM, the user session in the machine gets logged out. 
Two ways to solve it where:
1. Using a TightVNC connection between a master an a slave. When you close the TightVNC connection, it does not close the user session.
2. Implementing Autologon by changing windows registry:
This is the .reg file that I used (you should replace last 3 parameters:
"""
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\System]
"DisableLockWorkstation"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System]
"DisableCAD"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon]
"AutoAdminLogon"=dword:00000001 
"DefaultUserName"=""
"DefaultPassword"=""
"DefaultDomainName"=""

"""

**Comment by kensoh** [comment]
@Sebs66 oh wow these are nice tips! Thanks for sharing here! 🙏 

By any chance, have you or your colleagues tried using rpa package in Docker or have your own Docker image? I heard that there are interests from users to have a Docker image but I have not got to create one. If someone already has a good working one I could point to his or her image / dockerfile on Docker Hub.

**Comment by Sebs66** [comment]
No we have not :(

**Comment by kensoh** [comment]
Thank you @Sebs66 for your reply nevertheless! I hope to get some time to look at that in time to come.
