### ISSUE TITLE
Magic page save content missing - some ideas and learning more details

### ISSUE THREAD

**Issue by JJery-web** [tebelorg/RPA-Python#437]
I'm sorry to bother you. I recently encountered a problem.
I use the following paragraph to access a page and save its contents where link is an example.

_symobl=["CEG","COO","COP","COST","CPB","CPRT","CPT","CRL","CRM","CSX","CTAS","CTLT","CTRA"]
for i in symobl:
  link="https://seekingalpha.com/"+i+"/CEG/earnings/transcripts"  
  r.init(visual_automation=True)
  r.url(link)
    for k in range(80):
        if(k==20 or k==40 or k==60):
            r.wait(2)
        r.dom("window.scrollTo(0,document.body.scrollHeight)")
  r.wait(10)
  html_text = r.dom('''var content=document.body.innerHTML; return content;''')
  with open(i+"html.txt", 'w+',encoding='utf-8-sig') as file_handle:  
          file_handle.write(html_text)_  

When I stared at the automatic page scrolling of the rpa, I found that it could scroll to the end perfectly and save the page content. **But once I zoom the browser page to the lower end of the window**, after a while, I find that the content of the page I saved seems to be defective (that is, the scrolled content of the entire page is **not completely saved**)

**Strangely, when I stared at the rpa page again and did nothing else, he started to write the page content to the txt file completely again.**

I was very confused. In the middle of it, I added the circular r.dom ("window. scrollTo (0, document. body. scrollHeight)") and r.wait

Thanks！

**Comment by kensoh** [comment]
Hi @JJery-web ! Have you found a solution for above use case?

I recall that it might be possible to save directly to PDF in headless mode, or to set a large browser resolution to capture correctly. But it's been a while and I can't remember of a user example to give here. You could also try to use keyboard() function to trigger [pagedown] to the browser to get to the bottom of the page to force it to load completely. (Be sure to visually trigger a click on the browser first to make sure that it is in the foreground to receive the pagedown key)

**Comment by kensoh** [comment]
(closing issue for now, but please feel free to open or share any thoughts or questions)
