### ISSUE TITLE
Cannot run r.init() due an error - try out this solution from another user

### ISSUE THREAD

**Issue by fabio-condez** [tebelorg/RPA-Python#438]
Hi, 
I'm running pop os with python on version 3.9.13.
I installed rpa with pip.

Here is the result when I run the command r.init()

-> r.init()
[RPA][INFO] - setting up TagUI for use in your Python environment
[RPA][INFO] - downloading TagUI (~200MB) and unzipping to below folder...
[RPA][INFO] - /home/user
[RPA][INFO] - done. syncing TagUI with stable cutting edge version
[RPA][INFO] - TagUI now ready for use in your Python environment
[RPA][INFO] - visual automation (optional) requires special setup on Linux,
[RPA][INFO] - see the link below to install OpenCV and Tesseract libraries
[RPA][INFO] - https://sikulix-2014.readthedocs.io/en/latest/newslinux.html
[RPA][ERROR] - following happens when starting TagUI...

The following command is executed to start TagUI -
"/home/user/.tagui/src/tagui" rpa_python chrome

It leads to following output when starting TagUI -
Auto configuration failed
140537093654464:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libproviders.so): libproviders.so: cannot open shared object file: No such file or directory
140537093654464:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
140537093654464:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=providers, path=providers
140537093654464:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=providers
[RPA][ERROR] - unknown error encountered
False

Can you help me find the problem here?
edit: changed username on the logs

**Comment by omegastripes** [comment]
Try workaround from https://github.com/tebelorg/RPA-Python/issues/413

**Comment by kensoh** [comment]
Thanks @omegastripes !

Hi @fabio-condez, the only time I come across this issue is the issue #413 that @omegastripes shared. See if that helps.
