### ISSUE TITLE
Cannot init() the rpa - some ideas to explore and possible solutions

### ISSUE THREAD

**Issue by liuling950201** [tebelorg/RPA-Python#439]
Hi, I was facing an error with init() like this:
partially initialized module 'rpa' has no attribute 'init' (most likely due to a circular import)

But there is no other file named rpa in the folder with my python script.

**Comment by kensoh** [comment]
@liuling950201 is this resolved? I haven't come across this issue. It sounds like for some reason, in your environment, the rpa package cannot be found, and some other packages is loaded instead. Could you try printing __file__ to see where is the rpa file that is being loaded? or try doing import tagui as t and t.init() instead to see if it helps?

**Comment by kensoh** [comment]
(closing issue for now, but please feel free to open or share any thoughts or questions)
