### ISSUE TITLE
r.popup and r.read('page') - pending more details and here's a suggestion

### ISSUE THREAD

**Issue by bailipeng** [tebelorg/RPA-Python#440]
After using r.popup ('xxx '), you can't get the source code of the current page by using r.read ('page'). Can you help me

**Comment by kensoh** [comment]
Hi @bailipeng, from what I recall, to capture page of original page, you must first do r.popup() to reset the focus back to the parent original page. Otherwise r.read('page') will be reading the popup page instead of the parent original page.

**Comment by kensoh** [comment]
(closing issue for now, but please feel free to open or share any thoughts or questions)
