### ISSUE TITLE
I threw this error at runtime - pending more information and finding clues

### ISSUE THREAD

**Issue by Sunywdev** [tebelorg/RPA-Python#441]
2022/12/06 17:45:17 - RPA.handler.ZhiLianRelease - [INFO] | False
[RPA][ERROR] - following happens when starting TagUI...

The following command is executed to start TagUI -
"C:\Users\Administrator\AppData\Roaming/tagui/src/tagui" rpa_python chrome

It leads to following output when starting TagUI -
此时不应有 \RPA\rpa_python.log'。

[RPA][ERROR] - unknown error encountered
2022/12/06 17:45:18 - RPA.handler.ZhiLianRelease - [ERROR] | open chrome error

**Comment by kensoh** [comment]
Hi @Sunywdev is this resolved? It looks like some error with opening Chrome browser.

Is there any information in the rpa_python.log file?

Did a command prompt window popup for rpa package's Chrome backend process?

**Comment by Sunywdev** [comment]
@kensoh yeap,This problem has been solved, because of the garbled code caused by the Chinese path

**Comment by kensoh** [comment]
Thanks @Sunywdev! Appreciate that you take time to share on the root cause :)
