### ISSUE TITLE
[pagedown] pages in the nav bar - try to visually click on the browser first

### ISSUE THREAD

**Issue by EdGrossman** [tebelorg/RPA-Python#442]
Hello,

I'm trying to scroll to the bottom of a Web Page, but clicking and then using  [pagedown] usually scrolls the nav bar rather than the page. I made some sample code to demonstrate. Can anyone point me to a solution?

```
import rpa as r


def main():
    r.init(visual_automation=True)
    r.debug(True)
    r.url('https://www.amazon.com')
    r.click('//*[@id="nav-logo"]')
    r.click(400,400)
    r.keyboard('[pagedown]')
    print()

if __name__ == '__main__':

    main()
```

**Comment by kensoh** [comment]
Hi @EdGrossman I suspect it is because there isn't a visual automation click on the browser yet. The clicking of the logo is a software click which does not make the browser to be in the foreground. You can try to do a r.click('chrome_icon.png') or something to make the web browser to be in the foreground to receive the pagedown key subsequently.

**Comment by kensoh** [comment]
(or visually click on something on the webpage eg r.click('some_logo.png'))

**Comment by kensoh** [comment]
(closing issue for now, but please feel free to open or share any thoughts or questions)

**Comment by hanyuanzhong** [comment]
> Hello,
> 
> I'm trying to scroll to the bottom of a Web Page, but clicking and then using [pagedown] usually scrolls the nav bar rather than the page. I made some sample code to demonstrate. Can anyone point me to a solution?
> 
> ```
> import rpa as r
> 
> 
> def main():
>     r.init(visual_automation=True)
>     r.debug(True)
>     r.url('https://www.amazon.com')
>     r.click('//*[@id="nav-logo"]')
>     r.click(400,400)
>     r.keyboard('[pagedown]')
>     print()
> 
> if __name__ == '__main__':
> 
>     main()
> ```
Hi @EdGrossman you can try adding r.keyboard('[F6][F6]') or r.keyboard('[F6][F6][F6] [F6]') in front of r.keyboard('[pagedown]'), three f6s are the case with bookmarked bars

**Comment by hanyuanzhong** [comment]
But just on windows computers, I haven't found a way on mac os

**Comment by hanyuanzhong** [comment]
Hi @EdGrossman 
I've fixed the problem and in mac you can use r.eyboard ("[esc]")
