### ISSUE TITLE
Closing the browser while the code is running - try to hack something here

### ISSUE THREAD

**Issue by Sinha-Aditya** [tebelorg/RPA-Python#446]
When the code is running and the browser which has pooped up using r.init() is closed manually by the user the code gets halted and the code does not go into the except block (we have used the r.error(True) method to handle the exceptions). If there is a way out kindly suggest.

**Comment by kensoh** [comment]
@Sinha-Aditya oh this is a tricky situation. The rpa process will keep waiting for Chrome to respond back. If Chromes get killed accidentally, the process will keep waiting. If you wish to handle this use case, perhaps you can modify some code around this section. Maybe you can add a timer etc to let the while loop stop after a certain timeout value.

https://github.com/tebelorg/RPA-Python/blob/e6b6812cedd5d80d7f53508397bddf636f9d66ea/tagui.py#L851

**Comment by kensoh** [comment]
(closing issue for now, but please feel free to open or share any thoughts or questions)
