### ISSUE TITLE
Cannot download and open file in Chrome - pending trying download_location()

### ISSUE THREAD

**Issue by GrowUpXin** [tebelorg/RPA-Python#447]
![image](https://user-images.githubusercontent.com/30682583/215978362-bf35addf-30ab-44b6-b908-385130869f7b.png)
ift can not open

**Comment by kensoh** [comment]
@GrowUpXin can you try if changing the download location can help? See here for syntax - https://github.com/tebelorg/RPA-Python/issues/279#issuecomment-877749880

**Comment by kensoh** [comment]
(closing issue for now, but please feel free to open or share any thoughts or questions)
