### ISSUE TITLE
Google Colab sample notebook hangs at r.init() - updated notebook [fixed]

### ISSUE THREAD

**Issue by rainyraina** [tebelorg/RPA-Python#448]
I tried running both RPA for Python Colab notebooks (headless and upgraded non-headless) without making any changes. It hangs at r.init(headless_mode = True) and r.init() respectively. Can you advise me on this? Thank!

**Comment by kensoh** [comment]
Hi @rainyraina thanks for raising this! I've run into this recently and thought it was an isolated issue. Looks like something has been broken, probably due to a change in version in any of the components that Google Colab is using. Will dig further when I get some time. Possible software components could be Xvfb, the Chromium browser, the Ubuntu version, etc

**Comment by rainyraina** [comment]
Hi @kensoh thanks for looking into this issue! I've successfully run the headless mode notebook by referring to: https://stackoverflow.com/questions/51046454/how-can-we-use-selenium-webdriver-in-colab-research-google-com
Turns out Google collab was upgraded and since Ubuntu 20.04+ no longer distributes chromium-browser outside of a snap package, you need to install a compatible version from the Debian buster repository.

**Install chromium outside of snap package:**
%%shell
# Ubuntu no longer distributes chromium-browser outside of snap
#
# Proposed solution: https://askubuntu.com/questions/1204571/how-to-install-chromium-without-snap

# Add debian buster
cat > /etc/apt/sources.list.d/debian.list <<'EOF'
deb [arch=amd64 signed-by=/usr/share/keyrings/debian-buster.gpg] http://deb.debian.org/debian buster main
deb [arch=amd64 signed-by=/usr/share/keyrings/debian-buster-updates.gpg] http://deb.debian.org/debian buster-updates main
deb [arch=amd64 signed-by=/usr/share/keyrings/debian-security-buster.gpg] http://deb.debian.org/debian-security buster/updates main
EOF

# Add keys
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys DCC9EFBF77E11517
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 112695A0E562B32A

apt-key export 77E11517 | gpg --dearmour -o /usr/share/keyrings/debian-buster.gpg
apt-key export 22F3D138 | gpg --dearmour -o /usr/share/keyrings/debian-buster-updates.gpg
apt-key export E562B32A | gpg --dearmour -o /usr/share/keyrings/debian-security-buster.gpg

# Prefer debian repo for chromium* packages only
# Note the double-blank lines between entries
cat > /etc/apt/preferences.d/chromium.pref << 'EOF'
Package: *
Pin: release a=eoan
Pin-Priority: 500


Package: *
Pin: origin "deb.debian.org"
Pin-Priority: 300


Package: chromium*
Pin: origin "deb.debian.org"
Pin-Priority: 700
EOF

**Updated code:**
# setup RPA environment by installing PHP, Chromium and RPA for Python
!apt-get update; apt-get install chromium chromium-driver; pip install rpa
# run r.setup() to download TagUI, modify to run Chromium browser and as root user
import rpa as r
r.setup(); 
r.dump(r.load('/root/.tagui/src/tagui').replace('"google-chrome"', '"chromium"').replace('--disable-gpu', '--disable-gpu --no-sandbox'), '/root/.tagui/src/tagui')
# run sample web automation workflow on RPA for Python GitHub page
# r.init() headless mode as there is no display monitor for Chrome
# r.close() not needed at the end since Colab will self-destruct

r.init(headless_mode = True)
r.url('https://www.google.com')
r.type('//*[@name="q"]', 'decentralization[enter]')
print(r.read('result-stats'))
r.snap('page', 'results.png')

# validate Google search results image snapshot by displaying it
from IPython.display import Image; Image('results.png')

# [OPTIONAL] with Chrome browser you can download RPA output files to computer or phone
from google.colab import files; files.download('results.png')

# PS1 - use wget command to upload csv datafile or other files for your RPA to use
# !wget https://raw.githubusercontent.com/kelaberetiv/TagUI/master/flows/samples/form_data.csv

# PS2 - other ways to upload data to Google Colab cloud, for example files.upload()
# https://towardsdatascience.com/3-ways-to-load-csv-files-into-colab-7c14fcbdcb92

**Comment by kensoh** [comment]
Thanks @rainyraina for sharing your solution here!! The installation for Chromium in your solution is cool, but overly complicated. I was tinkering whether I can install Chrome instead. I tried this in the following notebook, but init() hangs. Would you be able to kindly have a look and tell what's missing to make it work for Chrome on Colab's Ubuntu version?

https://colab.research.google.com/drive/1or8DtXZP8ZxJYK52me0dA6O9A1dXKKOE#scrollTo=kl58MzRLyNgb

PS - I noticed that you installed chromium-driver in your solution, can you share why is that needed?

**Comment by kensoh** [comment]
Issue resolved thanks to you @rainyraina!

I opted to use Chromium since it works. Have updated readme to point to the new working Colab notebook at below link - 

https://colab.research.google.com/drive/1or8DtXZP8ZxJYK52me0dA6O9A1dXKKOE?usp=sharing

**Comment by kensoh** [comment]
Hi @rainyraina! I'm introducing the following promotion to users who report bugs or feature suggestions. You reported on the replicable bug on Google Colab not working anymore for the rpa package demo, could you kindly let me know how to contact you? I would like to share my appreciation by getting a 200 USD gift card for you, from your preferred merchant.

You can email me your contact at opensource@tebel.org and ping me here so that I can check the mailbox.

> As a bonus and token of my appreciation, any new bug reported will be appreciated with a 200 USD gift card from your preferred merchant. Any feature suggestion accepted will be appreciated with a 100 USD gift card.

https://github.com/tebelorg/RPA-Python#use-cases

**Comment by rainyraina** [comment]
Hi Ken Soh,

I've sent my contact at ***@***.*** Thank you :)

Best regards,
Raina

**Comment by kensoh** [comment]
@rainyraina, just got your online purchase screenshot, sent!

Thanks for raising the bug report, enjoy the US$200 gift 😄 

![bug_report](https://user-images.githubusercontent.com/10379601/228242606-fc21fe3a-9a63-484d-8ecf-bfbad798ea53.png)

**Comment by rainyraina** [comment]
Received with thanks!!

**Comment by kensoh** [comment]
Attaching a copy of the working updated Colab notebook here as backup - [RPA_for_Python_x_Colab.ipynb.zip](https://github.com/tebelorg/RPA-Python/files/11129665/RPA_for_Python_x_Colab.ipynb.zip)
