### ISSUE TITLE
TagUI download error on init() - likely blocked by intranet proxy, check proxy 

### ISSUE THREAD

**Issue by Ambarella-VE** [tebelorg/RPA-Python#449]
We have been trying (different users/computers) to run `r.init()` and we always get the same error `[RPA][ERROR] - failed downloading from https://github.com/tebelorg/Tump/releases/download/v1.0.0/TagUI_Windows.zip...` and noticed that url does not longer exist. I found the updated file from TagUI docs but I don't know where to save it so rpa doesn't try to download it. Also, having the url updated would be very helpful. Thanks.

**Comment by kensoh** [comment]
Hi @Ambarella-VE can you check your intranet proxy or try another computer like your personal laptop? The link https://github.com/tebelorg/Tump/releases/download/v1.0.0/TagUI_Windows.zip is valid and I can download it from the web browser. It might be your network policy not allowing automated download from github.com and its associated endpoints.

**Comment by Ambarella-VE** [comment]
Hi @kensoh, Thanks for your response. Isn't it possible to save it manually? and avoid the auto download?

**Comment by shubham303** [comment]
Hi Everyone, 
I am also facing the same problem, @Ambarella-VE is facing

**Comment by kensoh** [comment]
Thanks @Ambarella-VE and @shubham303, it is possible to avoid auto-download but you'll have to modify the tagui.py script to handle that. Whenever there is references for the string "download(" manually download and comment off that line.

Alternatively, the recommended way is to use a computer or proxy that has the internet access to auto-download from github.com domain, and use pack() to generate a zip file, which you can copy over to the restricted network PC to use.

See here for the steps to use pack() - https://github.com/tebelorg/RPA-Python/issues/36#issuecomment-543670292
