### ISSUE TITLE
failed to move mouse by hover() function

### ISSUE THREAD

**Issue by taoheihei** [tebelorg/RPA-Python#454]
hi ,bro
I met a non-standard dropdown, Initially I tried to use click() to expend it but failed, then I found it may trigger with mousedown
then  I try to use 
```
r.hover('//div[contains(@class,"ecom-g-select-single")]')
r.mouse('down')
r.wait(1)
r.mouse('up')
```
but the mouse does not move when hover() is running 
so what can I do for the problem ablove? thanks

**Comment by kensoh** [comment]
Hi @taoheihei bro, looks like you have found a solution! r.hover() if you give a XPath identifier it will only simulate a software move to that web element. To make a real move you can use r.hover('dropdown_option.png') before using r.mouse on it. You can also using r.click('dropdown_option.png') directly on it. Lastly, there might be a viable XPath to click on it directly. (You can try out SelectorsHub Chrome extension to read the XPath)
