### ISSUE TITLE
Hello! How do I get cookies - use tagui_user_profile folder to store browser state

### ISSUE THREAD

**Issue by kinglei88** [tebelorg/RPA-Python#456]
Hello! How do I get cookies

**Comment by kensoh** [comment]
The package is designed to replicate normal human user activities, thus does not actively store cookies.

However, if you really want to keep the state and login status, you can do the following -

print(r.tagui_location()) to get base location of TagUI engine. There is a tagui folder for Windows and .tagui folder for Linux and Mac in that folder. Under that folder there is the folder src/chrome/tagui_user_profile which saves the Chrome browser state. You can use that folder or keep a copy or restore from your copy, to replicate the state just like having cookies.

**Comment by kensoh** [comment]
Tagging @kinglei88. Your profile picture looks like Wang Wang biscuit
