### ISSUE TITLE
The time between two subsequent clicks is very slow - try out turbo mode

### ISSUE THREAD

**Issue by uditijain** [tebelorg/RPA-Python#457]
Hi, ive been using this package for quite some time now and found it to be very handy.
But now im stuck at an issue, we are trying to download some files in a loop from a website which need to select dropdown values one by one and then save file for that value.
The point to notice here is that the time between two subsequent clicks is significant. Is there a way to reduce this time so that the process becomes faster. In the below code, the time between 1st Click and Refresh click can be sometimes 10 secs as i tried to print there individual click times also

`        while j < rtoCount:

            print("j:"+j.__str__())
            #select RTO
            r.click('//*[@id="selectedRto"]/div[3]/span')
            r.click('//*[@id="selectedRto_' + j.__str__() + '"]')

            # final check for rto selection
            selectedrto = r.read('//*[@id="selectedRto_label"]')
            rtoToBeSelected = r.read('//*[@id="selectedRto_' + j.__str__() + '"]')
            while selectedrto != rtoToBeSelected:
                r.click('//*[@id="selectedRto"]/div[3]/span')
                r.click('//*[@id="selectedRto_' + j.__str__() + '"]')
                selectedrto = r.read('//*[@id="selectedRto_label"]')
            print("rto clicked:"+datetime.now().time().__str__())
            #click refresh
            r.click('//span[text()="Refresh"]')
            print("refresh clicked:" + datetime.now().time().__str__())`

**Comment by kensoh** [comment]
Whether you are using web automaton or visual automation, you can use the turbo mode to speed things up to 10X faster. However, note that websites and applications are not designed to handle speed faster than normal human actions. So your automation might be flagged as automation and get blocked from accessing the website.

See here for more on turbo mode - https://github.com/tebelorg/RPA-Python/issues/297

**Comment by kensoh** [comment]
Also tagging @uditijain

**Comment by uditijain** [comment]
Hi, im having some basic doubts while running browser automation. When my browser is in foreground, it downloads like 4 files in a minute avg, but when i try to keep it running in the background and do some other work simultaneously, the process only downloads 1 or 2 files. This Behavior is really strange but i would like to know the cause or python script runs slow in background?

**Comment by kensoh** [comment]
If you mean turbo mode, that mode is not reliable at all because websites are all not designed to work with super human speed. For normal mode, depending on your PC and what other work that you are doing, it might slow down the Python or rpa engine's process. You could add other checks in your steps to ensure that something is ready and done, before doing the next step.
