### ISSUE TITLE
How to wait for Loader to disappear - see these examples of possible ways

### ISSUE THREAD

**Issue by uditijain** [tebelorg/RPA-Python#458]
Hi , my solution needs to download a file after clicking refresh. Before i download, there is a loader for which we need to wait. The loader is animated. Please guide how to wait till the loader disappear and then download the file

**Comment by kensoh** [comment]
A possible design structure could be the following. Probably the 2nd way is better because for websites, an element may could be not visible but still exists in the html DOM structure.
```py
while r.exist('web_identifier'):
    wait()
```
```py
while r.exist('image_identifier.pngt'):
    wait()
```

**Comment by kensoh** [comment]
Above will keep looping until the loader disappears. Tagging @uditijain

**Comment by uditijain** [comment]
Ive already tried this with a png screenshot of the loader but the case is that this loader is animated gif

**Comment by kensoh** [comment]
Can you share the screenshot of the gif? The visual automation supports transparent .png files. Maybe there is some "fixed/static" part of the loader that can be used.

**Comment by kensoh** [comment]
This is quite tricky. Is there some unique image in the background that you can use to check, so that you know that the loader has disappeared? If yes, you can do the following to wait up to 5 minutes for the background to show up when loader is gone.

```py
r.timeout(300)
r.hover('background.png')
```

**Comment by uditijain** [comment]
i found a workaround for the above loader. Instead of checking for the animated loader, i picked its parent <div> and identified one of its attributes is busy when loader is there. 
`            while loaderExists:
                if r.present('//*[@id="combTablePnl" and @aria-busy="true"]'):
                    loaderExists = True
                    print("loader  exist")
                else:
                    loaderExists = False
                    print("loader does not exists")
            print("****************")`

**Comment by kensoh** [comment]
Nice solution @uditijain , thanks for sharing back!
