### ISSUE TITLE
Will r.click() work when screen is sleep or locked - visually nope, web id maybe

### ISSUE THREAD

**Issue by uditijain** [tebelorg/RPA-Python#459]

**Comment by kensoh** [comment]
I heard that for visual automation, it requires a logged in screen that is active, otherwise there is no display to automate visually. For normal web automation it might still work but this is not tested or part of the use case for the package.

**Comment by kensoh** [comment]
Also tagging @uditijain

**Comment by uditijain** [comment]
Yes visual automation does not happen when screen is locked, as for browser automation it works for a minute after a screen is locked and then this also starts giving [RPA Error]

**Comment by kensoh** [comment]
I see.. Gotcha. Yeah this isn't a tested and planned use case for the package. Closing issue but feel free to comment more!
