### ISSUE TITLE
Visual automation无法正常运行 - pending more details and replication steps

### ISSUE THREAD

**Issue by cylconee** [tebelorg/RPA-Python#460]
一运行到visual automation函数就卡住，一开始是可以的，但是安装完别的环境就无法跑这个代码了，debug卡在了[RPA][2] - exist_result = exist('shdxjwc.png').toString()

**Comment by cylconee** [comment]
这是我目前在做的一个毕业设计，希望能得到及时的回答，不是知否能加一下vx：18968312556

**Comment by cylconee** [comment]
就是运行到打开网址后。不报错也不继续运行，windows系统，画面调整到%推荐了
代码如下
import tagui as t

t.init(visual_automation = True)
t.url('https://www.baidu.com')
t.type('wd', '上海大学教务处[enter]')
t.click('shdx.png')
t.close()

**Comment by kensoh** [comment]
Hi @cylconee what is your OS (Windows, Mac, Linux)? You mentioned that after setting up in another environment it does not work anymore but before it was working. Can you tell me more what do you mean by 安装完别的环境 ?

Possibly something has gone missing or not copied properly. The visual automation requires Java JDK and SikuliX. Java JDK you can install manually from Amazon Corretto website. For SikuliX the package should automatically download and install on first run.
