### ISSUE TITLE
How to click on dynamic desktop app dropdown items - some thoughts and ideas

### ISSUE THREAD

**Issue by uditijain** [tebelorg/RPA-Python#461]
How to click on dropdown items one by one on a desktop application window since there is no xpath like browser. And the dropdown items change so image would also not work here. Please guide

**Comment by kensoh** [comment]
@uditijain can you show screenshot of how the dropdown and its options look like?

If you don't know the dropdown items to choose, how do you decide what to choose?

Can typing to select the dropdown work? If yes, can try using keyboard() function (after doing a click() visually on the web browser to make it in the foreground and in focus).

**Comment by uditijain** [comment]
hi I have to click on dropdown items one by one , perform some activity and then return to dropdown to pick next item and so on. This will be working in a loop. so we need to select all dropdown items whatever are present. Please refer the screenshot. The items can change everyday
![image](https://user-images.githubusercontent.com/103426165/231660368-a0ce60aa-9484-448e-bbf6-a0fb58a59585.png)

**Comment by kensoh** [comment]
I see, I get what you mean. One way is to access by XPath syntax for nth occurrence but it is hard to give example if the website  is not publicly available. For eg (XPath)[1] and (XPath)[2] to mean the first option and second option.

https://stackoverflow.com/questions/4007413/xpath-query-to-get-nth-instance-of-an-element

May need to do the initial click first to show the list, and use count('XPath') to get the number of items, before using click('(XPath)[n]') to click on the nth item. And just loop everything within a for loop.

**Comment by uditijain** [comment]
Hi, As mentioned before, this is not a website. Actually i need to take a remote desktop connection, login into it and open this desktop application there and perform automation one by one for everydrop down item

**Comment by uditijain** [comment]
that is okay but how would we know the count of the children of this dropdown. Any ideas

**Comment by uditijain** [comment]
we cant rely on the pixels as the dropdown items may vary in count. Please provide a way to count the number of dropdown items with keyboard keys , once we are able to get the count we can press [down] button to iterate through them but we need the count

**Comment by marcelocecin** [comment]
could you share a video with the human interaction of the dropdown with the keyboard?

**Comment by kensoh** [comment]
No ideas from me. This scenario is a desktop application with unknown number of dropdown options and unknow dropdown values. I'm afraid you may have to try out other tools..

**Comment by kensoh** [comment]
I don't think this is even doable with expensive commercial RPA software, so I don't think it's likely you can do it with rpa package. The two challenges of remote desktop connection combined with unknown dropdown number and values make it hard to design any logic to automate the process.

**Comment by uditijain** [comment]
umm, i know my use case is complex. I was thinking what about using tab to navigate to the concerned dropdown, press down key to open it. Is there anyway to get the text of this element being selected with down key, in this way we can create a list of the dropdown items and check if any is repeating, that way we can get the count given that we are able to read the context of the dropdown item without any image reference or text reference since this is dynamic. Any ideas

**Comment by kensoh** [comment]
Oh yes, if the dropdown box is at a specific location, you can use r.read(x1, y1, x2, y2) to use OCR to try to convert that text in the desktop client or Citrix window into text. You can move the mouse and use r.mouse_xy() to get the coordinates.

https://github.com/tebelorg/RPA-Python#api-reference
