### ISSUE TITLE
Visual automation is not working on Colab but worked before - pending details

### ISSUE THREAD

**Issue by bettyyy** [tebelorg/RPA-Python#463]
Hi @kensoh, hope you are doing well!

I have been using this colab notebook (https://colab.research.google.com/drive/1or8DtXZP8ZxJYK52me0dA6O9A1dXKKOE?usp=sharing) to run my personal rpa project but I encountered a problem when using visual automation lately. I hope you could help me with this issue!

I have installed OpenCV and Tesseract in this colab notebook and ran the program by setting r.init(visual_automation = True). It ran successfully two weeks before! However, when I try to run the same notebook again these days, it hangs at the r.keyboard command which could be shown in the log below. It is weird that the visual automation is worked 2 weeks before but not now. I hope you could give me some insight on solving this problem. Thank you very much in advance!

sample code:
r.init(visual_automation = True)
r.url('https://duckduckgo.com')
r.type('//*[@name="q"]', 'decentralisation[enter]')
r.snap('page', 'results.png')
r.keyboard('[pagedown]')
r.close()

log:
[RPA][STARTED]
[RPA][0] - listening for inputs
[RPA][1] - https://duckduckgo.com/
[RPA][1] - listening for inputs
[RPA][2] - exist_result = exist('//*[@name="q"]').toString()
[RPA][2] - listening for inputs
[RPA][3] - dump exist_result to rpa_python.txt
[RPA][3] - listening for inputs
[RPA][4] - type //*[@name="q"] as decentralisation[enter]
[RPA][4] - listening for inputs
[RPA][5] - snap page to results.png
[RPA][5] - listening for inputs
[RPA][6] - keyboard [pagedown]

**Comment by kensoh** [comment]
@bettyyy can you share the contents of the log file below?
`r.tagui_location() + '/.tagui/src/tagui.sikuli/tagui.log'`

Could you also share your Colab notebook so that I can see what other possible potential causes of the error would be. Usually if something that is working stops working, then at least one of the components in the process has changed. Perhaps website, perhaps browser, perhaps middleware etc.

The visual automation mode is not tested for Linux and Colab, and requires installing OpenCV and Tesseract, so I won't say that using the package this way is natively supported and tested for rpa package.

**Comment by bettyyy** [comment]
@kensoh thank you so much for your reply! 
The mentioned log file '/.tagui/src/tagui.sikuli/tagui.log' could not be read:(
![tagui_log_error](https://user-images.githubusercontent.com/17765156/232695863-3959eaf2-748a-45dc-96c4-b44e6b6b6c21.PNG)

I used the Colab notebook shared by you (https://colab.research.google.com/drive/1or8DtXZP8ZxJYK52me0dA6O9A1dXKKOE?usp=sharing) and just add two lines to install OpenCV and Tesseract without other lines added. The visual automation was working before. 

Lines added in the Colab notebook:
_!apt-get install python3-opencv; apt install tesseract-ocr;_

![rpa_for_python_colab_nb](https://user-images.githubusercontent.com/17765156/232707832-285239fb-93c9-45cf-abcb-5f45d9133765.PNG)

**Comment by kensoh** [comment]
@bettyyy you can use the following to show the contents of the tagui.log file -

![image](https://user-images.githubusercontent.com/10379601/232774850-d6f8a7dc-7031-493d-ab0e-76c0d4cde361.png)

**Comment by bettyyy** [comment]
@kensoh Got it!
![image](https://user-images.githubusercontent.com/17765156/232950312-2975f2be-1b4b-436b-8e5a-31b7801cb5ac.png)

**Comment by kensoh** [comment]
@bettyyy above looks like some java setup or installation problem on Google Colab. Can you Google the error to see if anyone else have the same problem and a solution?

I can't Google because above is a screenshot and can't copy out the error message.

**Comment by bettyyy** [comment]
@kensoh Sure! Thx a lot for your help!
