### ISSUE TITLE
Problems when installing tagui in python - likely due to Python incorrect usage

### ISSUE THREAD

**Issue by eduardolc21** [tebelorg/RPA-Python#464]
After paste this code:

import rpa as r
r.init()
r.url('https://duckduckgo.com')
r.type('//*[@name="q"]', 'decentralisation[enter]')
r.wait() # ensure results are fully loaded
r.snap('page', 'results.png')
r.close()

I am thrown this error: **AttributeError: partially initialized module 'rpa' has no attribute 'init' (most likely due to a circular import)**

**Comment by kensoh** [comment]
@eduardolc21 I believe this is likely a Python usage issue. Do you have a rpa.py file in the same folder or did you name your script rpa.py? If yes, you are asking Python to import your rpa.py instead of the rpa package as local file takes precedence!

**Comment by eduardolc21** [comment]
@kensoh thanks for your prompt reply and help, my jupyter filename was tagUI and it was the first time in this computer I used it.
I solved it with the import of: 
"import tagui as t"
