### ISSUE TITLE
Stuck up on opening browser - try these, perhaps company network blocking

### ISSUE THREAD

**Issue by itsmetofee** [tebelorg/RPA-Python#467]
Hi, I'm trying to do an automation, but I'm stuck up on this part. I wait almost an hour but still nothing happens. please give me some advice
![image](https://user-images.githubusercontent.com/131782686/234297807-fe929393-60f8-442d-b621-5a37432a87ba.png)

**Comment by itsmetofee** [comment]
is there anything that needs to reinstall? or I missed something to install?

**Comment by kensoh** [comment]
@itsmetofee can you try with r.debug(True) ? Also, if you are using Windows, is there a Chrome Engine command prompt window and what's shown in that window? The only reason I can think of is possibly some network policy in your company that blocks connecting to Chrome. There is an infinite loop to try to connect to Chrome on 9222 port using websocket. If that connection is blocked by network, then it can hang forever.
