### ISSUE TITLE
Error Handling for block of code - use r.error(True) and Python's try-catch

### ISSUE THREAD

**Issue by uditijain** [tebelorg/RPA-Python#468]
Hi Kensos, thanks for supporting us with our queries everytime.
I have one more. Like i was reading the documentation and some closed topics also where people have mentioned how we can check for every click and then handle it in else part if error occurs. I think this approach is okay when you have like less number of clicks. What if i want to handle this for an entire block of code. Like while perfoming browser automation using xpath, if the net goes down our clicks would start to fail one by one. Im looking for a solution where our code can detect catch that click failure immediately and wherever in the code it happens. My code runs for 5 hrs and there are number of clicks in between and i think coding if-else at every step is not a feasible solution

**Comment by kensoh** [comment]
Hi @uditijain! :wave: there is a standard Python try-catch feature introduced last year which you can set r.error(True) to handle any failed step as exception. See below example where you can handle a group of steps, decide how to handle accordingly

https://github.com/tebelorg/RPA-Python/issues/299#issuecomment-1110361923
