### ISSUE TITLE
RPA vs Selenium for Web Scrapping? - do the same with much lesser effort

### ISSUE THREAD

**Issue by mimranarif777** [tebelorg/RPA-Python#469]
Hi, Can I use RPA with same comfort and convenience for web scrapping without need to use Selenium?

**Comment by LucasValentimCamara** [comment]
As far as I know, you can easily do it. RPA have all the tools you need to web scraping.

**Comment by kensoh** [comment]
Thanks @LucasValentimCamara! @mimranarif777 i believe so, it takes much lesser lines of code to do the same thing using RPA package vs using Selenium. Selenium is primarily designed for web developers and test automation folks, so there are a lot of features, parameters and settings that you need to work with to get something simple done. RPA package is built for ordinary busy Python folks who wants the shortest path to get to their outcome, whether for work or personal use case.
