### ISSUE TITLE
 Close specific tab of a site - use keyboard() or dom() + JavaScript close()

### ISSUE THREAD

**Issue by Fugimura** [tebelorg/RPA-Python#470]
I have a website that opens a secondary page after selecting a specific button. The point is, I would like to close this page through rpa without needing to use keyboard commands. Something like r.close(url=address), I think it's more assertive. Thanks

**Comment by kensoh** [comment]
Hi @Fugimura, I'm afraid that there isn't a direct function to allow closure of a tab, but there is a frame() function to explicitly interact with a tab and the dom() function which you can combine to issue tab closure without using keyboard().

See this example:

```py
r.init()
r.url('https://tebel.org')
r.click('About')
r.wait()

# specify a unique part of the URL that you want to interact with, so rpa package knows which tab you want
r.popup('about_tebel')

# use javascript close() command and dom() function to send custom javascript code to browser to close tab
r.dom('close()')
```
