### ISSUE TITLE
Support using Edge browser? - possible but locally modifying a couple of lines

### ISSUE THREAD

**Issue by yhyu13** [tebelorg/RPA-Python#471]
Hi, Maybe a stupid question, how can I use Edge, or any other chromiunm based browser instead of chrom.exe?

**Comment by kensoh** [comment]
Hi @yhyu13 yes this is doable by modifying a few lines in tagui or tagui.cmd file used in the TagUI RPA engine that this package is built on. But that is not recommended as most websites are tested on Chrome and that offers best compatibility.

If you really wants to hack this let me know your OS and I can guide you how to make the local modification of a couple of lines. But note that any local hack will be overwritten if you upgrade this package in the future.

**Comment by yhyu13** [comment]
> Hi @yhyu13 yes this is doable by modifying a few lines in tagui or tagui.cmd file used in the TagUI RPA engine that this package is built on. But that is not recommended as most websites are tested on Chrome and that offers best compatibility.
> 
> If you really wants to hack this let me know your OS and I can guide you how to make the local modification of a couple of lines. But note that any local hack will be overwritten if you upgrade this package in the future.

I am using Ubuntu 22.04. If I made my local modification, I will need to built rpa locally instead of install from pypl, right?

**Comment by kensoh** [comment]
You don't need to build locally at all. The modifications are in some bash scripts. So once you modified you can run.

The only drawback is in future rpa versions, when you upgrade you will lose the changes.

**Comment by kensoh** [comment]
The file to modify is the .tagui/src/tagui file under the folder r.tagui_location()

**Comment by kensoh** [comment]
I can't remember the specific lines to modify, but if you are keen, I can try to look into it and advise.

There are just a couple of lines change I think...

**Comment by kensoh** [comment]
tagging @yhyu13

**Comment by kensoh** [comment]
Closing issue for now but do let me know if you are keen to make the local modification then i will try to point out to you which lines to change.
