### ISSUE TITLE
Port of driver mixed with debug port of chrome - port can be changed here

### ISSUE THREAD

**Issue by zailaib** [tebelorg/RPA-Python#472]
![image](https://github.com/tebelorg/RPA-Python/assets/10792685/7b3b3909-4944-4efa-a3d1-184b6cd881d8)

**Comment by kensoh** [comment]
@zailaib not sure what library you are using but above has nothing to do with Python rpa package and the TagUI RPA engine it uses. By default the TagUI engine uses port 9222 websocket to control and read data from Chrome browser. You can adjust it by changing the tagui file or tagui.cmd file under the src folder mentioned in the TagUI folder in your other issue on browser size.
