### ISSUE TITLE
Search subfolder for images? - yes Python code, use this suggestion by Lucas

### ISSUE THREAD

**Issue by joshglenn** [tebelorg/RPA-Python#475]
Hello. I've written a tool that uses RPA-Python... it works well, thank you.

Is there a way to place my images in a subfolder and the r.click( and other functions still be able to find the images?

**Comment by LucasValentimCamara** [comment]
Hi!

Yes, you can use r.click(), you just need to put the path to your image, like:

>  r.click('subfolder/image.png')
