### ISSUE TITLE
snap() can't capture elements off initial page (Chromium has changed) [fixed]

### ISSUE THREAD

**Issue by JS-code-dev** [tebelorg/RPA-Python#479]
Hi, I am looking to snap images that could be potentially off the initial screen and requires scrolling.

I am using t.hover to scroll to the image, then use t.snap to take a capture of the image. However it seems like the capture of the off screen element always turns up blank even though it has already scrolled to the element.

Refer to my sample code in Python:
```
t.url('https://www.google.com/search?q=test')
t.hover('(//div[@role="navigation"])[2]')
t.snap('(//div[@role="navigation"])[2]', 'test.png')
```

Is this a bug? Or is there a way to overcome this?

**Comment by Vic-Lau** [comment]
When you run the RPA process, it will open a new chrome browser, but I run your RPA process, I can't find your xpath.

![error](https://github.com/tebelorg/RPA-Python/assets/21170982/a1737bf5-927b-4b03-9cc4-142c4756a70e)

So, you can try this xpath: `//*[@id="tsf"]/div[1]/div[1]`, you will get a png like this:

![test](https://github.com/tebelorg/RPA-Python/assets/21170982/659c9411-7a34-4ebb-9f47-8c041e7168b7)

> Hi, I am looking to snap images that could be potentially off the initial screen and requires scrolling.
> 
> I am using t.hover to scroll to the image, then use t.snap to take a capture of the image. However it seems like the capture of the off screen element always turns up blank even though it has already scrolled to the element.
> 
> ```
> t.url('https://www.google.com/search?q=test')
> t.hover('(//div[@role="navigation"])[2]')
> t.snap('(//div[@role="navigation"])[2]', 'test.png')
> ```
> 
> Is this a bug? Or is there a way to overcome this?

**Comment by JS-code-dev** [comment]
Hello,

You are searching for the wrong xPath. The xPath is ***@***.***="
navigation"])[2]

[image: image.png]

The snap works if the element is on the main screen, but if it needs
scrolling to reach the element, snapping does not work.

**Comment by Vic-Lau** [comment]
yes, scrolling will get this bug, I delete the reply.

**Comment by kensoh** [comment]
@JS-code-dev @Vic-Lau I can replicate. I get the following from the logs. The log output looks correct, but somehow a blank image is returned. It's been a while since I created this function so I don't remember if it supports taking snapshot outside of the initial view. Likely this was working but along the way it might have stopped working with newer Chromium because below log output looks correct. I'll check more and update back.

```
[tagui] INPUT  -
[30] {"id":30,"method":"Page.captureScreenshot","params":{"format":"png","quality":80,"clip":{"x":180,"y":559,"width":652,"height":56,"scale":1},"fromSurface":true}}
[tagui] OUTPUT -
[30] {"id":30,"result":{"data":"iVBORw0KGgoAAAANSUhEUgAAAowAAAA4CAYAAAB396mcAAABL2lDQ1BTa2lhAAAokX2QPUsDQRCGH0NQonYqprC4RrBRc1FzBGzyocHCJlGIFsLlcgQxicflRHux80dYipWF/0SwsrDRWghYWPneXXEBjbPMzrPvDjM7C6kssnQOev3Ar9fKRvPo2Jh6Y0IrMtsZeIw3ZX29xLnPq//kjbNM2x04ip/ywFdzlWyL5zsxX4Xcivk25MvAC8R3IfsH9Yr4SbzSGeHWCDueH+a/ird73QsneTezbv+wodiUL1HjXKtDF5d1Gpxxii0qYVKkwIZ8l01FkwpVLEVL5wpldnRTIqe7KnntWxEXpVrhf8YtnRuwNGfmO9F6Q3icBmM/0ZZPIDsJ9x+JlvyxZ/t2JKXlKbcMwwWN8gBz7zBzLXUxqvz3rMavWQ326OOwJsrr3SaFHwYiSrMQwHDKAAABHElEQVR4nO3WMQHAIBDAwFL/nh8FZIXhTkHGrJmZDwAADv7bAQAAvM0wAgCQDCMAAMkwAgCQDCMAAMkwAgCQDCMAAMkwAgCQDCMAAMkwAgCQDCMAAMkwAgCQDCMAAMkwAgCQDCMAAMkwAgCQDCMAAMkwAgCQDCMAAMkwAgCQDCMAAMkwAgCQDCMAAMkwAgCQDCMAAMkwAgCQDCMAAMkwAgCQDCMAAMkwAgCQDCMAAMkwAgCQDCMAAMkwAgCQDCMAAMkwAgCQDCMAAMkwAgCQDCMAAMkwAgCQDCMAAMkwAgCQDCMAAMkwAgCQDCMAAMkwAgCQDCMAAMkwAgCQDCMAAMkwAgCQDCMAAMkwAgCQDCMAAMkwAgCQDCMAAGkDitEEbJUz5HAAAAAASUVORK5CYII="}}
```

**Comment by kensoh** [comment]
@JS-code-dev @Vic-Lau I've fixed the issue. Can you try again with v1.49 to see if it works now, no need to do hover() first, it will auto-move to the web page element before taking screenshot.

There is some change in Chromium behaviour so the old snapshot code no longer works with the browser. In v1.49 I've updated logic to use absolute x,y coordinates instead of relative coordinates and it works now.

**Comment by kensoh** [comment]
@JS-code-dev , this year I'm running a promotion if a user reports a new bug, there is 200 USD gift voucher. Could you pick a vendor you like so that I can get a gift voucher to appreciate reporting this bug and benefit other users of this package?

Thank you very much for raising this issue!!

**Comment by kensoh** [comment]
Adding on, any online vendor will do, does not need to be in USD. Roughly 200 USD value will do.

If more it is also ok, you can cover the rest of the cost and I can cover the 200 USD. Thank you 🙏

**Comment by JS-code-dev** [comment]
@kensoh I have verified that snapping off-page works as intended without the need for hover! Should I go ahead and close this then? Also, that's very generous of you for the 200 USD! I will pm you regarding the details! Thank you :)

**Comment by kensoh** [comment]
It's ok can leave issue open for a while so users with the same problem will know to upgrade their rpa package version.

You can email me at opensource@tebel.org thank you for raising this issue! So I know Chromium has changed and broke the snap() function.

**Comment by kensoh** [comment]
@JS-code-dev just give me a shout here after you've made your purchase and email me at opensource@tebel.org (By the way do you have TransferWise / Wise? Paypal has additional 15% cost when I recently transfer to a China user for raising a good feature suggestion)

**Comment by JS-code-dev** [comment]
@kensoh I am situated in Singapore and have dropped you an email with a suggestion. We can discuss over there. Thanks again.

**Comment by kensoh** [comment]
Oh great @JS-code-dev! I'm from Singapore and I can transfer you the equivalent value of 200 USD in SGD.

**Comment by JS-code-dev** [comment]
Oh! Cool! I have emailed you details for the transfer. Let me know if that works out. @kensoh

**Comment by Vic-Lau** [comment]
@kensoh snap() is good and it doesn't need hover().

**Comment by kensoh** [comment]
(sent gift card payment to @JS-code-dev 🙌)
