### ISSUE TITLE
Visual automation on different desktops on Mac or Windows - use vision()

### ISSUE THREAD

**Issue by niuniu132** [tebelorg/RPA-Python#481]

**Comment by kensoh** [comment]
Hi @niuniu132 I think so! By default the package uses the primary display. But through using vision() function, you can use custom SikuliX commands to perform actions on the 2nd or 3rd monitors. See below link for some examples. Essentially, you want to use vision() with Screen(1) for 2nd monitor and Screen(2) for 3rd monitor.

The image filename requires to be full path.

https://github.com/tebelorg/RPA-Python/issues/252#issuecomment-844277454

**Comment by kensoh** [comment]
Closing issue for now but do let me know if u run into blocker using vision() to automate a different monitor!
