### ISSUE TITLE
How to navigate to previous page without visual automation - use dom()

### ISSUE THREAD

**Issue by kompleksanda** [tebelorg/RPA-Python#482]
Hi, how do I navigate forward and backwards on the browser without visual automation? Thanks

**Comment by kensoh** [comment]
Try below (not at laptop now to validate). Below uses dom() to send JavaScript code to browser to run.

r.dom('window.history.back()')
r.dom('window.history.forward()')

**Comment by kensoh** [comment]
Tagging @kompleksanda

**Comment by kensoh** [comment]
Closing issue for now but let me know if above doesn't work. I think some online sources even omit the window base keyword and just use history.back()

**Comment by kompleksanda** [comment]
Thanks Kensoh!
