### ISSUE TITLE
Meeting point for TagUI users converting .tag workflows to Python rpa .py scripts

### ISSUE THREAD

**Issue by kensoh** [tebelorg/RPA-Python#484]
TagUI RPA has been maintained by AI Singapore for several years. From Q4 2023, they will stop supporting it.

The natural evolution for TagUI users, to make the most use of developed assets like TagUI workflows, would be to assess if converting to Python rpa package scripts make sense. Since each TagUI step has a matching Python rpa function(), conversion should be pretty straightforward for any user willing to learn Python.

For the JavaScript sections in TagUI workflow files, there are online convertors to convert JavaScript code to Python code. There are also other considerations like how to deal with scripts written in human languages other than English, how to deal with object repositories, how to deal with data tables etc etc etc.

Creating a placeholder issue here so TagUI users can post their challenges and share solutions on migrating from the most popular open-source RPA tool (TagUI) to the most popular open-source Python rpa tool (this package 😄)

**Comment by kensoh** [comment]
How I'll broadly approach migrating a TagUI script.

_**For basic TagUI workflows without advance features:**_

1. convert each TagUI step to Python syntax (it's similar to JavaScript). For example,
`snap page to results.png` becomes `r.snap('page', 'results.png')`
2. convert human language steps like `if`, `for` to Python or JavaScript syntax

_**For more complex TagUI workflows containing advance features:**_

3. if your TagUI script has JavaScript code, use online JavaScript to Python convertors
4. handle object repository possibly by loading the csv using csv module (or Pandas)
5. handle data table possibly by loading the csv using csv module (or Pandas)

_**For other features not mentioned above, post here to ask and exchange tips.**_

**Comment by 101NN** [comment]
Hi Ken, thanks for your work developing TagUI. My TagUI workflows that rely on SikuliX and require data tables stopped working recently, and I can’t solve the issue. Can this Python rpa tool handle data tables? If so, are there any resources you would recommend that explain how to write the code? Thank you.

**Comment by kensoh** [comment]
Closing issue for now because no posts or comments here, but feel free to post anything here, I will get GitHub notification
