### ISSUE TITLE
Cannot run Python RPA on Colab - notebook updated to work with new Colab env

### ISSUE THREAD

**Issue by terry-zc** [tebelorg/RPA-Python#486]
Hi, today I found that my code and sample code on Colab cannot run properly, I think there might be some issues of establish the Chrome on Colab. Does anyone fix this bug? thanks!
<img width="581" alt="截屏2023-07-21 12 48 54" src="https://github.com/tebelorg/RPA-Python/assets/104498558/b4f6eba9-ee05-4e9d-8789-be74bd04d751">

**Comment by kensoh** [comment]
Hi @terry-zc, thanks for raising this! Could you kindly try again? It looks like there is some change in the Colab environment that causes some OpenSSL issue. I've added a couple of lines in the Colab file to handle that new environment.

**Comment by kensoh** [comment]
(I'll exclude Google Colab issues from the bug report gift because Colab seems to be changing quite often that requires configuring the environment differently and installing Chromium differently, rather than fixing a bug in rpa package)

**Comment by kensoh** [comment]
Closing issue because works on desktop and mobile phone for me. But let me know if it still doesn't work for you!

**Comment by terry-zc** [comment]
Thank you! I just tried and it works now!

**Comment by kensoh** [comment]
That's wonderful! Thanks @terry-zc for reporting this :)
