### ISSUE TITLE
Focus windows desktop apps using run() command - try this example

### ISSUE THREAD

**Issue by nk-mobile** [tebelorg/RPA-Python#488]
Hi, Mr.Kensoh
r.run('cmd /c START c:\Project1.exe & EXIT')
r.wait(1)
r.keyboard('[right][enter]')

- application started, but not focused and script not working

r.keyboard('[win]'r)
r.wait(1)r
r.keyboard('c:\Project1.exe[enter]')
r.wait(1)
r.keyboard('[right][enter]')

- works perfectly

run('cmd /c START c:\Project1.exe & EXIT') in TagUI start and focus app.
So does it make sense to use run() to start windows desktop apps in RPA-Python?

**Comment by kensoh** [comment]
@nk-mobile if it is exe file, why not just do below for example, which launches Notepad for me and makes it in the foreground in focus. 

r.run('notepad.exe')

**Comment by kensoh** [comment]
Closing for now but feel free to post back here!
