### ISSUE TITLE
Support snapshot of the full screen as a fallback - use snap('page.png')

### ISSUE THREAD

**Issue by olimorris** [tebelorg/RPA-Python#489]
Firstly, just wanted to say what a fantastic package this is. I've thoroughly enjoyed working with it the past couple of evenings.

I've struggled to take a snapshot when trying trying out a visual automation. I've tried coordinates, passing over an image with a transparent background and it often stalls. As a backup, it would be great to be able to pass in 'None' to the first parameter and take a screenshot of the whole desktop.

**Comment by kensoh** [comment]
Thanks @olimorris! use snap('page.png') might be mentioned in docs but only briefly
