### ISSUE TITLE
How can I skip Geetest verification - use (x, y) coordinates to automate

### ISSUE THREAD

**Issue by monty8800** [tebelorg/RPA-Python#491]
Like this，After many tests, the background of this verification will not be changed. No matter how to refresh the background picture is always this one。
![image](https://github.com/tebelorg/RPA-Python/assets/10119633/4803920d-5061-4308-ab30-3d68c480a898)

**Comment by kensoh** [comment]
Hi @monty8800, try using x, y coordinates.

1. Use mouse_xy() to review current coordinates as you move the mouse around.
2. hover(x, y)
3. mouse('down')
4. hover(x, y)
5. mouse('up')
