### ISSUE TITLE
r.frame methods fail when inside iframe - Chrome not returning a match for this use case

### ISSUE THREAD

**Issue by RichiardChi** [tebelorg/RPA-Python#492]
Dear author, I have found that the r.frame method fails when url is inside the iframe, and I hope you can help fix this problem. Here is an case:

```
import rpa as r

if __name__ == '__main__':
    r.init(visual_automation=True, chrome_browser=True)
    r.url('http://localhost:63342/RPA-Python/iframe.html?_ijt=t9p2cu8m44uie9u1cb2bdfa1d2&_ij_reload=RELOAD_ON_SAVE')
    # r.url('http://www.tagui.com.cn/')
    r.dom('document.evaluate(\'/html/body/iframe\', document, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null).snapshotItem(0).setAttribute("name", "iframe-test")')
    r.frame('iframe-test')
    r.wait(5)
    r.click('/html/body/div[1]/nav/div/div[2]/ul/li[1]/a')
    r.wait(30)
    r.close()
```

![image](https://github.com/tebelorg/RPA-Python/assets/104183975/4cd8305d-a463-42b4-b306-35f15372fd03)

I want to click the menu in 'http://www.tagui.com.cn/' when the url is inside the iframe, but there is an error '[RPA][ERROR] - cannot find /html/body/div[1]/nav/div/div[2]/ul/li[1]/a'. 

The content of iframe.html is as below:

```
<iframe src='http://www.tagui.com.cn/' style='width: 100%;height: 100%;'>
</iframe>
```

**Comment by kensoh** [comment]
Hi @RichiardChi, do you have a real website with iframe that is accessible by public for me to test?

This is the first time an issue is raised on elements in iframe not accessible. I can't test above locally.

**Comment by RichiardChi** [comment]
Hi, soh. Thanks for your response. Really,I found this issue in a real website,which only can be accessed on our company intranet. So I do a simple test with above code. You can do a test using the ifarme.html first which i provided above.



---- Replied Message ----
| From | Ken ***@***.***> |
| Date | 09/24/2023 18:27 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [tebelorg/RPA-Python] r.frame methods fail when the url is inside the iframe (Issue #492) |

Hi @RichiardChi, do you have a real website with iframe that is accessible by public for me to test?

This is the first time an issue is raised on elements in iframe not accessible. I can't test above locally.

**Comment by RichiardChi** [comment]
you can run the ifarme.html in your local. and access the ifarme.html by calling “http://localhost:8080/ifarme.html”



---- Replied Message ----
| From | Ken ***@***.***> |
| Date | 09/24/2023 18:27 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [tebelorg/RPA-Python] r.frame methods fail when the url is inside the iframe (Issue #492) |

Hi @RichiardChi, do you have a real website with iframe that is accessible by public for me to test?

This is the first time an issue is raised on elements in iframe not accessible. I can't test above locally.

**Comment by kensoh** [comment]
Is the source website and target website url from the same domain? I think browser will block cross-site access for web security reasons. So I'll need to find a real website to test. Above would be cross-site too I think and not allowed by browser.

**Comment by RichiardChi** [comment]
Indeed this is a cross-domain problem. But we do have this cross-domain request situation on real websites, and it would be great if you could resolve it



---- Replied Message ----
| From | Ken ***@***.***> |
| Date | 09/25/2023 02:49 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [tebelorg/RPA-Python] r.frame methods fail when inside iframe - pending replication on a real website (Issue #492) |

Is the source website and target website url from the same domain? I think browser will block cross-site access for web security reasons. So I'll need to find a real website to test. Above would be cross-site too I think and not allowed by browser.

**Comment by RichiardChi** [comment]
Hi，Kensoh

Is there any new progress on the r.frame methods fail issue? I have disabled the web security of browser, but r.frame also fialed.

**Comment by kensoh** [comment]
Hi @RichiardChi,

1. How do you disable the web security of browser to allow cross-site queries using API?
2. I can only test if you can give an example of a public website which you can show the issue

**Comment by RichiardChi** [comment]
Hi @kensoh ,
1、add the param --disable-web-secutity when starting chrom.exe

**Comment by RichiardChi** [comment]
Hi @kensoh ,

2、' https://51.20.107.84/iframe.html ' this is a public website which you can show the issue to replicate. 
 Looking forword to your reply. Thanks a lot.

**Comment by RichiardChi** [comment]
Hi @kensoh ,
Can you replicate the issue of r.frame methods fail by the above website? Please feel free to contact us if you have any question. Thank you .

**Comment by kensoh** [comment]
Hi @RichiardChi, I had a look, for some reason, the iframe isn't being returned by Chrome?? Can you see if you are observing the same in Chrome devtools console:

![image](https://github.com/tebelorg/RPA-Python/assets/10379601/446ef4e4-95fd-4d76-ad6d-c88b5360702b)

Querying //h1 returns an object -
`document.evaluate('//h1',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0)`
`<h1>​…​</h1>​`

But querying the iframe returns null -
`document.evaluate('//iframe[@name="iframe-test"]',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0)`

I suspect that could be why the underlying iframe contents could not be accessed, when I tried to trace the execution.

**Comment by RichiardChi** [comment]
Hi，kensoh. 

The name 'iframe-test' is not an attribute of iframe. Firstly, you need execute `document.evaluate('/html/body/iframe', document, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null).snapshotItem(0).setAttribute("name", "iframe-test")` to add the name 'iframe-test' for iframe. You can see the result in console below:

![image](https://github.com/tebelorg/RPA-Python/assets/104183975/5d81f39f-8ce4-41b2-aa1f-a2fca2cdfc19)

**Comment by kensoh** [comment]
Thanks @RichiardChi,

Strange, I've added that (using dom() function) and can see that attribute in the DOM. But returns null.

Will try out more to do it from console.

**Comment by RichiardChi** [comment]
Ok，looking forward to your reply if you have any progress.

**Comment by marcelocecin** [comment]
hey guys
Another suggestion would be to record the tab with [this platform](https://jam.dev/?invite=0d7d5cec-9b13-49f2-a69d-d119d1440e5c)
it captures network information and console logs

**Comment by kensoh** [comment]
Trying on another webpage with iframe, the following works. It is able to type into the text box in the iframe whether referencing the original ID of the iframe, or referencing a manually added name attribute.

```py
import rpa as r
r.init()
r.url('https://demo.automationtesting.in/Frames.html')
r.frame('singleframe')
r.type('//input', 'testing 123')
r.frame()
r.dom('document.evaluate(\'//iframe\', document, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null).snapshotItem(0).setAttribute("name", "test_frame_name")')
r.frame('test_frame_name')
r.type('//input', 'testing 456')
r.wait()
```

**Comment by kensoh** [comment]
Adding on to above testing on a typical website with iframe but without cross-site URL to another domain,

Retesting on the sample website you shared, the query returns the object.

![image](https://github.com/tebelorg/RPA-Python/assets/10379601/6e92ba06-4b13-44eb-8bd3-e09bc96df22e)

But querying from console the following, it returns 0 which means no result returned from Chrome browser after setting context to the iframe. This is despite mainframe_context having correct iframe object.
```
mainframe_context = document.evaluate('//iframe[@name="iframe-test"]',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0)
document.evaluate('/html/body/div[1]/nav/div/div[2]/ul/li[1]/a',mainframe_context,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength
```
![image](https://github.com/tebelorg/RPA-Python/assets/10379601/b548539e-25af-43e1-8468-5c1c098b7919)

**Comment by kensoh** [comment]
Adding on to above 2 debugging findings,

I found this post - https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome

When I add below to the tagui script to disable web security and enable the cross-site stuffs,

```
chrome_started="$(uname -s)"; chrome_switches="--disable-web-security --disable-features=IsolateOrigins,site-per-process --remote-debugging-port=9222 about:blank"
```

Chrome is still returning nothing when tried to query the element in the frame, when the frame object is valid -
```
[109] {"id":109,"result":{"result":{"type":"object","subtype":"error","className":"TypeError","description":"TypeError: Failed to execute 'evaluate' on 'Document': parameter 2 is not of type 'Node'.\n    at <anonymous>:1:10","objectId":"2030281531867037696.3.95"},"exceptionDetails":{"exceptionId":48,"text":"Uncaught","lineNumber":0,"columnNumber":9,"scriptId":"13","exception":{"type":"object","subtype":"error","className":"TypeError","description":"TypeError: Failed to execute 'evaluate' on 'Document': parameter 2 is not of type 'Node'.\n    at <anonymous>:1:10","objectId":"2030281531867037696.3.96"}}}}
```

I cannot assist further, because if you trace above, Chrome literally is just not turning a match when querying a valid frame object with the following JavaScript code, even with the special flags enabled to launch Chrome.

```
mainframe_context = document.evaluate('//iframe[@name="iframe-test"]',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0)
document.evaluate('/html/body/div[1]/nav/div/div[2]/ul/li[1]/a',mainframe_context,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength
```

My suggestion is if you can query the URL of the frame directly, instead of accessing it as a frame. There is something around Chrome's behaviour which I suspect is related to cross-site security, but this edge case is not something the rpa package can change or support. cc @RichiardChi

**Comment by RichiardChi** [comment]
thinks, mybe I can only visit the url of iframe directly. 







At 2024-01-07 10:30:39, "Ken Soh" ***@***.***> wrote:

Adding on to above 2 debugging findings,

I found this post - https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome

When I add below to the tagui script to disable web security and enable the cross-site stuffs,

chrome_started="$(uname -s)"; chrome_switches="--disable-web-security --disable-features=IsolateOrigins,site-per-process --remote-debugging-port=9222 about:blank"


Chrome is still returning nothing when tried to query the element in the frame, when the frame object is valid -

[109] {"id":109,"result":{"result":{"type":"object","subtype":"error","className":"TypeError","description":"TypeError: Failed to execute 'evaluate' on 'Document': parameter 2 is not of type 'Node'.\n    at <anonymous>:1:10","objectId":"2030281531867037696.3.95"},"exceptionDetails":{"exceptionId":48,"text":"Uncaught","lineNumber":0,"columnNumber":9,"scriptId":"13","exception":{"type":"object","subtype":"error","className":"TypeError","description":"TypeError: Failed to execute 'evaluate' on 'Document': parameter 2 is not of type 'Node'.\n    at <anonymous>:1:10","objectId":"2030281531867037696.3.96"}}}}


I cannot assist further, because if you trace above, Chrome literally is just not turning a match when querying a valid frame object with the following JavaScript code, even with the special flags enabled to launch Chrome.

mainframe_context = ***@***.***="iframe-test"]',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotItem(0)
document.evaluate('/html/body/div[1]/nav/div/div[2]/ul/li[1]/a',mainframe_context,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength


My suggestion is if you can query the URL of the frame directly, instead of accessing it as a frame. There is something around Chrome's behaviour which I suspect is related to cross-site security, but this edge case is not something the rpa package can change or support. cc @RichiardChi
