### ISSUE TITLE
Return html of element searched by id - try using attribute with @attribute

### ISSUE THREAD

**Issue by aadams26** [tebelorg/RPA-Python#496]
Hi, 
Is there a way to select an html element by id/name/etc or return the html of an element?

**Comment by kensoh** [comment]
Hi @aadams26, I'm not sure how to do that or if that's even possible, to retrieve specifically the html of an element.

Can you share more on your use case? You can, however, using @attribute to access attributes of an element.

For example, on Google search page, below could give your the property value of autocapitalize property/attribute.

```
r.url('www.google.com')
r.read('//*[@name="q"]/@autocapitalize')
```

**Comment by aadams26** [comment]
@kensoh  thank you kindly for your help. This solves my use case.
