### ISSUE TITLE
TagUI cannot be closed after closing the browser - expected, pending more info

### ISSUE THREAD

**Issue by RichiardChi** [tebelorg/RPA-Python#497]
Hi kensoh,

When tagui runs' r.lose ()' after closing the brower, the process cannot be closed. I found this line of code  ' while _process.poll() is None: pass' at funtion close() in tagui.py got stuck in an infinite loop until I restart.  Could you please help to fix it? The test code  is as fellow:

```
r.init(visual_automation=True)
r.debug()
r.url('https://github.com/tebelorg/RPA-Python')
r.wait(2)
keyboard('[alt][space]')
keyboard('[alt][F4]')
r.close()

```

**Comment by kensoh** [comment]
Hi @RichiardChi, the expected design is using close() to close the process and the browser. If user accidentally close browser before close() function runs, you can ignore it. The next time init() runs, it will kill dead processes and start clean.
