### ISSUE TITLE
Change browser window focus - depending on what you want, popup() or focus()

### ISSUE THREAD

**Issue by Yuro12345** [tebelorg/RPA-Python#499]
Have somehow i change the window focus?

**Comment by kensoh** [comment]
Do you mean change focus to another tab? That will be using popup(). If you mean change focus to another desktop app window, you can either use visual automation to click on it from the task bar, or use focus().

**Comment by Yuro12345** [comment]
I need to change focus to another tab of my browser

**Comment by kensoh** [comment]
I see, then use popup(). See API reference section, use popup('unique_string_in_url_of_tab') to switch focus and popup() to reset to original page.
