### ISSUE TITLE
Upon executing r.init(), Chrome opens, but nothing happens afterward - might be IT policy

### ISSUE THREAD

**Issue by bwfyyy** [tebelorg/RPA-Python#500]
I have been using RPA for automation for over a month now, and it has been running smoothly. However, issues started arising from yesterday. Upon executing r.init(), it launches Chrome, but Chrome automatically closes, showing an error with r.init(). I reinstalled Chrome, but it didn't resolve the issue. Subsequently, I reinstalled the Python environment and RPA. Now, what happens is that Chrome opens after r.init() is executed, but there's no response afterward. Looking at the status in Jupyter, r.init() is constantly busy with no prompts whatsoever.

**Comment by bwfyyy** [comment]
The operating system I am using is Windows 10

**Comment by kensoh** [comment]
Hi @bwfyyy, it sounds like for some reason, the package cannot connect to the websocket connection to the Chrome browser. Is this a work laptop? It might be company IT policy or firewall or anti-virus blocking connection to Chrome's websocket. Can you try the following?

1. run in debug mode to see what happens
```
r.debug(True)
r.init()
```
2. There should be other command prompt windows when init() is run, one of them is for Chrome browser. Is there any message showing up there?
