### ISSUE TITLE
macOS: Chrome session created by init() cannot access disk(?)

### ISSUE THREAD

**Issue by 328joe** [tebelorg/RPA-Python#504]
Hi,
I am attempting writing a very simple code to test the web automation, which open a URL and click the a button to download a Excel file:

r.init()
r.url('https://xxxxxx')
r.wait(20)
r.click('//*[@id="ete"]')
ans = input("Wait....")
r.close()

Problem:
A Chrome session is successfully created which pointing to the target site.
A mouse click is successful emulated. Chrome shows download completed.
However, when check at the Finder, no file is saved.

I tried to add a Python statement (input) to pause the Chrome session. So I can manually operate the Chrome.
Finding:
1. Manually click the download button on the target website. Same symptoms. No file is wrote.
2. Click the "recent download history" of Chrome. All the corresponding download attempting are shown usually, as expected.
3. Move the mouse over the filename and click "show in the finder". No response. The target folder cannot be opened.

Seems the Chrome session which created by RPA init() cannot access to disk. If I manually open Chrome, everything works fine. The target file can be downloaded and saved.
Would you give me some hints. Thanks a lot.

The following is my environment info:
RPA
1.50.0

OS Version:
macOS 14.1.1 (23B81)

% php -v
PHP 8.2.12 (cli) (built: Oct 24 2023 19:22:16) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.12, Copyright (c) Zend Technologies
with Zend OPcache v8.2.12, Copyright (c), by Zend Technologies

Chrome version:
Version 119.0.6045.159 (Official Build) (x86_64)

**Comment by 328joe** [comment]
Hi,
Finally I found only the 'current' directory is accessible by the Chrome. The files are saved to the 'project root', whatever we config under Chrome.

**Comment by kensoh** [comment]
Hi @328joe thanks for raising this and updating back! Yes I think the default downloaded folder is the project root folder. But I haven't come across a user report saying that Chrome can't access other folders. It might be a new security measure in newer Chrome. Do let me know again if you run into a blocker!
