### ISSUE TITLE
How do I use rpa.init() in PyScript or Pyodide? - try this local hacks to see if they work

### ISSUE THREAD

**Issue by bielaiwuyang-j** [tebelorg/RPA-Python#506]
When I use PyScript or Pyodide, platform.system() print is Emscripten.So when I run rpa.init() in browser,show error "unknown Emscripten operating system to setup TagUI".
    In source codes,I can see it,is only support windows linux and macos.How should I solve this problem.
    My English is not very good. If there is any problem with my expression, please forgive me,thanks

**Comment by kensoh** [comment]
Hi @bielaiwuyang-j, can you share with me more on your use case of running Python code in the web browser?

Indeed, the package is designed to run directly on Python Windows, Linux, Mac, but not through a web browser.

There could be a workaround, you can try the following -

1. get location of the Python rpa package with
```
import rpa as r
print(r.__file__)
```
2. edit the file tagui.py under that folder
3. search and replace all references of `platform.system()` with `Windows`, `Linux`, `Darwin`(Darwin is code name for Mac) depending on what is the real OS that you are running the automation on
4. restart and try again

**Comment by kensoh** [comment]
(you can also type in Chinese, I'm Chinese but primarily using English and type English keyboard, but I can read Chinese no problem)
