### ISSUE TITLE
Using reCAPTCHA keys to bypass - those are for the actual website owner for testing

### ISSUE THREAD

**Issue by aadams26** [tebelorg/RPA-Python#508]
Is there a method in place to use reCAPTCHA keys to bypass reCAPTCHA using this RPA?

https://developers.google.com/recaptcha/docs/faq#id-like-to-run-automated-tests-with-recaptcha.-what-should-i-do

**Comment by marcelocecin** [comment]
reCAPTCHA v2 or v3 ?

**Comment by marcelocecin** [comment]
Can you share the code you are trying to use?

**Comment by marcelocecin** [comment]
maybe [this](https://github.com/dessant/buster) can help you

**Comment by kensoh** [comment]
Adding on @aadams26, the link below shows how a website owner can configure the reCAPTCHA on his testing website for test automation. It is not how someone can automate and goes through reCAPTCHA prompts on normal PROD websites.

https://developers.google.com/recaptcha/docs/faq#id-like-to-run-automated-tests-with-recaptcha.-what-should-i-do

Thanks @marcelocecin for your reply and sharing these libraries!!
