### ISSUE TITLE
Text not found - r.click() with OCR text by using "Text I want to click on.png" syntax

### ISSUE THREAD

**Issue by Kellesc** [tebelorg/RPA-Python#509]
Hi, 

first of all thank you for this amazing library!

The documentations states "If the image file specified does not exist, OCR will be used to search for that text on the screen". I would like to click on the desktop application on a specific text that changes with a variable. 

I tried a test:
![word_example](https://github.com/tebelorg/RPA-Python/assets/133388064/35ee4da9-2be7-40a3-968c-0847ddc11dce)

I am looking for 'Test2' in the word document but it is not able to find it:
![command_1](https://github.com/tebelorg/RPA-Python/assets/133388064/6fb50e9c-8576-4725-8082-40581d1dc7bd)

If I look for the text in Word it works fine:
![command_2](https://github.com/tebelorg/RPA-Python/assets/133388064/9a12c22d-9b33-4545-9bf9-746bcd010f75)

am I doing anything wrong?

Thanks
Michele

**Comment by kensoh** [comment]
Hi @Kellesc, you are welcome! Oh the syntax is r.click('Submit Form.png') shown in the doc. There is a need to have .png so that rpa package knows that you are looking for a match visually, vs looking using XPath, CSS selectors on a web page.

In this case you can try r.click('Test2.png')

**Comment by Kellesc** [comment]
Hi,

Thank you for replying so could you please confirm that it cannot look for text as described? ("If the image file specified does not exist, OCR will be used to search for that text on the screen")

Thanks

**Comment by kensoh** [comment]
It can look, your syntax is wrong. Use r.click('Test2.png') and not r.click('Test'). See the example in my reply above.

**Comment by Kellesc** [comment]
Hi Kensoh, 

I am sorry I could not reply earlier. Thank you for the clarification I misinterpreted the guide. 
I tried as you suggested resulting in an unexpected SikuliX Engine crash (I think due to some incorrect configuration):
![siculix_error](https://github.com/tebelorg/RPA-Python/assets/133388064/8d38c219-dd8e-452e-baf5-b75a6e4f81b3)

"Tesseract couldn't load any languages!"

Is there any know way to fix it?
Thanks

**Comment by Kellesc** [comment]
Hi Kensoh,

I am sorry I could not reply earlier. Thank you for the clarification I misinterpreted the guide.
I tried as you suggested and it works. 

Thank you

**Comment by Kellesc** [comment]
Hi @kensoh,

is it possible to change the tesseract language?

Thanks

**Comment by marcelocecin** [comment]
https://github.com/aisingapore/TagUI/issues/1215#issuecomment-1110529037

**Comment by kensoh** [comment]
Thanks @marcelocecin it is indeed as you shared, issue #405 example of switching to Chinese OCR. Tagging @Kellesc
