### ISSUE TITLE
Will there be support for automation of desktop apps - already, visual automation

### ISSUE THREAD

**Issue by lrange2001** [tebelorg/RPA-Python#512]
May I ask if there will be support for automation of desktop applications in the future

**Comment by lrange2001** [comment]
Will there be a feature similar to waiting for page elements in the future? It seems that desktop applications are currently unable to capture windows

**Comment by kensoh** [comment]
Hi @lrange2001 you can interact with desktop apps using visual automation (image, coordinates, OCR) and keyboard shortcuts etc. There is auto-wait for element to appear too. See the API reference section and the sample.py for examples.
