### ISSUE TITLE
The problem with Cyrillic in r.keyboard() - known limitation with SikuliX engine

### ISSUE THREAD

**Issue by debugger1979** [tebelorg/RPA-Python#515]
Hello!
I found a problem with the output of Cyrillic characters in r.keyboard(). When trying to perform an operation, the script freezes. I have already seen a similar topic that described problems with Chinese characters. I tried the option of adding a UTF-8 string to the body of the script, but nothing worked. I used the option with r.clipboard() - the issue was resolved, but partially. I need to perform a text "typing" operation in a text editor. It is typing, not pasting from the clipboard
Tell me, please, is it possible to solve this problem?

**Comment by kensoh** [comment]
Closing this issue for now but will look out for any reply

**Comment by debugger1979** [comment]
Hello!
My task is to emulate working with documents
- open a document in the program
- edit the document (type the text)
- save the document
- exit the program

The problem is "typing" in Cyrillic.

**Comment by kensoh** [comment]
Are you able to use below to do it?

r.clipboard('some Cyrillic text')
r.keyboard('[ctrl]v']

**Comment by kensoh** [comment]
Will above be also able to get the text you want into the document?
