### ISSUE TITLE
use document for context - checking if still a problem and scenario to do this

### ISSUE THREAD

**Issue by rcfcu2000** [tebelorg/RPA-Python#519]
The mainframe_context may not work in all cases, in my case, the html page has js function which triggers a pop up div, and present() could not find the element, my investigation shows that mainframe_context is the cause of this problem.

If I use:
document.evaluate('//*[@class=\"bosschat-chat-input chat-global-message boss-chat-editor-input\"]',mainframe_context,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength

length is 0

document.evaluate('//*[@class=\"bosschat-chat-input chat-global-message boss-chat-editor-input\"]',document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null).snapshotLength

length is 1

and mainframe_context is different than document
<img width="836" alt="image" src="https://github.com/tebelorg/RPA-Python/assets/10900674/602fbdb7-58a0-47b7-887b-4511fd8986ee">

**Comment by kensoh** [comment]
Hi @rcfcu2000, sorry for late reply I just got to work on GitHub issues! Is this still a problem?

**Comment by kensoh** [comment]
If it is still a problem, can you share the scenario and your use case and I can see if there is another way to doing what you need?

**Comment by kensoh** [comment]
Closing issue for now but I will look out for your reply
