### ISSUE TITLE
dom() returns empty string - that is within a frame, see this easier example

### ISSUE THREAD

**Issue by Kellesc** [tebelorg/RPA-Python#520]
Hi, 

Once more thank you for your great job! 

I am trying to use dom() function to get the style of an element. 

For instance from this page (https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_document_getelementbyid1) 

I tried:
r.dom('return document.getElementById("demo").style')
r.dom('return document.querySelector("demo").style')
 and other options , I always get '' as output. Adding r.echo I just get True.

I have seen examples from 
https://github.com/tebelorg/RPA-Python/issues/49
https://github.com/tebelorg/RPA-Python/issues/295
and others; whatever I try returns an empty string. 

What am I missing?
Thanks

**Comment by kensoh** [comment]
Hi @Kellesc sorry for late reply I just got to work on the GitHub issues!

This is because on that webpage there are various frames. The dom() is assessing the primary parent frame.

To do what you want you can use the @ attribute in XPath to read the style value - see example below

```
>>> r.url("https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_document_getelementbyid1")
True
>>> r.frame('iframeResult')
True
>>> r.read('//*[@id="demo"]/@style')
'color: red;'
```

**Comment by kensoh** [comment]
(closing issue for now)
