### ISSUE TITLE
Run rpa in centos error whether headless or not - checking if it is still a problem

### ISSUE THREAD

**Issue by balicheng** [tebelorg/RPA-Python#521]
I run code as RPA for python's WEB AUTOMATION demo on centos. When i setting headless_mode=False on init(), code can init, but on url step, return error as  **b'ERROR - step only supported in live mode using Chrome browser\n'
tagui_out ERROR - step only supported in live mode using Chrome browser** .
When i seting headless_mode=True on init. Code have no response or log, more than 10 min. I print Intermediate steps, after ### **### _tagui_cmd "/home/hh/.tagui/src/tagui" rpa_python headless_**, code is stoping.
When is run **"/home/hh/.tagui/src/tagui" rpa_python headless** command  on my machine, it return:
 (base) [hh@localhost RPA]$ "/home/hh/.tagui/src/tagui" rpa_python headless
/home/hh/.tagui/src/tagui: 行 315: 26477 段错误               $chrome_command --user-data-dir="$TAGUI_DIR/chrome/tagui_user_profile" $chrome_switches $window_size --no-sandbox > /dev/null 2>&1
已终止
When is run **"/home/hh/.tagui/src/tagui" rpa_python google-chrome** command  on my machine, it return:
**(base) [hh@localhost RPA]$ "/home/hh/.tagui/src/tagui" rpa_python google-chrome

START - automation started - Tue Feb 27 2024 10:02:54 GMT+0800 (CST)

LIVE MODE - type done to quit**

I'm looking forward your help. I want to simulate web automation process by Xpath on centos successful, then can run online.
Hope for your answer, than you very much!

**Comment by kensoh** [comment]
Hi @balicheng sorry for late reply I just got to work on GitHub issues! Is this still a problem?
