### ISSUE TITLE
r.init() hang on cloned virtual machine - my guess is some VM / vendor issue

### ISSUE THREAD

**Issue by cohnhead66** [tebelorg/RPA-Python#522]
My RPA-Python application requires running multiple instances, (4-6), in parallel at a specified schedule.  I have coded and tested a master instance on a google cloud linux virtual machine and trigger with a cronjob and it works great.   My plan to run multiple instances is to spin up clones of the master instance vm a few minutes prior to needing them, let them run the script, and then delete the vm once run is completed.  This minimizes cost and also ensures that the script is always the latest version.

Unfortunately, when I clone a vm and run the script it hangs on the r.init() command.  There is no error, just hangs.  If I clone the master vm before I install RPA and PHP, and do those installs manually the clone works just like the master.  Not sure what is causing the hang, so not sure how to troubleshoot, so any help would be appreciated.

Also, happy to hear other suggestions of the best way to accomplish running multiple instances of the same script at the same time.

**Comment by kensoh** [comment]
Hi @cohnhead66 sorry for my late reply! Just got to work on the GitHub issues!

If a VM works, by right cloning it should work. But I'm not familiar enough with VM to know why it doesn't.

My best guess is the VM and your vendor somehow stores some state such that installing directly works but cloning an an already installed VM doesn't.

My best guess on what could work may be to just factor in the few minutes of installation time and do those installation on all the instances. You can use some of the Python date time libraries to just sleep until it is the time to run the automation then it starts, so the running will be all in parallel.

Closing the issue for now but will look out for your reply!
