### ISSUE TITLE
Running r.url("https://www.baidu.com") fails - pending more details and replication

### ISSUE THREAD

**Issue by luSir997** [tebelorg/RPA-Python#524]
import rpa as r
r.init()
r.url("https://www.baidu.com")
r.wait()
r.close()
可以正常打开浏览器到首页但是打不开指定的页面  希望大佬指点

**Comment by luSir997** [comment]
![0a80e33142c09f5310df66cdea7f5fd](https://github.com/tebelorg/RPA-Python/assets/163833335/6f0252e5-3a61-4bb0-94d6-c2a958997536)

**Comment by kensoh** [comment]
Hi @luSir997 can you tell me more?

I am able to open and go to Baidu webpage using your code above.

![image](https://github.com/user-attachments/assets/68a3273e-c173-4902-ad93-1cd1d1806c68)

**Comment by kensoh** [comment]
Closing this issue for now but will look out for any reply
