### ISSUE TITLE
运行可以打开浏览器，但是浏览器显示崩溃 url() cannot work - pending replication

### ISSUE THREAD

**Issue by langmie123** [tebelorg/RPA-Python#525]
运行代码可以打开浏览器，但是不能打开百度

```python
import rpa as r

r.init()
r.url('https://www.baidu.com')
r.wait() # ensure results are fully loaded
r.snap('page', 'results.png')
r.close()
```
![企业微信截图_20240323134346](https://github.com/tebelorg/RPA-Python/assets/23777888/7ed6120d-21ff-4f01-b0c2-eaa8c8f16c26)

**Comment by kensoh** [comment]
Closing this issue for now but will look out for any reply
