### ISSUE TITLE
RPA-python code has stopped working after update of chrome browser

### ISSUE THREAD

**Issue by venky652003** [tebelorg/RPA-Python#527]
hi,
My chrome browser got auto updated with version 121.0.6167.185 . My rpa-python code which was running earlier is not running. Any way to resolve the issue please?

**Comment by venky652003** [comment]
hi,
The above issue still persists. can you please suggest a solution ?

**Comment by venky652003** [comment]
This issue got resolved after re-installing chrome. How it got resolved is not clear.

**Comment by venky652003** [comment]
thanks.

**Comment by kensoh** [comment]
Hi @venky652003 thanks for raising this issue! I suspect that some new Chrome version might have a bug but it was fixed by Google in the newer version so it works again.
