### ISSUE TITLE
Enhance Telegram function with sendphoto - has to pass on this, VPS bandwidth limited

### ISSUE THREAD

**Issue by ignatiustanjh** [tebelorg/RPA-Python#528]
Hi @kensoh ,

Was working on building a monitoring platform using the library and wanted to send myself telegram notifications based on the RPA automated task.

I think it would be a useful enhancement (or secondary addition) to the telegram method to allow it to send images using the telegram api. Eg. the sendPhoto method

**Comment by ignatiustanjh** [comment]
Not sure if there are costing or privacy issues associated with your instance to send the image- so feel free to close this if it's not feasible from a cost, privacy or other perspective

**Comment by kensoh** [comment]
Thanks @ignatiustanjh for raising this! It is exactly like you said, my VPS has a limited data bandwidth every month, so I could risk causing issues for other users using normal text Telegram messages, if I enable the photo sending function.

However, you can use the bin() function to auto-upload your image to a temporary URL, then send that URL as part of your Telegram message - https://github.com/tebelorg/RPA-Python?tab=readme-ov-file#secure-temporary-storage

Closing the issue for now but I will look out for your reply!
