### ISSUE TITLE
rpa package init the chrome without the stored cookies - pending replication

### ISSUE THREAD

**Issue by Yucheng123** [tebelorg/RPA-Python#529]
I need to login the web everytime when I init the chrome. Is there any ways to init a normal chrome. My platform is mac

**Comment by kensoh** [comment]
Hi @Yucheng123 by default the package will store the user session, can you share a simple replication script? One possible reason could be the website you are automating can detect that it is automated, so it terminates the logged in session once you exit Chrome.

**Comment by kensoh** [comment]
Closing this issue for now but will look out for any reply
