### ISSUE TITLE
怎么操作应用呢 (how to automate desktop apps) - a few methods, see here

### ISSUE THREAD

**Issue by Louis24** [tebelorg/RPA-Python#532]

**Comment by kensoh** [comment]
Hi @Louis24, for desktop apps, you can use visual automation by providing images to click on and to type into. Or use x,y coordinates on the screen. Or use keyboard() step. You can also use OCR. See more at this section

https://github.com/tebelorg/RPA-Python?tab=readme-ov-file#element-identifiers

And example here - https://github.com/tebelorg/RPA-Python/blob/master/sample.py

**Comment by kensoh** [comment]
I'll close issue for now but will look out for your reply
