### ISSUE TITLE
Encountered error if path contains spaces - limitation of TagUI engine for Windows user name

### ISSUE THREAD

**Issue by mathans1695** [tebelorg/RPA-Python#535]
**This is my code**:

`
import rpa as r

def main():
    r.init()

if __name__ == '__main__':
    main()
`

When executed using `python main.py`

**The following error occurred**:
`
(venv) C:\Users\DELL PC\Desktop\Mahalingam\option-chain-rpa>python main.py
'C:\Users\DELL' is not recognized as an internal or external command,
operable program or batch file.
[RPA][ERROR] - following happens when starting TagUI...

The following command is executed to start TagUI -
"C:\Users\DELL PC\AppData\Roaming\tagui\src\tagui" rpa_python chrome

It leads to following output when starting TagUI -
'C:\Users\DELL' is not recognized as an internal or external command,
operable program or batch file.

[RPA][ERROR] - unknown error encountered
`

**And also Tagui is not installed in the specified location - `C:\Users\DELL PC\AppData\Roaming\tagui\src\tagui`, because of this problem**

<img width="414" alt="image" src="https://github.com/tebelorg/RPA-Python/assets/62509702/f97e9024-de33-4f24-a984-2b47a759a454">

**Platform**: Windows 11 pro
**Python version**: 3.12.2

**Comment by kensoh** [comment]
Hi @mathans1695 thanks for raising this! This is a limitation in the TagUI RPA engine that Python rpa package is based on. Can you try with another user name that has no space in the name?

Closing the issue for now, but I will look out for your reply.
