### ISSUE TITLE
How to open a new tab at given URL and visit the new tab - see example

### ISSUE THREAD

**Issue by Anencephalous** [tebelorg/RPA-Python#536]
Hi Ken @kensoh 
please help.

Let me explain my use case.   I have 2 websites(siteA and siteB) and they are unrelated to each other (can't open siteB from siteA using any operates like clicking some link or buttons).
The job is to get some datas from siteB and put it into the forms in siteA (and do the same thing from A to B) . 
but r.url() always works with the first tab.

I tried like this 👇: 

   r.init(visual_automation=True)
   r.url("http://www.siteA.com")
    r.wait(2)
    r.keyboard('[ctrl]t')
    r.popup("blank")
    r.wait(2)
    r.url("http://www.siteB.com")

but it dosen't work. It can successfully create a new tab but  [ r.url("http://www.siteB.com") ]  still just changes the first tab to siteB...

please help. Thanks.

**Comment by kensoh** [comment]
Hi @Anencephalous I understand your scenario, you can use dom() to send JavaScript to open a new tab, see example -

The URL will change on the new Yahoo tab. And you can use r.popup() to change focus back to the Google tab.

```py
r.init()
r.url('www.google.com')
r.dom("window.open('www.yahoo.com')")
r.dom("window.open('https://www.yahoo.com')")
r.popup('yahoo')
r.url('www.duckduckgo.com')
```

**Comment by kensoh** [comment]
Will close issue for now but let me know if any issue!

**Comment by Anencephalous** [comment]
BIG THANKS.

**Comment by Anencephalous** [comment]
BIG THANKS @kensoh
