### ISSUE TITLE
[clear] doesn't always work - webpage doesn't allow automation, try using visual automation

### ISSUE THREAD

**Issue by ascheitel** [tebelorg/RPA-Python#543]
Hello,

I am trying to clear an input field before inserting text into it, but unfortunately, the command works only half of the time. Sometimes the field is cleared, and sometimes the field fails to clear.

I don't understand why.

Here is the code:
```
import rpa as r

r.init()
r.url('https://www.lk.com/fr/')
r.wait(15) # ensure results are fully loaded
r.type('/html/body/div/section/main/div[1]/div[2]/div[3]/div/div[2]/div/div[1]/div[1]/div/input', '[clear]5000')
```

Thank you for your help

**Comment by kensoh** [comment]
Hi @ascheitel I've tried the webpage, it looks to not allow automated changing of values.

I tried using Chrome debugger and changing the value but it changes back immediately to old value.

An alternative is try using visual automation to use images to click and type into the webpage.

For example, you can try doing a r.click() on below image, then do
`r.keyboard('[ctrl]a'); r.keyboard('[delete]'); r.keyboard('5000')`;

![Screenshot 2024-10-03 at 11 24 48 AM](https://github.com/user-attachments/assets/1cb4a771-55a9-4696-8a6e-bfd2050a6397)

**Comment by ascheitel** [comment]
I tried the code below but it doesn't work. It clears the browser's url bar.

```
r.init(visual_automation=True)
r.url('https://www.lbank.com/fr/trade/btc_usdt')
r.wait() # ensure results are fully loaded

# double-quote the string
r.click('/html/body/div/section/main/div[1]/div[2]/div[3]/div/div[2]/div/div[1]/div[1]/div/input')

r.keyboard('[ctrl]a')
r.keyboard('[delete]')
r.keyboard('5000')
r.close()
```

**Comment by kensoh** [comment]
No no for the r.click() you need to provide a snapshot of the web element to click on. For eg r.click('textbox.png')

**Comment by ascheitel** [comment]
Thanks, it works.
But now I'm wondering what to do if I want to do the same thing on the right field as the image is identical. Do you know how to proceed?

![img2024-10-03 214413](https://github.com/user-attachments/assets/bedc3f2d-dd2c-4343-9764-19936beb704d)

**Comment by kensoh** [comment]
The visual automation clicks on centre of the image. Try taking snapshot of something unique like this - 

![Screenshot_20241003_233604_com android chrome_edit_1512026194992197](https://github.com/user-attachments/assets/9fd4030b-6745-4793-9204-c817ff1d3f0c)

**Comment by ascheitel** [comment]
Hi Ken Soh,
what tool do you use to make screenshots ?
I'm trying to reproduce the same screenshot as you but the RPA script doesn't recognize it.

**Comment by kensoh** [comment]
I use snipping tool on Windows. Check your display settings, need to choose 100% to work properly.

**Comment by ascheitel** [comment]
Thanks, it works
