### ISSUE TITLE
How to run another TagUI script? - use Python import to run other .py scripts 

### ISSUE THREAD

**Issue by baramofme** [tebelorg/RPA-Python#544]
I want to run another TagUI flow (.tag or .py or word file)within a Python code.

The CLI version of TagUI explains how to call a flow with the .tag extension in the “[Running flows within a flow](https://tagui.readthedocs.io/en/latest/advanced.html#running-flows-within-a-flow)” section.

 I couldn’t find any method to run another flow within Python code in the [RPA-Python 
 API Refrence](https://github.com/tebelorg/RPA-Python/?tab=readme-ov-file#api-reference). Did I miss something?

Currently, I am using the method `r.run('tagui ./[relative path]/[name].tag')` to execute the script.

However, when the run command ends, the browser also closes, so I cannot continue the flow in the Python script. Additionally, it is inconvenient that it is not executed in-place within the Python script.

**Comment by kensoh** [comment]
Hi @baramofme you can write another Python script and call its functions like how Python users normally import another script and run its functions.

**Comment by baramofme** [comment]
Hello @kensoh, now I know how to import and run TagUI Python code from relative paths' .py files like belows. Thank you!

```python
import rpa as r
import os
# "Assume there's a file at ./flow/python/main.py.
from flow.python import main

os.system('chcp 65001')
r.init(visual_automation = True)

main.login(r)

r.click('login')
r.close()
```
root.py

```python
def login(r):
    # login
    r.url('https://rpaexercise.aisingapore.org/login')
    r.type('username', 'jane007')
    r.type('password', 'TheBestHR123')
```
main.py

How can I import and run TagUI scripts with a .tag file extension?

I understand that I could write Python code to replicate .tag script functionality. But doing everything in Python involves tedious tasks like capturing and processing images or using developer tools to find XPaths.

So, directly calling .tag scripts created with efficient tools like the web recorder Chrome extension seems much more appealing.

**Comment by kensoh** [comment]
You can also using TagUI Chrome extension to record, then manually or use Anthropic's Claude AI to convert to RPA for Python script. I don't think you can run .tag scripts from Python, because rpa package and TagUI share some underlying engines and will conflict with each other. But you can simply use Python os module to run .tag scripts if you wish. For eg

```py
import os
os.system('tagui xxx.tag')
```

**Comment by baramofme** [comment]
@kensoh, understood. I'll record with the extension and then convert it using LLM. There are conflicts between Python and non-Python TagUI due to some shared engine parts.

Thanks for all your help!
