### ISSUE TITLE
How to avoid / set OpenJDK - depends on use case and environment 

### ISSUE THREAD

**Issue by lmh87883819** [tebelorg/RPA-Python#545]
I want to know where I can set the jdk package in my code, because I want to make an rpa application, but I don't want users to go to amazon to download OpenJDK

**Comment by kensoh** [comment]
Hi @lmh87883819, OpenJDK is only needed if you use visual automation or keyboard() function. Otherwise no need.

Also, if users' PCs already have Java, may not need to install OpenJDK separately. You can try if it works on their PCs.
