### ISSUE TITLE
Holding ctrl key while clicking - use r.vision('keyDown(Key.CTRL)')

### ISSUE THREAD

**Issue by yekunhui** [tebelorg/RPA-Python#546]
r.mouse('down')  # hold the mouse down
r.keyboard('[ctrl]') 
r.mouse('left')  # release the mouse

Hi, I'm trying to do "hold the ctrl key and click something", but right now the best I can do is hold the left mouse button, press the ctrl key (not hold), and release the left mouse button.

Could you show me how to hold a key using the RPA?

**Comment by kensoh** [comment]
Hi @yekunhui you will have to use custom SikuliX commands with r.vision() see this example -

```py
r.vision('keyDown(Key.CTRL)'); r.click('some_button.png'); r.vision('keyUp(Key.CTRL)')
```

**Comment by yekunhui** [comment]
Thank you, the issue is resolved!
