### ISSUE TITLE
Multiple objects, search the top one only - try these

### ISSUE THREAD

**Issue by dickhfchan** [tebelorg/RPA-Python#547]
Hi,

I used the image for serching the coordination but there were multiple exactly matched objects in the screen. The library didn't always give me the first top object. How to let the library search from the top or give me the first top one?

Regards,
Dick Chan

**Comment by kensoh** [comment]
Hi @dickhfchan you can try to take a larger snapshot to capture more unique background. But if that is not possible, you can check SikuliX API and use r.vision() but I don't think it's straightforward to do.

**Comment by baramofme** [comment]
@dickhfchan Hi, How about using Sikuix [findall-maches](https://sikulix.github.io/docs/api/match/#findall-matches)?

Let me know if it worked for you. I'm interested to see if this works with rpa-python.

Refs in sikulix:
- https://valmore.work/sikulix-region/
- https://dejavuqa.tistory.com/168
