### ISSUE TITLE
click failed to work after close iframe - maybe identifier changed 

### ISSUE THREAD

**Issue by lj1029** [tebelorg/RPA-Python#549]
Hi @kensoh 
I am working with a web page that has a menu on the left side and a mainFrame on the right side. Inside the mainFrame, there is a button btnCommit. When I click btnCommit, it displays some data. Clicking on the data it will show a dialogiframe with detailed information.
The issue I’m encountering is as follows:
On the first iteration, everything works as expected.
During the second iteration of the loop, r.read() function works, r.click() function returns True, but does not open the dialogiframe. However, the data should be clicked get highlighted.
I have also tried clicking btnCommit during the second iteration, but it didn't work either.
Here is my code:
```
r.frame('mainFrame')
r.click('//*[@id="btnCommit"]')
r.frame()
r.wait(1)
while running:
    print('start')
    r.frame('mainFrame')
    print('mainframe',r.read('/html/body/div[1]/div[3]/div[3]/div[4]/div/table/tbody/tr[2]/td[4]/a'))
    r.click('/html/body/div[1]/div[3]/div[3]/div[4]/div/table/tbody/tr[2]/td[4]/a')
    r.wait(1)
    r.frame('dialogiframe')
    print('dialogiframe',r.read('/html/body/div[1]/div[1]/div[2]/ul/li/p'))
    r.frame()
    # close
    r.click('/html/body/div[5]/div/div/div[1]/div/div[1]/button')
    print('finish')
    r.wait(1)
```
![image](https://github.com/user-attachments/assets/d53858f8-138b-465a-88da-25e9eb253d1f)

Thank you for your help

**Comment by lj1029** [comment]
I have tried to use r.rclick() when I click btnCommit, right-click will open the menu. In the first iteration, it opens directly on the button, but in subsequent iterations, the position where the menu is opened has shifted as shown in the figure below.
![image](https://github.com/user-attachments/assets/426253c0-1355-4b6a-88a9-c219161433e8)

**Comment by kensoh** [comment]
Hi @lj1029 my best guess is in 2nd iteration the web element selector might have changed. So you can try to find the new identifier and use it for 2nd iteration.
