### ISSUE TITLE
telegram() service down - AutoSSL on server broken, meantime please use alternatives for notifications

### ISSUE THREAD

**Issue by kensoh** [tebelorg/RPA-Python#550]

**Comment by marcelocecin** [comment]
I use [Pipedream](https://pipedream.com/apps/telegram-bot-api)

**Comment by juanyacovino77** [comment]
do you guys know if this is going to be up somewhen?

**Comment by kensoh** [comment]
I've re-requested issue of new SSL certs and also ask server vendor to fix this. No ETA at the moment.

**Comment by marcelocecin** [comment]
@kensoh perhaps it would be interesting to add support for this platform: https://www.txthinking.com/talks/articles/are-whatsapp-signal-telegram-really-end-to-end-encrypted-en.article

**Comment by kensoh** [comment]
The telegram notification service is up now!

Server vendor can't do anything about it some issue with AutoSSL issuer, so I bought a SSL cert and install it myself.

Cc @juanyacovino77 and @marcelocecin
