### ISSUE TITLE
Issue when using function upload - only for css selectors, try this

### ISSUE THREAD

**Issue by phatberstromgg** [tebelorg/RPA-Python#551]
Your project is great, it's helping me a lot. However, I'm having trouble with the upload function, specifically the website I'm working on has multiple upload buttons, all of them have the same element like this 

''' < input _ngcontent-xri-c509 multiple id="file_upload" type="file" accept=".DOC,.DOCX,.PDF,.XLS,.XLSX,.TXT,.JPG,.JPEG,.PNG"> '''

As you can see, it's using multiple id. If I use the copy selector from the web, all of them will return #file_upload, with this value the upload function can upload the file successfully, but only to the first button position. 
Then I tried using full_xpath, the result returned True but no file was uploaded successfully, similar to xpath, because these elements are in different tables, their xpaths are roughly in the form 

//table/tr[3]/td[8]/mat-radio-group/div/div/div/div[2]/input[@id="file_upload"]
//table/tr[4]/td[8]/mat-radio-group/div/div/div/div[2]/input[@id="file_upload"]
//table/tr[5]/td[8]/mat-radio-group/div/div/div/div[2]/input[@id="file_upload"]. 

However, with both xpath and full_xpath, the click functions work, but the upload function reports True but no file is uploaded successfully like when I use #file_upload. Looking forward to hearing from you and your help, thanks.

**Comment by kensoh** [comment]
Hi @phatberstromgg there is technical limitation that upload() can only work with CSS selectors (see https://github.com/tebelorg/RPA-Python?tab=readme-ov-file#pro-functions)

Another problem is this website is badly designed with duplicated IDs which should be unique.

I can think of 2 ways you can try.

First way is your use dom() to change the ID to something unique before using upload(). But you need to be familiar with JavaScript code to query and make modifications.

Second way is use visual automation or keyboard step to visually automate clicking and uploading.
