### ISSUE TITLE
网页拖动滑块 - use hover('image.png') instead of hover('id') for visual automation

### ISSUE THREAD

**Issue by 491933243** [tebelorg/RPA-Python#552]
在使用hover('元素id')后，如何拖动这个滑块，使用r.mouse_x()、r.mouse_y()获取到的是当前鼠标的位置，不是这个元素的位置，我看在第一次hover('元素id')后鼠标并没有移动过去

**Comment by 491933243** [comment]
r.hover('//*[@id="slider"]')
    r.mouse('down')
    r.hover(r.mouse_x() + 30, r.mouse_y())
    r.mouse('up')
   r.mouse_x()没有获取到slider元素的位置

**Comment by kensoh** [comment]
Hi @491933243 I know why. If you use hover() with element ID it does not move mouse to web element. It only moves in the browser's backend memory. To actually move the mouse, use hover('image.png') where image.png is an image snapshot of the web element. This will actually move the mouse on the OS level to do what you want.

**Comment by 491933243** [comment]
Okay, got it, I also planned to try before, but it didn't success. Which folder should I put the image.png in

**Comment by kensoh** [comment]
Can put in the same folder as your python script / current working directory in Python
